        const emailData = [
    {
        "name": "Christopher Rodican",
        "email": "crodican@councilsepa.org",
        "date": "5/5/2025",
        "time": "10:38 AM",
        "subject": "RE: Assistance",
        "body": "Kristy, Thank you for reaching out and congratulations on your recovery journey. For individuals with lived experience in overcoming substance use disorder, becoming a Certified Recovery Specialist presents a remarkable opportunity to make a profound difference. This certification enables you to uniquely contribute to the recovery community by offering empathy, motivation, and support grounded in your personal journey. The CRS is not a sponsor, case manager, or a therapist, but we provide a distinct and necessary perspective as a role model, mentor, advocate, and motivator. As a CRS you would be illuminating the recovery process through the lens of your own success. If this sounds like what you are looking for, then so we can best assist you, can you tell me what counties you live in and work in? We hold several Recovery Specialist trainings in Southeast Pennsylvania a year, at no cost to the students, open to people who either live or work in the county that the training is held in. In order to get on our list to be contacted when we schedule a training in your county, please use the following link to complete our short Recovery Specialist Interest Survey. You'll be added to our list which is used to fill classes, so that when a training is available for you, we will contact you with the next steps: https://councilsepa.org/hubs/certifications/survey. Additionally, the Pennsylvania Certification Board keeps an updated list of all currently scheduled Recovery Specialist trainings across the state which you can periodically check at the following link, in case you see a suitable training offered by another organization. https://www.pacertboard.org/node/141627/classes. We are here to assist you if you have any additional questions or need assistance, so don't hesitate to reach out at CRSTrainingInfo@councilsepa.org. Best of luck, Kristy!",
        "county": "Unknown",
        "summary": "Christopher Rodican responds to Kristy's inquiry about becoming a CRS, providing comprehensive information about the certification, training availability, and next steps including the interest survey.",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "K j.",
        "email": "kccj33@gmail.com",
        "date": "4/26/2025",
        "time": "2:30 PM",
        "subject": "Assistance",
        "body": "Hello my name is Kristy and I am interested in training to become a recovery support specialist and offer assistance to individuals with all of my experience, education and skills I have gained over the past years. I graduated with a bachelor degree in social work and I have been on my own recovery journey since November 12 2022. I am around of my accomplishments thus far however, I want to make a career out of all my experiences. I am lost on how to get started and I'm reaching out for some direction. Thank you for your time. Kristy Jameson 6109062895",
        "county": "Unknown",
        "summary": "Kristy Jameson inquires about becoming a recovery support specialist, mentioning her BSW degree and recovery journey since November 2022.",
        "isInquiry": true,
        "isStaffResponse": false
    },
    {
        "name": "Jim Bollinger",
        "email": "jbollinger@councilsepa.org",
        "date": "5/6/2025",
        "time": "9:53 AM",
        "subject": "Learn to Share the Value of Peer Support with Providers & Communities – May 7 (ZOOM)",
        "body": "Hello, We're excited to invite you to an upcoming Information Session on Peer-Based Professional Services, presented by PaPSC. Date: Wednesday, May 7, 2025 Time: 10:00 AM – 11:30 AM Zoom Registration: https://us02web.zoom.us/meeting/register/6t0-Y9a4QP6L0Q2ORRP7Ow This presentation provides an in-depth overview of peer-based professionals and their unique role in behavioral health and recovery settings. Designed specifically for providers and service teams, the session explores the distinction between natural peer support and certified peer roles, outlines the credentialing process for Certified Peer Specialists (CPS) and Certified Recovery Specialists (CRS), and highlights the benefits of peer services within clinical and community environments. Participants will gain a better understanding of how peer professionals support recovery, collaborate with other providers, and contribute to person-centered care. Important Note: Please be aware that this is not a CEU training. We are unable to offer Continuing Education (CE) hours for this session, and attendees should not expect to receive them. While this may make it a less formal option, we believe the content is still highly beneficial and relevant for anyone interested in learning more about peer services. We appreciate your interest in our presentation and look forward to sharing this important conversation with you. If you have any questions, feel free to reach out.",
        "county": "Philadelphia",
        "summary": "Jim Bollinger announces an information session about peer-based professional services, explaining CPS and CRS roles for providers and service teams.",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Jim Bollinger",
        "email": "jbollinger@councilsepa.org",
        "date": "5/6/2025",
        "time": "4:45 PM",
        "subject": "Technical Tuesdays - TONIGHT - Learning Logistics - Register now!!",
        "body": "Hello, Technical Tuesdays is tonight on Zoom. Tonight's topic: Learning Logistics 1st Tuesday of every month Post Recovery Specialist Training Support: Have you completed the Recovery Specialist Training and are preparing for your exam? This week is for you! Topics include: exam readiness, test taking skills, support for outstanding assignments, and answers to questions you have about obtaining your credential. Register at the link below: https://bit.ly/HubVirtualMeeting Hope to see you there!",
        "county": "Philadelphia",
        "summary": "Jim Bollinger announces Technical Tuesdays session focused on post-training support for Recovery Specialist exam preparation and credential assistance.",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "James Vaughn",
        "email": "jvaughn267@gmail.com",
        "date": "5/7/2025",
        "time": "3:20 PM",
        "subject": "",
        "body": "I would like more information on the class that you offer.. I've been in recovery for 3 years now and i wanna do more with my knowledge and leadership skills and help people who suffer with addiction get the help they need... I wanna become a certified recovery specialist..",
        "county": "Unknown",
        "summary": "James Vaughn expresses interest in CRS training, mentioning 3 years in recovery and desire to use his experience to help others with addiction.",
        "isInquiry": true,
        "isStaffResponse": false
    },
    {
        "name": "Jim Bollinger",
        "email": "jbollinger@councilsepa.org",
        "date": "5/8/2025",
        "time": "9:11 AM",
        "subject": "\"Our Stories Have Power\" Training Opportunity",
        "body": "Greetings! The Recovery Hub is excited to offer three upcoming opportunities to attend Faces and Voices of Recovery's \"Our Stories Have Power\" training. This impactful two-day workshop is open to people in recovery, advocates, and family members. It is designed to empower participants to share their personal stories as a tool for advocacy, education, and connection. Continuing education hours will be available. Training Dates: Option 1 (Virtual): May 20 & 22, 2025 Link to register: Meeting Registration - Zoom Option 2 (Virtual): May 21 & 23, 2025 Meeting Registration - Zoom Option 3 (In-Person): June 23 & 24, 2025 Location: TBD To celebrate, we're hosting a special in-person gathering for all training participants on June 27, 2025. Please see the attached flyer for details, and feel free to share this invitation widely within your networks. We'd love to have you join us in lifting up the power of recovery stories.",
        "county": "Philadelphia",
        "summary": "Jim Bollinger announces \"Our Stories Have Power\" training opportunities for people in recovery to learn advocacy through storytelling, with virtual and in-person options.",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Jim Bollinger",
        "email": "jbollinger@councilsepa.org",
        "date": "5/8/2025",
        "time": "9:15 AM",
        "subject": "Fw: Riverview Wellness Village Referral Change",
        "body": "Please see attached email.",
        "county": "Philadelphia",
        "summary": "Jim Bollinger forwards information about changes to Riverview Wellness Village referral criteria, expanding from inpatient to include outpatient treatment participants.",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Christopher Rodican",
        "email": "crodican@councilsepa.org",
        "date": "5/8/2025",
        "time": "12:04 PM",
        "subject": "Re: CRS",
        "body": "Hi James, Congratulations on your recovery, I think it is awesome that you want to do more with your knowledge and leadership skills to help people in their own recovery journeys, and I would be happy to give you more information about our Recovery Specialist trainings. The CRS (Certified Recovery Specialist) is a professional who utilizes their training and the personal lived recovery experience that they bring to the table to offer empathy, motivation, and support to individuals in recovery. They may find themselves working with a caseload of individuals in the office or out in the community, or working in a hospital, connecting with individuals in crisis and helping them find the treatment they need, and there are several other roles and jobs that a CRS might find themselves working in. To become a Certified Recovery Specialist, someone must be a person with personal lived recovery experience ( and have at least 18 months in a continuous manner), and must have a high school diploma or a GED. The training is 78 hours in total, 75 hours of class time and three hours' worth of homework. Our trainings are generally two weeks, Monday through Friday, or ten Saturdays. So I can best assist you in locating a suitable training, can you tell me what counties you live in and work in?",
        "county": "Unknown",
        "summary": "Christopher Rodican responds to James Vaughn with detailed CRS information, explaining role, requirements, and training format while asking for county information.",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Fred Shue",
        "email": "FShue@councilsepa.org",
        "date": "5/8/2025",
        "time": "4:32 PM",
        "subject": "RE: CRS",
        "body": "To be clear Chris, it is 66 hours of class time, and 12 hours of homework. Thanks. -Fred",
        "county": "Unknown",
        "summary": "Fred Shue corrects Christopher Rodican's training hour information, clarifying it's 66 hours of class time and 12 hours of homework.",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Christopher Rodican",
        "email": "crodican@councilsepa.org",
        "date": "5/8/2025",
        "time": "5:32 PM",
        "subject": "RE: CRS",
        "body": "Much obliged, I'm sending a follow up to James now. 😊",
        "county": "Unknown",
        "summary": "Christopher Rodican acknowledges Fred's correction and indicates he'll send updated information to James.",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Christopher Rodican",
        "email": "crodican@councilsepa.org",
        "date": "5/8/2025",
        "time": "5:33 PM",
        "subject": "RE: CRS",
        "body": "James, That's actually 66 hours of class time and 12 hours of homework. Apologies",
        "county": "Unknown",
        "summary": "Christopher Rodican sends correction to James about the accurate training hours (66 class hours, 12 homework hours).",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Wyanda Holman",
        "email": "wyanda123@gmail.com",
        "date": "5/9/2025",
        "time": "7:26 AM",
        "subject": "CRS Training",
        "body": "Good morning, I am looking to start CRS training and enroll into your next course. I currently have a CPS certification and I have been working as an Outreach specialist for Veteran's Multi-Service Center. Can you send me the next class schedule? Thank you Wyanda Holman",
        "county": "Philadelphia",
        "summary": "Wyanda Holman, who already has CPS certification and works as an outreach specialist for veterans, inquires about CRS training schedule.",
        "isInquiry": true,
        "isStaffResponse": false
    },
    {
        "name": "Nik Loil",
        "email": "chanels20231@gmail.com",
        "date": "5/9/2025",
        "time": "3:31 PM",
        "subject": "Classes for CRS",
        "body": "Good Afternoon, My name is Chanel Suber I'm inquiring about classes to become a CRS. As someone in recovery I've had several various individuals help me along the way,I was able to open up to them and not feel judged because they understand everything that I'm going through. I have been clean since November 5th,2023 and I wouldn't have made it without help and support. I want to give back to those who are in the same position I used to be in. I would really like the opportunity to be able to enroll in trainings for both CRS/CPS. My contact information is 445-238-8868 And this is my personal email Thank you for your time Hope to hear from you soon",
        "county": "Unknown",
        "summary": "Chanel Suber inquires about CRS and CPS training, sharing her recovery journey since November 2023 and desire to help others in similar situations.",
        "isInquiry": true,
        "isStaffResponse": false
    },
    {
        "name": "Christopher Rodican",
        "email": "crodican@councilsepa.org",
        "date": "5/14/2025",
        "time": "9:25 AM",
        "subject": "RE: CRS Training",
        "body": "Wyanda, First let me say congratulations on your recovery, obtaining your CPS, and your outreach work! We facilitate several Recovery Specialist trainings in the city every year, and they are available to individuals who live or work in the city. They are provided at no cost to the student. As I see that you have filled out our interest survey form on 4/21, someone will be emailing you to give you the next steps when a training becomes available for you. I don't, however, have a schedule to be able to provide you with specifics beyond that. If you would like, you can periodically check the Pennsylvania Certification Board website's statewide list of upcoming Recovery Specialist trainings that people can apply for. While there aren't any Philadelphia trainings currently listed, it is updated all the time so you could check back weekly or even daily. Here is that page: https://www.pacertboard.org/node/141627/classes In addition to those facilitated by PRO-ACT, which you have already filled out the Interest Survey for, you can apply to trainings from other organizations. As it says at the top of the chart listing the classes, you'll want to email the facilitator on that page directly, rather than clicking the \"enroll\" button. Congratulations again on your recovery and the amazing things you are doing, and good luck!",
        "county": "Philadelphia",
        "summary": "Christopher Rodican responds to Wyanda Holman, congratulating her achievements and explaining the training process, noting she's already completed the interest survey.",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Christopher Rodican",
        "email": "crodican@councilsepa.org",
        "date": "5/14/2025",
        "time": "9:45 AM",
        "subject": "RE: Classes for CRS",
        "body": "Hi Chanel, Thank you for reaching out, and congratulations on your recovery! While I am not able to assist you with information about CPS certification, I can help provide info about getting CRS certification. The Certified Recovery Specialist certification offers a fantastic opportunity for individuals with at least 18 months in a continuous manner of personal, lived recovery experience to use that experience to assist individuals with their own recovery! In addition to the required minimum of 18 months, a high school diploma or GED is also required. So we can best assist you, can you tell me what counties you live in and work in? Additionally, please use the following link to complete our short Recovery Specialist Interest Survey. As soon as a training becomes available for you, we'll contact you with the next steps: https://councilsepa.org/hubs/certifications/survey If you would like, you can periodically check the Pennsylvania Certification Board website's statewide list of upcoming Recovery Specialist trainings that people can apply for. As of today, there are no Philadelphia trainings listed, but it is updated all the time so you should check back weekly or even daily. Here is that page: https://www.pacertboard.org/node/141627/classes In addition to those facilitated by PRO-ACT, which you have already filled out the Interest Survey for, you can apply to the trainings on that page that are from other organizations. As it says at the top of the chart listing the classes, you'll want to email the facilitator on that page directly, rather than clicking the \"enroll\" button. Congratulations again on your recovery, Chanel, and good luck!",
        "county": "Unknown",
        "summary": "Christopher Rodican responds to Chanel Suber with CRS information, explaining requirements and directing her to complete the interest survey and check the PCB website.",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Ann Archer",
        "email": "archer.ann0819@icloud.com",
        "date": "5/18/2025",
        "time": "12:28 PM",
        "subject": "How to get started",
        "body": "Hi, this is Ann Archer. I'm just reaching out to try and find out more information on the CRS certification and training if somebody could either give me an email back or give me a call at 304-702-9139 so I can get enrolled and get started as soon as possible thank you Ann Archer Sent from my iPhone",
        "county": "Unknown",
        "summary": "Ann Archer requests information about CRS certification and training, asking for email or phone contact to get started as soon as possible.",
        "isInquiry": true,
        "isStaffResponse": false
    },
    {
        "name": "Mathew Braciszewski",
        "email": "mathewbraciszewski@gmail.com",
        "date": "5/18/2025",
        "time": "9:03 PM",
        "subject": "Requesting Info for CRS classes",
        "body": "Good evening. I was referred to this contact about looking into certified recovery specialist classes and training and was told this was a great resource to look into. I myself am a personal 29 months into alcohol recovery and find myself between a rock and a purposeless place. These classes are something I'd love to talk more about and get some further details on to potentially look into as a future career path. If there is availability tomorrow to speak, I'd love to pick your brain and talk some more. My direct contact is 267-290-2585. Looking forward to speaking more. Best, Mat Braciszewski Sent from my iPhone",
        "county": "Unknown",
        "summary": "Mat Braciszewski, 29 months into alcohol recovery, seeks information about CRS classes as a potential career path and requests a phone conversation.",
        "isInquiry": true,
        "isStaffResponse": false
    },
    {
        "name": "Christopher Rodican",
        "email": "crodican@councilsepa.org",
        "date": "5/19/2025",
        "time": "8:38 AM",
        "subject": "RE: How to get started",
        "body": "Hi Ann, Thanks for reaching out! Congratulations on your interest, and to give you some more info, the Certified Recovery Specialist (CRS) is someone with personal experience in their own substance use disorder recovery. The CRS is not a therapist, a counselor, a sponsor, or a case manager. Instead, they are a professional who use their personal, lived recovery experience offer unique insights from their own journey, giving a kind of support that no one else can. The CRS's role is to be a role model, mentor, advocate, and motivator. For more info, please see https://www.pacertboard.org/crs. So I can best assist you, can you please tell me what counties you live in and work in? We offer several trainings a year across the southeast Pennsylvania region, and these trainings are available to individuals who live or work in the county where that training is conducted. These trainings are made available at no cost to the student. Please fill out this short survey form, and when a training becomes available for you, someone will contact you with the next steps to take: https://www.councilsepa.org/hubs/certifications/survey/ In addition to the trainings facilitated by PRO-ACT, you may want to see trainings offered by other organizations. The Pennsylvania Certification Board website contains a list of all the upcoming Recovery Specialist trainings in the state. The list contains the location, cost, and instructor's email for each training course. The list is updated all the time so you can check back weekly or even daily. If you find a training on that list you would like to apply to, email the instructor directly instead of using the green enroll button. Here is that page: https://www.pacertboard.org/node/141627/classes Don't forget to fill out the survey form and then email me back to let me know your counties. Best of luck, Ann!",
        "county": "Unknown",
        "summary": "Christopher Rodican responds to Ann Archer with comprehensive CRS information, explaining the role, requirements, and directing her to complete the interest survey.",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Christopher Rodican",
        "email": "crodican@councilsepa.org",
        "date": "5/19/2025",
        "time": "11:29 AM",
        "subject": "RE: Requesting Info for CRS classes",
        "body": "Hi Mat, Thank you so much for reaching out. It sounds like you're on an incredible journey with your recovery, and it's inspiring to hear about your interest in becoming a Certified Recovery Specialist. I can absolutely understand that feeling of being at a crossroads, and it's wonderful that you're exploring paths that could bring purpose and meaning. I'd be very happy to speak with you more about the CRS classes and training. I will plan to call you around 12:30 PM today. If you happen to miss my call, please feel free to call me back at your convenience. Looking forward to connecting with you.",
        "county": "Unknown",
        "summary": "Christopher Rodican responds warmly to Mat Braciszewski, acknowledging his recovery journey and scheduling a phone call to discuss CRS training.",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Christopher Rodican",
        "email": "crodican@councilsepa.org",
        "date": "5/19/2025",
        "time": "2:30 PM",
        "subject": "RE: Requesting Info for CRS classes",
        "body": "Mat, It was great having a chance to talk with you today. Here is some more information about Certified Recovery Specialist https://pacertboard.org/crs As discussed, we offer several trainings in Philadelphia each year, for people who live and/or work in the city, and the trainings are offered at no cost to the student. Please fill out this short survey form, so we can contact you with next steps when we have a training for you https://www.councilsepa.org/hubs/certifications/survey/ Additionally, to look into the CRS trainings offered by other organizations, the Pennsylvania Certification Board's website contains a list of all the upcoming Recovery Specialist trainings in the state. The list contains the location, cost, and instructor's email for each training course. The list is updated all the time so you can check back weekly or even daily. If you find a training on that list you would like to apply to, email the instructor directly instead of using the green enroll button. Here is that page: https://www.pacertboard.org/node/141627/classes Good luck!",
        "county": "Philadelphia",
        "summary": "Christopher Rodican follows up with Mat after their phone conversation, providing CRS resources, survey link, and PCB training information.",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Amber Moon",
        "email": "amberreneemoon41@gmail.com",
        "date": "5/19/2025",
        "time": "3:17 PM",
        "subject": "Possibility of joining class for missed class on multiple pathways",
        "body": "Good afternoon, My name is Amber Moon. I am currently enrolled in a CRS class and missed an hour and a half on day 2 for multiple pathways. Is it possible I could join in for that class? My graduation date is June 4th. My phone number is 267-808-2726. Thank you for your time, Amber Moon",
        "county": "Unknown",
        "summary": "Amber Moon, currently enrolled in CRS class, requests to make up missed time for multiple pathways section before her June 4th graduation.",
        "isInquiry": true,
        "isStaffResponse": false
    },
    {
        "name": "Gina Tomaselli",
        "email": "gina@sparkwellness.com",
        "date": "5/21/2025",
        "time": "6:22 PM",
        "subject": "information on classes",
        "body": "HI I have someone that is interested in becoming a CRS. Can you please send me info on your training and when the class opens up again. Thank you Gina Tomaselli ASW,CAAC Facility Director Spark Wellness LLC 301 Oxford Valley Rd Suite 1302A Yardley Pa 19067 office:267-399-3990 cell:267-994-4248 Gina@sparkwellness.com",
        "county": "Bucks",
        "summary": "Gina Tomaselli from Spark Wellness in Yardley requests CRS training information for someone interested in becoming certified.",
        "isInquiry": true,
        "isStaffResponse": false
    },
    {
        "name": "Kristan Waters",
        "email": "kristanakai1@gmail.com",
        "date": "5/21/2025",
        "time": "7:09 PM",
        "subject": "Certified Recovery Training",
        "body": "Hi, My name is Kristan Waters and I'm very much interested in the Certified Recovery Support Specialist Program. I currently live in Delaware County and I'm 40 years old with lived experience of alcohol and mental health. I can be reached at kristanakai1@gmail.com or 610-220-1858 Thank you Kristan Waters Sent from my iPhone",
        "county": "Delaware",
        "summary": "Kristan Waters from Delaware County expresses interest in CRS program, mentioning lived experience with alcohol and mental health challenges.",
        "isInquiry": true,
        "isStaffResponse": false
    },
    {
        "name": "Christopher Rodican",
        "email": "crodican@councilsepa.org",
        "date": "5/22/2025",
        "time": "3:46 PM",
        "subject": "RE: Certified Recovery Training",
        "body": "Kristan, Thanks so much for reaching out and congratulations on your recovery! Becoming Certified Recovery Specialist is a fantastic opportunity to use your personal, lived recovery experience to assist individuals with their own recovery! We conduct several Recovery Specialist trainings across the region each year, available to individuals who live or work in the county where the training is being conducted. These trainings are offered at no cost to the students. I see that you've already filled out our Recovery Specialist Interest Survey form yesterday, which is great! We use the list generated from that form to contact people to fill the trainings, so as soon as a training becomes available for you, we will contact you with the next steps for enrolling. Additionally, you can also check the Pennsylvania Certification Board website's statewide list of all upcoming Recovery Specialist trainings to see if another training is suitable for you in terms of cost and location. As the list is continually updated, you may want to check back regularly. If you see a course you want to apply for, it is best to contact the facilitator using the email provided in the list. It can be confusing, but the green \"Enroll\" button is actually for enrolling for the class portal. Here is the link to that list: https://www.pacertboard.org/node/141627/classes Best of luck!",
        "county": "Delaware",
        "summary": "Christopher Rodican responds to Kristan Waters, noting she completed the interest survey and explaining the training process and PCB resources.",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Kristan Waters",
        "email": "kristanakai1@gmail.com",
        "date": "5/22/2025",
        "time": "3:57 PM",
        "subject": "Re: Certified Recovery Training",
        "body": "Thank you so much for the info! And please do keep me updated on the free courses. Thanks Again Kristan Waters",
        "county": "Delaware",
        "summary": "Kristan Waters thanks Christopher for the information and requests to be kept updated on free courses.",
        "isInquiry": false,
        "isStaffResponse": false
    },
    {
        "name": "Christopher Rodican",
        "email": "crodican@councilsepa.org",
        "date": "5/27/2025",
        "time": "10:03 AM",
        "subject": "RE: CRS training inquiry",
        "body": "Jack, Congratulations on your recovery and thank you for reaching out! I apologize for the delay in getting back to you, your email was lost in the shuffle for some reason. So I can best assist you, could you please let me know what counties you live and/or work in? We hold several Recovery Specialist trainings in Southeast Pennsylvania a year, at no cost to the students, open to people who either live or work in the county that the training is held in. Please use the following link to complete our short Recovery Specialist Interest Survey form. As soon as a training becomes available for you, we'll contact you with the next steps: https://councilsepa.org/hubs/certifications/survey Additionally, the Pennsylvania Certification Board keeps a list of all the Recovery Specialist trainings across the state which are available to apply for. It is continually updated, so you can check it weekly or even daily: https://www.pacertboard.org/node/141627/classes Good luck!",
        "county": "Unknown",
        "summary": "Christopher Rodican apologizes for delayed response to Jack Lark's CRS inquiry and provides standard information about training process and resources.",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Jack Lark",
        "email": "jacklark3422@icloud.com",
        "date": "4/9/2025",
        "time": "5:42 PM",
        "subject": "CRS training inquiry",
        "body": "Hello my name is Jack Lark. I'm currently in recovery myself and am working in the field. A coworker of mine, recommend I reach out regarding CRS certification. I'm curious how I would be able to being the process of becoming a CRS. Thank you kindly With Unity, JL",
        "county": "Unknown",
        "summary": "Jack Lark, currently in recovery and working in the field, inquires about the CRS certification process based on a coworker's recommendation.",
        "isInquiry": true,
        "isStaffResponse": false
    },
    {
        "name": "Alison Dunn",
        "email": "adunn@councilsepa.org",
        "date": "5/28/2025",
        "time": "10:32 AM",
        "subject": "RE: Lisa Baxter",
        "body": "Hi Lisa, It is nice to meet you. We facilitate Recovery Specialist Trainings through the Pennsylvania Certification Board for individuals to receive the CRS, CFRS, or CRSS Credential. The counties we train in are Bucks, Berks, Chester, Delaware, Lancaster, Montgomery, Philadelphia, and Schuylkill Counties. Recovery Specialist Trainings are in person and have homework outside of class. We use our Recovery Specialist Training Interest Survey: https://bit.ly/RSTrainingsurvey. This survey is for anyone interested in becoming a CRS or CFRS. When a training becomes available in their area, we send an email with details and provide support for enrollment. Additionally, we've created a dedicated email for questions and inquiries about Recovery Specialist Classes: CRSTraininginfo@councilsepa.org. Here are some resources for you. You have a Regional Recovery Hub for Adams County. They may be able to assist you with locating a Recovery Specialist Class in your area. https://pmhca.wildapricot.org/Recovery-Hub Tristan Schnoke tristan@pmhca.org Pennsylvania Certification Board To learn more about the certifications themselves, you can visit the PA Certification Board website at: https://www.pacertboard.org/certifications Upcoming trainings throughout the state. https://www.pacertboard.org/recovery-specialist-curriculum I hope this information is helpful and what you are looking for. If you have any other questions, feel free to email or to give me a call.",
        "county": "Adams",
        "summary": "Alison Dunn responds to Lisa Baxter from Gettysburg (Adams County), explaining their training scope and directing her to Adams County Regional Recovery Hub resources.",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Lisa Baxter",
        "email": "baxtermlisa68@yahoo.com",
        "date": "5/26/2025",
        "time": "9:10 AM",
        "subject": "Lisa Baxter",
        "body": "Hello, My name is Lisa Baxter and I graduated from Hood College located in Frederick, Maryland with a social work degree. I am interested in the field of addiction and I am interested in signing up for classes. I currently live in Gettysburg, Pennsylvania and I am interested in online classes and I came across your website and I saw that classes are starting soon! If you could email or call me back regarding classes and certification guideline in PA I would appreciate it! Thank You, Lisa Baxter",
        "county": "Adams",
        "summary": "Lisa Baxter from Gettysburg with a social work degree expresses interest in addiction field training and asks about online classes and certification guidelines.",
        "isInquiry": true,
        "isStaffResponse": false
    },
    {
        "name": "Carolyn Mahn",
        "email": "carolynmahn81718@gmail.com",
        "date": "5/29/2025",
        "time": "3:50 PM",
        "subject": "Crs training Carolyn Suhrcke",
        "body": "Hello I was wondering how to apply or get started or find a course to become a crs if you could help with any info that would be great ! Thank you so much !! Carolyn rose suhrcke 570-202-2889 Sent from my iPhone",
        "county": "Unknown",
        "summary": "Carolyn Suhrcke requests information on how to apply for or find CRS training courses.",
        "isInquiry": true,
        "isStaffResponse": false
    },
    {
        "name": "Alison Dunn",
        "email": "adunn@councilsepa.org",
        "date": "5/29/2025",
        "time": "4:54 PM",
        "subject": "Makeup Class Information & Upcoming Opportunities",
        "body": "Hi Theresa, Here's a quick summary of the classes you missed: Day 3 – Learner Manual pages 32–45 Day 8 – Learner Manual pages 108–125 Day 10 – Learner Manual pages 140 to the end I'm glad you'll be able to attend Gina's class this Saturday, May 31, 2025. I hope you have a great experience! We also have an upcoming 10-day class starting next week in Schuylkill County, beginning Monday, June 2, 2025. Tentatively, Day 3 will fall on Wednesday, June 4, and Day 8 on Wednesday, June 11. Please note that the class flow may vary, so you'll need to check in with Fred to confirm which pages are being covered on each day. Please check with your employer regarding your availability and let us know if you're interested in attending. If this class doesn't work for you, we're planning another class in July in Montgomery County and can revisit your participation in that session depending on space. Location: Alvernia University 500 Progress Ave Pottsville, PA 17901 Additionally, here's a link to the PCB website listing other upcoming classes: https://www.pacertboard.org/recovery-specialist-curriculum If you see another class that fits your schedule, you can email the listed instructor directly to ask about availability. Be sure to mention which Learner Manual pages you need to make up. Let me know if you have any questions!",
        "county": "Schuylkill",
        "summary": "Alison Dunn provides Theresa with makeup class information for missed CRS training sessions and upcoming opportunities in Schuylkill and Montgomery counties.",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Teresa Fetzer",
        "email": "tfetzer35@gmail.com",
        "date": "5/29/2025",
        "time": "5:16 PM",
        "subject": "Re: Makeup Class Information & Upcoming Opportunities",
        "body": "Good evening, thank you Allison for your quick response and assistance. I will be there Saturday Gina, I look forward to attending.",
        "county": "Schuylkill",
        "summary": "Teresa Fetzer thanks Alison for the makeup class information and confirms she'll attend Gina's Saturday class.",
        "isInquiry": false,
        "isStaffResponse": false
    },
            {
                "name": "joshua shorts",
                "email": "joshuashorts232@yahoo.com",
                "date": "6/3/2025",
                "time": "2:49 PM",
                "subject": "Next available class",
                "body": "Hi my name is Joshua shorts and I m interested in the next class you have available to become a certified peer specialist please contact me via email or phone at 267 453 6181 thank you",
                "county": "Unknown",
                "summary": "Joshua Shorts expresses interest in becoming a certified peer specialist and requests contact via email or phone.",
                "isInquiry": true,
                "isStaffResponse": false
            },
            {
                "name": "Amy Legath",
                "email": "amylegath@gmail.com",
                "date": "6/3/2025",
                "time": "9:33 PM",
                "subject": "Recovery Specialist Training",
                "body": "Good Evening,  I am interested in enrolling in the Certified Recovery Specialist course. I am just shy of 19 months sober (AA) and have been interested in close to a year to complete this training program. What is the next step?  Warmest Regards,   Amy Legath",
                "county": "Unknown",
                "summary": "Amy inquires about enrolling in CRS course, mentions being shy of 19 months sober and interested for close to a year.",
                "isInquiry": true,
                "isStaffResponse": false
            },
            {
                "name": "Alison Dunn",
                "email": "adunn@councilsepa.org",
                "date": "6/10/2025",
                "time": "11:23 AM",
                "subject": "RE: CRS Training",
                "body": "Good morning Alyssa, Currently, we are taking applications to identify the class size. Could you follow back up with me around the beginning of July and I will have a better idea on if we can accommodate your make up days. Please let me know the exact Learner Manual pages you need to cover as each class can flow differently. Additionally, what class were you in and what county are you travelling from? Thank you, Ali Dunn, CRS/CFRS/CRSS",
                "county": "Montgomery",
                "summary": "Response to Alyssa Murriell about make-up days for Montgomery County training, requesting specific details and follow-up in July.",
                "isInquiry": false,
                "isStaffResponse": true
            },
            {
                "name": "Christopher Rodican",
                "email": "crodican@councilsepa.org",
                "date": "6/10/2025",
                "time": "2:21 PM",
                "subject": "RE: Crs training Carolyn Suhrcke",
                "body": "Carolyn, Thank you for reaching out, congratulations on your recovery, and on your interest in Recovery Specialist certification.  The CRS is for individuals with personal, lived recovery experience, and it's a wonderful way to your personal, lived recovery experience to assist other individuals in recovery from substance use disorder as a role model, mentor, advocate, and motivator.     To better assist you, could you please let us know the counties where you live and work?     We offer several Recovery Specialist trainings in Southeast Pennsylvania each year at no cost to the participants.  These trainings are available to individuals who live or work in the county where the training is conducted.  Please fill out this short Recovery Specialist Interest Survey form, and someone will contact you with the next steps when a suitable training is available for you.",
                "county": "Unknown",
                "summary": "Response to Carolyn Mahn providing comprehensive CRS training information, survey link, and PCB training list.",
                "isInquiry": false,
                "isStaffResponse": true
            },
            {
                "name": "Anita James",
                "email": "anitajames1306@icloud.com",
                "date": "6/12/2025",
                "time": "11:36 AM",
                "subject": "CRS Course Inquiry",
                "body": "Hello my name is Anita.  I am interested in taking the CRS course. I have 2 years and 7 months clean, I also have been working one treatment as a BHT for 18 months. You can contact me at 445-224-8978 or my email. Thank you so much for your time. Have a wonderful day.",
                "county": "Unknown",
                "summary": "Anita expresses interest in CRS course, mentions 2 years 7 months clean and 18 months working in treatment as BHT.",
                "isInquiry": true,
                "isStaffResponse": false
            },
            {
                "name": "Christopher Rodican",
                "email": "crodican@councilsepa.org",
                "date": "6/12/2025",
                "time": "2:46 PM",
                "subject": "RE: CRS Course Inquiry",
                "body": "Hi Anita,  Thanks for reaching out!  To better assist you, could you please let us know the counties where you live and work?  We offer several Recovery Specialist trainings in Southeast Pennsylvania each year at no cost to the participants.  These trainings are available to individuals who live or work in the county where the training is conducted.  Please fill out this short Recovery Specialist Interest Survey form, and someone will contact you with the next steps when a suitable training is available for you.  [link]  In the meantime, the Pennsylvania Certification Board keeps an up to date list of every upcoming Recovery Specialist training across the state.  You can always check it regularly in case there is another organization with a suitable Recovery Specialist training for you.  The prices for the trainings, the locations, the dates, and instructor's contact info are included.  If interested in a class, rather than click the green enroll button, you will want to email the instructor.  [link] Best of luck to you!",
                "county": "Unknown",
                "summary": "Response to Anita James asking for county information and providing Recovery Specialist Interest Survey and PCB training list.",
                "isInquiry": false,
                "isStaffResponse": true
            },
            {
                "name": "Christopher Rodican",
                "email": "crodican@councilsepa.org",
                "date": "6/12/2025",
                "time": "2:51 PM",
                "subject": "RE: Recovery Specialist Training",
                "body": "Joshua,  A Certified Recovery Specialist is an individual who has lived experience with substance use disorder recovery and is certified to provide peer support to others on their recovery journey.  A CPS (Certified Peer Specialist), on the other hand, is an individual who has lived experience with mental health challenges and recovery and is certified to provide peer support to others facing similar struggles.  Both CRS and CPS are types of 'peer specialists'. They are trained and certified by the Pennsylvania Certification Board (PCB).  Which certification were you inquiring about?",
                "county": "Chester",
                "summary": "Response to Amy Legath congratulating her recovery, requesting county info, and providing survey link and training resources.",
                "isInquiry": false,
                "isStaffResponse": true
            },
            {
                "name": "Amy Legath",
                "email": "amylegath@gmail.com",
                "date": "6/12/2025",
                "time": "2:57 PM",
                "subject": "Re: Recovery Specialist Training",
                "body": "                                                                                                                                                                                                                                                                       ",
                "county": "Chester",
                "summary": "Amy specifies Chester County location, requests low-cost Saturday training due to full-time work and caring for autistic son.",
                "isInquiry": true,
                "isStaffResponse": false
            },
            {
                "name": "Christopher Rodican",
                "email": "crodican@councilsepa.org",
                "date": "6/12/2025",
                "time": "2:58 PM",
                "subject": "RE: Next available class",
                "body": "",
                "county": "Unknown",
                "summary": "Response to Joshua Shorts explaining difference between CRS and CPS certifications and asking which he was interested in.",
                "isInquiry": false,
                "isStaffResponse": true
            },
            {
                "name": "Christopher Rodican",
                "email": "crodican@councilsepa.org",
                "date": "6/12/2025",
                "time": "3:27 PM",
                "subject": "RE: Recovery Specialist Training",
                "body": "",
                "county": "Montgomery",
                "summary": "Follow-up to Amy providing Pottstown training link and PCB statewide list, noting weekday schedule and limited slots.",
                "isInquiry": false,
                "isStaffResponse": true
            },
            {
                "name": "Amy Legath",
                "email": "amylegath@gmail.com",
                "date": "6/12/2025",
                "time": "3:43 PM",
                "subject": "Re: Recovery Specialist Training",
                "body": "",
                "county": "Chester",
                "summary": "Amy mentions Pottstown is too far from Coatesville, asks about Reading/Lancaster options and password issues.",
                "isInquiry": true,
                "isStaffResponse": false
            },
            {
                "name": "Alyssa Brennan",
                "email": "abrennan1991@icloud.com",
                "date": "6/12/2025",
                "time": "6:17 PM",
                "subject": "CRS",
                "body": "",
                "county": "Bucks",
                "summary": "Alyssa requests information about getting CRS certification and guidance on the process.",
                "isInquiry": true,
                "isStaffResponse": false
            },
            {
                "name": "Christopher Rodican",
                "email": "crodican@councilsepa.org",
                "date": "6/13/2025",
                "time": "6:29 PM",
                "subject": "Re: Recovery Specialist Training",
                "body": "",
                "county": "Unknown",
                "summary": "Clarification to Amy about enrollment process - explaining to email instructor rather than use green enrollment button.",
                "isInquiry": false,
                "isStaffResponse": true
            },
            {
                "name": "Alison Dunn",
                "email": "adunn@councilsepa.org",
                "date": "6/16/2025",
                "time": "9:44 AM",
                "subject": "RE: Trying to register for the crs course",
                "body": "",
                "county": "Montgomery",
                "summary": "Response to Ange about Montgomery County training registration, providing flyer and application link with June 30th deadline.",
                "isInquiry": false,
                "isStaffResponse": true
            },
            {
                "name": "Alison Dunn",
                "email": "adunn@councilsepa.org",
                "date": "6/16/2025",
                "time": "9:51 AM",
                "subject": "RE: CFRS training July",
                "body": "",
                "county": "Montgomery",
                "summary": "Response to Diane from Exton Parents about July CFRS training, mentions blended CRS/CFRS class with high interest.",
                "isInquiry": false,
                "isStaffResponse": true
            },
            {
                "name": "Christopher Rodican",
                "email": "crodican@councilsepa.org",
                "date": "6/16/2025",
                "time": "10:14 AM",
                "subject": "Re: CRS",
                "body": "",
                "county": "Bucks",
                "summary": "Response to Alyssa Brennan providing CRS info, noting she's from Bucks County, and offering Pottstown training option.",
                "isInquiry": false,
                "isStaffResponse": true
            },
            {
                "name": "Alison Dunn",
                "email": "adunn@councilsepa.org",
                "date": "6/16/2025",
                "time": "10:36 AM",
                "subject": "Recovery Specialist interest Survey",
                "body": "",
                "county": "Unknown",
                "summary": "Providing Recovery Specialist Training Interest Survey link to Serephine for future training notifications.",
                "isInquiry": false,
                "isStaffResponse": true
            },
            {
                "name": "Alison Dunn",
                "email": "adunn@councilsepa.org",
                "date": "6/16/2025",
                "time": "2:34 PM",
                "subject": "RE: Recovery Specialist Cert Program",
                "body": "",
                "county": "Montgomery",
                "summary": "Response to Joanna Roth about Montgomery County training enrollment, providing application process details.",
                "isInquiry": false,
                "isStaffResponse": true
            },
            {
                "name": "Joanna Roth",
                "email": "joannaroth84@gmail.com",
                "date": "6/16/2025",
                "time": "2:54 PM",
                "subject": "Re: Recovery Specialist Cert Program",
                "body": "",
                "county": "Montgomery",
                "summary": "Joanna confirms she found the application link in flyer and submitted her application, thanks Alison for quick response.",
                "isInquiry": true,
                "isStaffResponse": false
            },
            {
                "name": "Christopher Rodican",
                "email": "crodican@councilsepa.org",
                "date": "6/16/2025",
                "time": "3:01 PM",
                "subject": "RE: Next available class",
                "body": "",
                "county": "Unknown",
                "summary": "Follow-up to Joshua after phone conversation, providing Recovery Specialist Interest Survey and PCB training list guidance.",
                "isInquiry": false,
                "isStaffResponse": true
            },
            {
                "name": "Alison Dunn",
                "email": "adunn@councilsepa.org",
                "date": "6/17/2025",
                "time": "2:19 PM",
                "subject": "RE: CRS program information: Jasmine Baez",
                "body": "",
                "county": "Montgomery",
                "summary": "Response to Jasmine providing Montgomery County training application process and deadline information.",
                "isInquiry": false,
                "isStaffResponse": true
            },
            {
                "name": "Joan Rajkowski",
                "email": "djraj1128@gmail.com",
                "date": "6/21/2025",
                "time": "9:26 PM",
                "subject": "CRS Training program",
                "body": "Hi, My name is Joanie Rajkowski.  I have applied to the program in the past and I thought I got a seat but never heard back from anyone that I left messages to. I would like to apply again and hope to get in for the 2 Weeks or the Saturday program preferably because I m looking actively for employment to work during the week.  Please get back to me and I will redo The application.  Thank you for your time and consideration.  Sincerely,  Joan Rajkowski  215-869-6101",
                "county": "Unknown",
                "summary": "Joan mentions previous application issues, seeks 2-week or Saturday program due to active job searching during weekdays.",
                "isInquiry": true,
                "isStaffResponse": false
            },
            {
                "name": "Alison Dunn",
                "email": "adunn@councilsepa.org",
                "date": "6/23/2025",
                "time": "4:25 PM",
                "subject": "RE: Recovery Specialist Training",
                "body": "",
                "county": "Montgomery",
                "summary": "Response to Debbie Soto-Vega noting Montgomery County class may be full, providing application info and interest survey.",
                "isInquiry": false,
                "isStaffResponse": true
            },
            {
                "name": "Alison Dunn",
                "email": "adunn@councilsepa.org",
                "date": "6/23/2025",
                "time": "4:30 PM",
                "subject": "RE: Recovery Specialist Training",
                "body": "",
                "county": "Berks",
                "summary": "Response to Andrea Rose about Kelly Schaeffer's memorial service conflict, noting class appears full.",
                "isInquiry": false,
                "isStaffResponse": true
            },
            {
                "name": "Alison Dunn",
                "email": "adunn@councilsepa.org",
                "date": "6/23/2025",
                "time": "4:32 PM",
                "subject": "Recovery Specialist Interest Survey",
                "body": "",
                "county": "Unknown",
                "summary": "Providing Jackie with Montgomery County training info noting class may be full, plus Philadelphia training options.",
                "isInquiry": false,
                "isStaffResponse": true
            },
            {
                "name": "Alison Dunn",
                "email": "adunn@councilsepa.org",
                "date": "6/25/2025",
                "time": "12:11 PM",
                "subject": "RE: CRS CLASSES",
                "body": "",
                "county": "Montgomery",
                "summary": "Response to Brendan Bungay explaining Montgomery County class appears full, providing application process details.",
                "isInquiry": false,
                "isStaffResponse": true
            },
            {
                "name": "Andrea Rose",
                "email": "arose@recoverycoachingservices.com",
                "date": "6/26/2025",
                "time": "11:55 AM",
                "subject": "Re: Recovery Specialist Training",
                "body": "",
                "county": "Berks",
                "summary": "Andrea confirms Montgomery class is full and Kelly can't attend, asks about future training availability.",
                "isInquiry": true,
                "isStaffResponse": false
            },
            {
                "name": "R Wills",
                "email": "rafiya127@gmail.com",
                "date": "7/22/2025",
                "time": "4:48 PM",
                "subject": "CRS",
                "body": "",
                "county": "Unknown",
                "summary": "Rafiya Williams requests to join CRS training and provides phone number 2679007117.",
                "isInquiry": true,
                "isStaffResponse": false
            },
            {
                "name": "R Wills",
                "email": "rafiya127@gmail.com",
                "date": "7/22/2025",
                "time": "4:51 PM",
                "subject": "CRS TRAINING",
                "body": "",
                "county": "Unknown",
                "summary": "Follow-up email from Rafiya Williams expressing interest in CRS training.",
                "isInquiry": true,
                "isStaffResponse": false
            },
            {
                "name": "Alison Dunn",
                "email": "adunn@councilsepa.org",
                "date": "7/23/2025",
                "time": "12:35 PM",
                "subject": "Recovery Specialist Interest Survey",
                "body": "",
                "county": "Unknown",
                "summary": "Response to artis1214@gmail.com providing Recovery Specialist Interest Survey link and upcoming class information.",
                "isInquiry": false,
                "isStaffResponse": true
            },
            {
                "name": "Jennifer Carroll",
                "email": "jacrroll@councilsepa.org",
                "date": "7/23/2025",
                "time": "1:35 PM",
                "subject": "Recovery Specialist Training Interest Survey",
                "body": "",
                "county": "Unknown",
                "summary": "Response to Lisa (lisamensch094@gmail.com) with interest survey link and information about enrollment process.",
                "isInquiry": false,
                "isStaffResponse": true
            },
            {
                "name": "Jennifer Carroll",
                "email": "jacrroll@councilsepa.org",
                "date": "7/23/2025",
                "time": "1:48 PM",
                "subject": "Recovery Specialist Interest Survey",
                "body": "",
                "county": "Unknown",
                "summary": "Standard response template providing Recovery Specialist Interest Survey link for enrollment.",
                "isInquiry": false,
                "isStaffResponse": true
            },
            {
                "name": "quarantine@messaging.microsoft.com",
                "email": "",
                "date": "7/23/2025",
                "time": "6:09 PM",
                "subject": "Microsoft 365 security: You have messages in quarantine",
                "body": "",
                "county": "Unknown",
                "summary": "Microsoft security notification about quarantined message from malcolmb2595@gmail.com flagged as phishing.",
                "isInquiry": false,
                "isStaffResponse": false
            },
            {
                "name": "Christopher Rodican",
                "email": "crodican@councilsepa.org",
                "date": "7/25/2025",
                "time": "8:46 AM",
                "subject": "RE: CRS TRAINING",
                "body": "",
                "county": "Unknown",
                "summary": "Response to Rafiya Williams explaining CRS certification requirements, asking for location details, and providing survey link and training information.",
                "isInquiry": false,
                "isStaffResponse": true
            },
            {
                "name": "Christopher Rodican",
                "email": "crodican@councilsepa.org",
                "date": "7/27/2025",
                "time": "6:30 PM",
                "subject": "test",
                "body": "",
                "county": "Unknown",
                "summary": "Internal test email with no content.",
                "isInquiry": false,
                "isStaffResponse": false
            },
            {
                "name": "Christopher Rodican",
                "email": "christopher.rodican@gmail.com",
                "date": "7/27/2025",
                "time": "6:37 PM",
                "subject": "test email",
                "body": "",
                "county": "Unknown",
                "summary": "External test email from Christopher Rodican's personal Gmail account.",
                "isInquiry": false,
                "isStaffResponse": false
            },
            {
                "name": "Christina Pooler",
                "email": "christina.pooler@gmail.com",
                "date": "7/28/2025",
                "time": "9:41 AM",
                "subject": "CRS Training",
                "body": "",
                "county": "Delaware",
                "summary": "Inquiry from Delaware County resident about CRS training availability, format, location, prerequisites, and costs. Mentions 3 years sobriety.",
                "isInquiry": true,
                "isStaffResponse": false
            },
            {
                "name": "Christopher Rodican",
                "email": "crodican@councilsepa.org",
                "date": "7/29/2025",
                "time": "10:00 AM",
                "subject": "RE: Recovery Specialist Training",
                "body": "",
                "county": "Delaware",
                "summary": "Response to Shawn confirming he's on waiting list for Delaware County training and providing alternative training options.",
                "isInquiry": false,
                "isStaffResponse": true
            },
            {
                "name": "Christopher Rodican",
                "email": "crodican@councilsepa.org",
                "date": "7/29/2025",
                "time": "1:25 PM",
                "subject": "RE: Recovery Specialist Training",
                "body": "",
                "county": "Berks",
                "summary": "Instructions for Shawn on how to contact facilitator for Reading training enrollment.",
                "isInquiry": false,
                "isStaffResponse": true
            },
            {
                "name": "Alison Dunn",
                "email": "adunn@councilsepa.org",
                "date": "7/29/2025",
                "time": "2:07 PM",
                "subject": "Bucks County Recovery Specialist Training - October 2025",
                "body": "",
                "county": "Bucks",
                "summary": "Mass email to Bucks County residents about October 2025 Recovery Specialist Training with registration link.",
                "isInquiry": false,
                "isStaffResponse": true
            },
            {
                "name": "Sean Ripley",
                "email": "smripley@gmail.com",
                "date": "7/29/2025",
                "time": "2:09 PM",
                "subject": "Re: Bucks County Recovery Specialist Training - October 2025",
                "body": "",
                "county": "Bucks",
                "summary": "Positive response from Sean Ripley confirming he will register for the October Bucks County training.",
                "isInquiry": true,
                "isStaffResponse": false
            },
            {
                "name": "Alison Dunn",
                "email": "adunn@councilsepa.org",
                "date": "7/29/2025",
                "time": "2:10 PM",
                "subject": "RE: Bucks County Recovery Specialist Training - October 2025",
                "body": "",
                "county": "Bucks",
                "summary": "Brief acknowledgment response to Sean Ripley wishing him a great day.",
                "isInquiry": false,
                "isStaffResponse": true
            },
            {
                "name": "Casilyn Papiro",
                "email": "casipapirio@gmail.com",
                "date": "7/29/2025",
                "time": "2:30 PM",
                "subject": "Re: Bucks County Recovery Specialist Training - October 2025",
                "body": "",
                "county": "Bucks",
                "summary": "Casilyn Papirio explains she already completed training but certification lapsed during breast cancer recovery; she's been in remission for 3 years and ready to return to work.",
                "isInquiry": true,
                "isStaffResponse": false
            },
            {
                "name": "tania_oneill25",
                "email": "tania_oneill25@yahoo.com",
                "date": "7/29/2025",
                "time": "3:31 PM",
                "subject": "RE: Bucks County Recovery Specialist Training - October 2025",
                "body": "",
                "county": "Bucks",
                "summary": "Tania O'Neill expresses interest in October training but needs information about funding or financial assistance.",
                "isInquiry": true,
                "isStaffResponse": false
            },
            {
                "name": "Alison Dunn",
                "email": "adunn@councilsepa.org",
                "date": "7/30/2025",
                "time": "9:14 AM",
                "subject": "RE: Bucks County Recovery Specialist Training - October 2025",
                "body": "",
                "county": "Bucks",
                "summary": "Response to Tania directing her to complete registration form for information about funding, as this training is not facilitated by their organization.",
                "isInquiry": false,
                "isStaffResponse": true
            },
            {
                "name": "Alison Dunn",
                "email": "adunn@councilsepa.org",
                "date": "7/30/2025",
                "time": "9:21 AM",
                "subject": "RE: Bucks County Recovery Specialist Training - October 2025",
                "body": "",
                "county": "Bucks",
                "summary": "Response to Trevor Hahn about TMS account requirement and Keystone Login setup instructions for registration.",
                "isInquiry": false,
                "isStaffResponse": true
            },
            {
                "name": "Christopher Rodican",
                "email": "crodican@councilsepa.org",
                "date": "7/31/2025",
                "time": "2:05 PM",
                "subject": "RE: [blank]",
                "body": "",
                "county": "Berks",
                "summary": "Clarification to Shawn about contacting the correct facilitator for Reading training, includes training list link.",
                "isInquiry": false,
                "isStaffResponse": true
            },
            {
                "name": "Alison Dunn",
                "email": "adunn@councilsepa.org",
                "date": "8/1/2025",
                "time": "10:12 AM",
                "subject": "Recovery Specialist Interest Survey and Upcoming Bucks County Recovery Specialist Training - October 2025",
                "body": "",
                "county": "Bucks",
                "summary": "Outreach to Elvin Colon at Pocono MRC sharing interest survey and October Bucks County training information.",
                "isInquiry": false,
                "isStaffResponse": true
            },
            {
                "name": "Christopher Rodican",
                "email": "crodican@councilsepa.org",
                "date": "8/1/2025",
                "time": "1:42 PM",
                "subject": "RE: Re:",
                "body": "",
                "county": "Unknown",
                "summary": "Follow-up with Shawn confirming phone number (267-817-4972) and offering continued assistance.",
                "isInquiry": false,
                "isStaffResponse": true
            },
            {
                "name": "Jacquelyn Hagen",
                "email": "hagenjacquelyn7@gmail.com",
                "date": "8/4/2025",
                "time": "1:21 PM",
                "subject": "Re: Bucks County Recovery Specialist Training - October 2025",
                "body": "",
                "county": "Bucks",
                "summary": "Jacquelyn mentions being on waitlist for Saturday Philadelphia class through Jennifer Carroll, asks about Saturday options in Bucks County.",
                "isInquiry": true,
                "isStaffResponse": false
            },
            {
                "name": "Ashley Crozier",
                "email": "croziera@live.bucks.edu",
                "date": "8/8/2025",
                "time": "6:48 AM",
                "subject": "Re: Bucks County Recovery Specialist Training - October 2025",
                "body": "",
                "county": "Bucks",
                "summary": "Ashley asks about weekend-only availability due to current employment schedule preventing weekday attendance.",
                "isInquiry": true,
                "isStaffResponse": false
            },
            {
                "name": "Alison Dunn",
                "email": "adunn@councilsepa.org",
                "date": "8/8/2025",
                "time": "10:02 AM",
                "subject": "RE: CFRS Trainings?",
                "body": "",
                "county": "Chester",
                "summary": "Response to Kim Porter about CFRS training availability, mentions no current CFRS-specific training scheduled but one planned for later in year. Provides interest survey and Chester County PSEI option.",
                "isInquiry": false,
                "isStaffResponse": true
            },
            {
                "name": "Kim Porter",
                "email": "kim@conversation.zone",
                "date": "8/8/2025",
                "time": "11:42 AM",
                "subject": "Re: CFRS Trainings?",
                "body": "",
                "county": "Unknown",
                "summary": "Kim Porter thanks Alison for helpful information and confirms she'll pass along info to Synergy House.",
                "isInquiry": false,
                "isStaffResponse": false
            }
        ];