const emailData = [
    {
        "from": "Alison Dunn",
        "email": "adunn@councilsepa.org",
        "date": "8/1/2025",
        "time": "10:12 AM",
        "county": "Staff",
        "subject": "Recovery Specialist Interest Survey and Upcoming Bucks County Recovery Specialist Training - October 2025",
        "body": "Good morning Elvin, I wanted to share our Recovery Specialist Interest Survey with you. When completed, you'll be among the first to be contacted when registration opens for new classes in our region. This survey is open to anyone interested in becoming a Certified Recovery Specialist (CRS) or Certified Family Recovery Specialist (CFRS). We encourage you to stay connected with the Recovery Hub for updates, events, and additional opportunities...",
        "summary": "Alison Dunn provides CRS training information to Elvin",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "from": "Christopher Rodican",
        "email": "crodican@councilsepa.org",
        "date": "8/1/2025",
        "time": "1:42 PM",
        "county": "Staff",
        "subject": "RE: Re:",
        "body": "Hi Shawn, Ok good luck and reach back out if you have any questions! PS. Yes, 267-817-4972 is me. Most of us at PRO-ACT have 267-817 phone numbers, so you know if you see one that it's us.",
        "summary": "Christopher Rodican responds to program inquiry",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "from": "Shawn",
        "email": "shawntmvp352@gmail.com",
        "date": "7/31/2025",
        "time": "4:38 PM",
        "county": "Delaware",
        "subject": "Re:",
        "body": "Hi Christopher I looked into that particular course and it's in Berks County which would be too far for me to make it to class so I'll just wait until something comes up for Delaware County or one that would accept me that I could make even if I'm in a different County. Sorry I missed your call and thank you hopefully one will come up soon again thank you",
        "summary": "Shawn inquires about training options in Delaware County",
        "isInquiry": true,
        "isStaffResponse": false
    },
    {
        "from": "Jacquelyn Hagen",
        "email": "hagenjacquelyn7@gmail.com",
        "date": "8/4/2025",
        "time": "1:21 PM",
        "county": "Bucks",
        "subject": "Re: Bucks County Recovery Specialist Training - October 2025",
        "body": "Hi Alison, I did reach out to Jennifer and she said she was able to put me in the wait list for the next Saturday Philadelphia class. She said she was going to reach out to you as well and discuss the matter. I'm unaware if you offer Saturday options in the Bucks County area. Please let me know as it is closer to my residence. I hope to hear back from you soon. Thank you and have a wonderful day.",
        "summary": "Jacquelyn Hagen requests weekend training options",
        "isInquiry": true,
        "isStaffResponse": false
    },
    {
        "from": "Ashley Crozier",
        "email": "croziera@live.bucks.edu",
        "date": "8/8/2025",
        "time": "6:48 AM",
        "county": "Bucks",
        "subject": "Re: Bucks County Recovery Specialist Training - October 2025",
        "body": "Hi, Would there be any availability on the weekends only? I am currently employed, and I am unable to attend any of those classes during the weekday. Thank you, Ashley Crozier",
        "summary": "Ashley Crozier requests weekend training options",
        "isInquiry": true,
        "isStaffResponse": false
    },
    {
        "from": "Alison Dunn",
        "email": "adunn@councilsepa.org",
        "date": "8/8/2025",
        "time": "10:02 AM",
        "county": "Staff",
        "subject": "RE: CFRS Trainings?",
        "body": "Good morning Kim, I hope you're enjoying the summer! My apologies for the delayed response. I was out sick for a few days, and Fred has also been off. At this time, we haven't scheduled another CFRS-specific training, but we do plan to offer another this year. Anyone interested in becoming a Certified Recovery Specialist (CRS) or Certified Family Recovery Specialist (CFRS) is welcome to complete our Recovery Specialist Interest Survey...",
        "summary": "Alison Dunn provides CFRS training information",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "from": "Kim Porter",
        "email": "kim@conversation.zone",
        "date": "8/8/2025",
        "time": "11:42 AM",
        "county": "Chester",
        "subject": "Re: CFRS Trainings?",
        "body": "Thank you so much, Ali! This is very helpful. I'll pass along the info to Synergy!",
        "summary": "Kim Porter inquires about CFRS training for Chester County",
        "isInquiry": true,
        "isStaffResponse": false
    },
    {
        "from": "Alison Dunn",
        "email": "adunn@councilsepa.org",
        "date": "8/12/2025",
        "time": "2:33 PM",
        "county": "Staff",
        "subject": "Recovery Specialist Interest Survey, PCB Website for RS Trainings, and Recovery Hub Email",
        "body": "Hello Joel, Below are the resources we discussed for individuals interested in Recovery Specialist Trainings. Please feel free to share them with individuals. Recovery Specialist Interest Survey - This survey is open to anyone interested in becoming a Certified Recovery Specialist (CRS) or Certified Family Recovery Specialist (CFRS). When completed, individuals will be among the first to be contacted when registration opens for new classes in our region...",
        "summary": "Alison Dunn provides training resources and contact information",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "from": "Joel Shafer-Harris",
        "email": "Shafer-HarrisJ@co.delaware.pa.us",
        "date": "8/12/2025",
        "time": "2:50 PM",
        "county": "Delaware",
        "subject": "RE: (EXTERNAL) [External] Recovery Specialist Interest Survey, PCB Website for RS Trainings, and Recovery Hub Email",
        "body": "Thanks very much Please note the Case Management email changes below",
        "summary": "Joel Shafer-Harris responds with contact information updates",
        "isInquiry": true,
        "isStaffResponse": false
    },
    {
        "from": "Alison Dunn",
        "email": "adunn@councilsepa.org",
        "date": "8/13/2025",
        "time": "4:11 PM",
        "county": "Staff",
        "subject": "RE: Bucks County Recovery Specialist Training - October 2025",
        "body": "Hi Kelly, We are not facilitating this training; we just assisted with promotion. The facilitator is Martha Thompson and her email is drmartha@empowerthemind.org. You would want to confirm with her if you are on their waitlist. For the Recovery Hub, below are a few resources: Recovery Specialist Interest Survey - This survey is open to anyone interested in becoming a Certified Recovery Specialist (CRS) or Certified Family Recovery Specialist (CFRS)...",
        "summary": "Alison Dunn provides facilitator contact and training resources",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "from": "Kelly Greer",
        "email": "kellygreer659@gmail.com",
        "date": "8/12/2025",
        "time": "1:40 PM",
        "county": "Bucks",
        "subject": "Re: Bucks County Recovery Specialist Training - October 2025",
        "body": "Hi Alison, I registered for this class but just wanted to be sure that it was full and I am on the waiting list? If so, where can I look to see when additional classes are scheduled in Bucks County? Thank you!",
        "summary": "Kelly Greer inquires about waitlist status",
        "isInquiry": true,
        "isStaffResponse": false
    },
    {
        "from": "Kim Christner",
        "email": "kmbrgrl@yahoo.com",
        "date": "8/13/2025",
        "time": "10:21 PM",
        "county": "Bucks",
        "subject": "Recovery specialists",
        "body": "My name is Kim Christner. I have been sober for quite some time and am looking to take the recovery specialist training class. If you would please let me know when the next one becomes available, I'd greatly appreciate it. Thank you and have a blessed day.",
        "summary": "Kim Christner inquires about CRS training",
        "isInquiry": true,
        "isStaffResponse": false
    },
    {
        "from": "Christopher Rodican",
        "email": "crodican@councilsepa.org",
        "date": "8/14/2025",
        "time": "9:04 AM",
        "county": "Staff",
        "subject": "RE: Recovery specialists",
        "body": "Hi Kim, So we can best assist you, can you tell me what counties you live in and work in? We hold several Recovery Specialist trainings in Southeast Pennsylvania a year, at no cost to the students, open to people who either live or work in the county that the training is held in. The Certified Recovery Specialist certification is such an awesome way to use one's own lived experiences to help individuals on their recovery journey...",
        "summary": "Christopher Rodican responds with county and training information request",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "from": "quarantine@messaging.microsoft.com",
        "email": "quarantine@messaging.microsoft.com",
        "date": "8/15/2025",
        "time": "1:52 PM",
        "county": "Unknown",
        "subject": "Microsoft 365 security: You have messages in quarantine",
        "body": "Review These Messages 1 messages are being held for you to review as of 8/15/2025 5:22:12 PM (UTC). Review them within 30 days of the received date by going to the Quarantine page in the Security Center. Prevented phish messages Sender: wendooc1972@gmail.com Subject: 2025 Fall Cohort Date: 8/15/2025 4:32:36 PM Review Message Release © 2025 Microsoft Corporation. All rights reserved...",
        "summary": "Microsoft quarantine system provides security notification",
        "isInquiry": false,
        "isStaffResponse": false
    },
    {
        "from": "Dana Rachko",
        "email": "RachkoD@co.delaware.pa.us",
        "date": "8/18/2025",
        "time": "9:08 AM",
        "county": "Delaware",
        "subject": "RE: (EXTERNAL) [External] Recovery Specialist Interest Survey, PCB Website for RS Trainings, and Recovery Hub Email",
        "body": "Good morning, I was hoping to get some of the workforce development resources we spoke about in the meeting as well, if I'm remembering correctly, list of employers in the collar counties that hire people in recovery or with criminal background, information on past GED programs just for my knowledge and how that operates, any work fairs or employment events coming up. No rush, thank you so much!",
        "summary": "Dana Rachko requests workforce development resources",
        "isInquiry": true,
        "isStaffResponse": false
    },
    {
        "from": "Christopher Rodican",
        "email": "crodican@councilsepa.org",
        "date": "8/19/2025",
        "time": "12:06 PM",
        "county": "Staff",
        "subject": "RE: Recovery specialists",
        "body": "Hello Kim, Thank you so much for reaching out, and congratulations on your recovery! It's wonderful to hear that you want to become a Certified Recovery Specialist (CRS). Using your personal, lived recovery experience to help others is a fantastic way to give back. The Certified Recovery Specialist credential is a great way for individuals with personal, lived experience in their own substance use disorder recovery to help others...",
        "summary": "Christopher Rodican provides comprehensive CRS training information",
        "isInquiry": false,
        "isStaffResponse": true
    }
];