const emailData = [
    {
        "name": "joshua shorts",
        "email": "joshuashorts232@yahoo.com",
        "date": "6/3/2025",
        "time": "2:49 PM",
        "county": "Unknown",
        "subject": "Next available class",
        "body": "Hi my name is Joshua shorts and I'm interested in the next class you have available to become a certified peer specialist please contact me via email or phone at 267 453 6181 thank you",
        "summary": "joshua shorts inquires about CRS training",
        "isInquiry": true,
        "isStaffResponse": false
    },
    {
        "name": "Amy Legath",
        "email": "amylegath@gmail.com",
        "date": "6/3/2025",
        "time": "9:33 PM",
        "county": "Unknown",
        "subject": "Recovery Specialist Training",
        "body": "Good Evening, I am interested in enrolling in the Certified Recovery Specialist course. I am just shy of 19 months sober (AA) and have been interested in close to a year to complete this training program. What is the next step? Warmest Regards, Amy Legath 610-858-2969",
        "summary": "Amy Legath inquires about CRS training",
        "isInquiry": true,
        "isStaffResponse": false
    },
    {
        "name": "Alison Dunn",
        "email": "adunn@councilsepa.org",
        "date": "6/10/2025",
        "time": "11:23 AM",
        "county": "Staff",
        "subject": "RE: CRS Training",
        "body": "Good morning Alyssa, Currently, we are taking applications to identify the class size. Could you follow back up with me around the beginning of July and I will have a better idea on if we can accommodate your make up days. Please let me know the exact Learner Manual pages you need to cover as each class can flow differently...",
        "summary": "Alison Dunn coordinates make-up class scheduling",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Christopher Rodican",
        "email": "crodican@councilsepa.org",
        "date": "6/10/2025",
        "time": "2:21 PM",
        "county": "Staff",
        "subject": "RE: Crs training Carolyn Suhrcke",
        "body": "Thank you for reaching out, congratulations on your recovery, and on your interest in Recovery Specialist certification. The CRS is for individuals with personal, lived recovery experience, and it's a wonderful way to your personal, lived recovery experience to assist other individuals in recovery...",
        "summary": "Christopher Rodican provides CRS training information",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Anita James",
        "email": "anitajames1306@icloud.com",
        "date": "6/12/2025",
        "time": "11:36 AM",
        "county": "Unknown",
        "subject": "",
        "body": "Hello my name is Anita. I am interested in taking the CRS course. I have 2 years and 7 months clean, I also have been working one treatment as a BHT for 18 months. You can contact me at 445-224-8978 or my email. Thank you so much for your time.",
        "summary": "Anita James inquires about CRS training",
        "isInquiry": true,
        "isStaffResponse": false
    },
    {
        "name": "Christopher Rodican",
        "email": "crodican@councilsepa.org",
        "date": "6/12/2025",
        "time": "2:46 PM",
        "county": "Staff",
        "subject": "RE:",
        "body": "Thanks for reaching out! To better assist you, could you please let us know the counties where you live and work? We offer several Recovery Specialist trainings in Southeast Pennsylvania each year at no cost to the participants...",
        "summary": "Christopher Rodican provides CRS training information",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Christopher Rodican",
        "email": "crodican@councilsepa.org",
        "date": "6/12/2025",
        "time": "2:51 PM",
        "county": "Staff",
        "subject": "RE: Recovery Specialist Training",
        "body": "Congratulations on your recovery and your decision to become a CRS! So I can best assist you, please let me know what county you live in and or work in. We offer several trainings per year across the region, and they are available to individuals who live or work in the county where the training is conducted...",
        "summary": "Christopher Rodican provides CRS training information",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Amy Legath",
        "email": "amylegath@gmail.com",
        "date": "6/12/2025",
        "time": "2:57 PM",
        "county": "Chester",
        "subject": "Re: Recovery Specialist Training",
        "body": "Thank you for reaching out! I am in Chester County but would be willing to drive to other areas within reason for training. I am trying to do one that is low cost ( or free) and hopefully on saturdays.. I work full time and also take care of my son who is autistic...",
        "summary": "Amy Legath requests weekend training options",
        "isInquiry": true,
        "isStaffResponse": false
    },
    {
        "name": "Christopher Rodican",
        "email": "crodican@councilsepa.org",
        "date": "6/12/2025",
        "time": "2:58 PM",
        "county": "Staff",
        "subject": "RE: Next available class",
        "body": "A Certified Recovery Specialist is an individual who has lived experience with substance use disorder recovery and is certified to provide peer support to others on their recovery journey. A CPS (Certified Peer Specialist), on the other hand, is an individual who has lived experience with mental health challenges...",
        "summary": "Christopher Rodican provides CRS training information",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Christopher Rodican",
        "email": "crodican@councilsepa.org",
        "date": "6/12/2025",
        "time": "3:27 PM",
        "county": "Staff",
        "subject": "RE: Recovery Specialist Training",
        "body": "I see that you have filled out the Recovery Specialist Interest Survey, awesome! We will be facilitating a training in Pottstown this summer, but it is a weekday class, and I don't know how many slots are left...",
        "summary": "Christopher Rodican provides CRS training information",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Amy Legath",
        "email": "amylegath@gmail.com",
        "date": "6/12/2025",
        "time": "3:43 PM",
        "county": "Chester",
        "subject": "Re: Recovery Specialist Training",
        "body": "I did look at that , Pottstown is a bit far from me in Coatesville. I did see some in Reading and tried to find something in Lancaster too. I couldn't apply for the ones on the website without a password?",
        "summary": "Amy Legath inquires about training schedule",
        "isInquiry": true,
        "isStaffResponse": false
    },
    {
        "name": "Alyssa Brennan",
        "email": "abrennan1991@icloud.com",
        "date": "6/12/2025",
        "time": "6:17 PM",
        "county": "Bucks",
        "subject": "CRS",
        "body": "Hi my name is Alyssa and I'm interested in getting my CRS certification. How do I go about getting more information to help guide me to doing so?",
        "summary": "Alyssa Brennan inquires about CRS program details",
        "isInquiry": true,
        "isStaffResponse": false
    },
    {
        "name": "Christopher Rodican",
        "email": "crodican@councilsepa.org",
        "date": "6/13/2025",
        "time": "6:29 PM",
        "county": "Staff",
        "subject": "Re: Recovery Specialist Training",
        "body": "I know it's confusing but that green button is for after you've been accepted to the course. He will want to send an email to the instructor of the course you are interested in.",
        "summary": "Christopher Rodican provides CRS training information",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Alison Dunn",
        "email": "adunn@councilsepa.org",
        "date": "6/16/2025",
        "time": "9:44 AM",
        "county": "Staff",
        "subject": "RE: Trying to register for the crs course",
        "body": "Good morning Ange, Currently, we are working on phone interviews for the Montgomery County Training. On the flyer for the training, the first step is to complete a registration to be considered for the class...",
        "summary": "Alison Dunn provides CRS training information",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Alison Dunn",
        "email": "adunn@councilsepa.org",
        "date": "6/16/2025",
        "time": "9:51 AM",
        "county": "Staff",
        "subject": "RE: CFRS training July",
        "body": "Thank you so much for reaching out. I remember your name from Be a Part of the Conversation. Currently, we are working on phone interviews for the Montgomery County Training. This training will be happening, and it is gaining a lot of interest...",
        "summary": "Alison Dunn provides CRS training information in July",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Christopher Rodican",
        "email": "crodican@councilsepa.org",
        "date": "6/16/2025",
        "time": "10:14 AM",
        "county": "Staff",
        "subject": "Re: CRS",
        "body": "Thank you for reaching out and congratulations on your recovery! The CRS certification is for people with personal, lived experience in their own substance use disorder recovery. This allows them to offer a unique perspective and valuable insight when providing recovery support services...",
        "summary": "Christopher Rodican provides CRS training information",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Alison Dunn",
        "email": "adunn@councilsepa.org",
        "date": "6/16/2025",
        "time": "10:36 AM",
        "county": "Staff",
        "subject": "Recovery Specialist interest Survey",
        "body": "Here is our Recovery Specialist Training Interest Survey: This survey is for anyone interested in becoming a CRS or CFRS. When a training becomes available within our region, we send an email updating individuals registration is available.",
        "summary": "Alison Dunn provides CRS training information",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Alison Dunn",
        "email": "adunn@councilsepa.org",
        "date": "6/16/2025",
        "time": "2:34 PM",
        "county": "Staff",
        "subject": "RE: Recovery Specialist Cert Program",
        "body": "Thank you for reaching out. Currently, we are working on phone interviews for the Montgomery County Training. On the flyer for the training, the first step is to complete a registration to be considered for the class...",
        "summary": "Alison Dunn provides CRS training information",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Joanna Roth",
        "email": "joannaroth84@gmail.com",
        "date": "6/16/2025",
        "time": "2:54 PM",
        "county": "Unknown",
        "subject": "Re: Recovery Specialist Cert Program",
        "body": "I found the link in the flyer and just submitted my application. Thank you so much for your very quick reply and helpful information!",
        "summary": "Joanna Roth responds with gratitude for training information",
        "isInquiry": true,
        "isStaffResponse": false
    },
    {
        "name": "Christopher Rodican",
        "email": "crodican@councilsepa.org",
        "date": "6/16/2025",
        "time": "3:01 PM",
        "county": "Staff",
        "subject": "RE: Next available class",
        "body": "It was good talking with you today on the phone, and since you are interested in becoming a Certified Recovery Specialist, here is the link to our short Recovery Specialist Interest Survey form, which is the first step you should take...",
        "summary": "Christopher Rodican provides CRS training information",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Alison Dunn",
        "email": "adunn@councilsepa.org",
        "date": "6/17/2025",
        "time": "2:19 PM",
        "county": "Staff",
        "subject": "RE: CRS program information: Jasmine Baez",
        "body": "Thank you for reaching out. Currently, we are working on phone interviews for the Montgomery County Training. On the flyer for the training, the first step is to complete a registration to be considered for the class...",
        "summary": "Alison Dunn provides CRS training information",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Joan Rajkowski",
        "email": "djraj1128@gmail.com",
        "date": "6/21/2025",
        "time": "9:26 PM",
        "county": "Unknown",
        "subject": "CRS Traing program",
        "body": "Hi, My name is Joanie Rajkowski. I have applied to the program in the past and I thought I got a seat but never heard back from anyone that I left messages to. I would like to apply again and hope to get in for the 2 Weeks or the Saturday program preferably...",
        "summary": "Joan Rajkowski requests weekend training options",
        "isInquiry": true,
        "isStaffResponse": false
    },
    {
        "name": "Alison Dunn",
        "email": "adunn@councilsepa.org",
        "date": "6/23/2025",
        "time": "4:25 PM",
        "county": "Staff",
        "subject": "RE: Recovery Specialist Training",
        "body": "Thank you for reaching out. I just left you a voicemail, but I am glad I can follow up with an email also. Currently, we are working on phone interviews for the Montgomery County Training, and it appears this class may be full...",
        "summary": "Alison Dunn provides CRS training information",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Alison Dunn",
        "email": "adunn@councilsepa.org",
        "date": "6/23/2025",
        "time": "4:30 PM",
        "county": "Staff",
        "subject": "RE: Recovery Specialist Training",
        "body": "Thank you for reaching out. I did leave a voicemail for Kelly today, but I am glad I can follow up with an email also. Currently, we are working on phone interviews for the Montgomery County Training, and it appears this class may be full...",
        "summary": "Alison Dunn provides CRS training information",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Alison Dunn",
        "email": "adunn@councilsepa.org",
        "date": "6/23/2025",
        "time": "4:32 PM",
        "county": "Staff",
        "subject": "Recovery Specialist Interest Survey",
        "body": "Currently, we are working on phone interviews for the Montgomery County Training, and it appears this class may be full. I can follow back up with you once confirmed. On the flyer for the training, the first step is to complete a registration to be considered for the class...",
        "summary": "Alison Dunn provides CRS training information",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Alison Dunn",
        "email": "adunn@councilsepa.org",
        "date": "6/23/2025",
        "time": "4:34 PM",
        "county": "Staff",
        "subject": "FW: [CORRECTION] Recovery Specialist Training! Philadelphia - Spring 2025!",
        "body": "See below email for Philadelphia trainings.",
        "summary": "Alison Dunn provides CRS training information",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Alison Dunn",
        "email": "adunn@councilsepa.org",
        "date": "6/25/2025",
        "time": "12:11 PM",
        "county": "Staff",
        "subject": "RE: CRS CLASSES",
        "body": "Thank you for reaching out. Currently, we are finalizing the phone interviews for the Montgomery County Training, and it appears this class may be full. I can follow back up with you once confirmed...",
        "summary": "Alison Dunn provides CRS training information",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Andrea Rose",
        "email": "arose@recoverycoachingservices.com",
        "date": "6/26/2025",
        "time": "11:55 AM",
        "county": "Berks",
        "subject": "Re: [External] Recovery Specialist Training",
        "body": "Hello Alison, We did receive the flyer but we didn't want to register until we knew the answers to her questions. However, this class does appear full and she is not able to attend anyway. Is there another class being offered in the near future?",
        "summary": "Andrea Rose inquires about training schedule",
        "isInquiry": true,
        "isStaffResponse": false
    }
];