const emailData = [
    {
        "name": "Christopher Rodican",
        "email": "Unknown",
        "date": "5/5/2025",
        "time": "10:38 AM",
        "county": "Staff",
        "subject": "RE: Assistance",
        "body": "Kristy,\n\nThank you for reaching out and congratulations on your recovery journey. For individuals with lived experience in overcoming substance use disorder, becoming a Certified Recovery Specialist presents a remarkable opportunity to make a profound difference. This certification enables you to uniquely contribute to the recovery community by offering empathy, motivation, and support grounded in your personal journey. The CRS is not a sponsor, case manager, or a therapist, but we provide a distinct and necessary perspective as a role model, mentor, advocate, and motivator. As a CRS you would be illuminating the recovery process through the lens of your own success. If this sounds like what you are looking for, then so we can best assist you, can you tell me what counties you live in and work in?\n\nWe hold several Recovery Specialist trainings in Southeast Pennsylvania a year, at no cost to the students, open to people who either live or work in the county that the training is held in. In order to get on our list to be contacted when we schedule a training in your county, please use the following link to complete our short Recovery Specialist Interest Survey. You'll be added to our list which is used to fill classes, so that when a training is available for you, we will contact you with the next steps:\n\nAdditionally, the Pennsylvania Certification Board keeps an updated list of all currently scheduled Recovery Specialist trainings across the state which you can periodically check at the following link, in case you see a suitable training offered by another organization.\n\nWe are here to assist you if you have any additional questions or need assistance, so don't hesitate to reach out at .\n\nBest of luck, Kristy!",
        "summary": "Christopher Rodican responds to program inquiry",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Kristy Jameson",
        "email": "kccj33@gmail.com",
        "date": "4/26/2025",
        "time": "2:30 PM",
        "county": "Delaware",
        "subject": "Assistance",
        "body": "Hello my name is Kristy and I am interested in training to become a recovery support specialist and offer assistance to individuals with all of my experience, education and skills I have gained over the past years. I graduated with a bachelor degree in social work and I have been on my own recovery journey since November 12 2022. I am around of my accomplishments thus far however, I want to make a career out of all my experiences. I am lost on how to get started and I'm reaching out for some direction. Thank you for your time.\n\nKristy Jameson\n\n6109062895",
        "summary": "Kristy Jameson inquires about CRS training",
        "isInquiry": true,
        "isStaffResponse": false
    },
    {
        "name": "Jim Bollinger",
        "email": "Unknown",
        "date": "5/6/2025",
        "time": "9:53 AM",
        "county": "Philadelphia",
        "subject": "Learn to Share the Value of Peer Support with Providers & Communities – May 7 (ZOOM)",
        "body": "Hello,\nWe're excited to invite you to an upcoming Information Session on Peer-Based Professional Services, presented by PaPSC.\n📅 Date: Wednesday, May 7, 2025\n⏰ Time: 10:00 AM – 11:30 AM\n🔗Zoom Registration:\nThis presentation provides an in-depth overview of peer-based professionals and their unique role in behavioral health and recovery settings. Designed specifically for providers and service teams, the session explores the distinction between natural peer support and certified peer roles, outlines the credentialing process for Certified Peer Specialists (CPS) and Certified Recovery Specialists (CRS), and highlights the benefits of peer services within clinical and community environments. Participants will gain a better understanding of how peer professionals support recovery, collaborate with other providers, and contribute to person-centered care.\nImportant Note:\nPlease be aware that this is not a CEU training. We are unable to offer Continuing Education (CE) hours for this session, and attendees should not expect to receive them. While this may make it a less formal option, we believe the content is still highly beneficial and relevant for anyone interested in learning more about peer services.\nWe appreciate your interest in our presentation and look forward to sharing this important conversation with you.\nIf you have any questions, feel free to reach out.\nWarm regards,",
        "summary": "Jim Bollinger provides CRS training information in May",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Jim Bollinger",
        "email": "Unknown",
        "date": "5/6/2025",
        "time": "4:45 PM",
        "county": "Philadelphia",
        "subject": "Technical Tuesdays - TONIGHT - Learning Logistics - Register now!!",
        "body": "Hello,\n\nTechnical Tuesdays is tonight on Zoom. Tonight's topic:\n\nLearning Logistics\n\n1st Tuesday of every month\n\nPost Recovery Specialist Training Support: Have you completed the Recovery Specialist\n\nTraining and are preparing for your exam? This week is for you!\n\nTopics include: exam readiness, test taking skills, support for outstanding assignments,\n\nand answers to questions you have about obtaining your credential.\n\nRegister at the link below:\n\nHope to see you there!",
        "summary": "Jim Bollinger provides CRS training information",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "James Vaughn",
        "email": "jvaughn267@gmail.com",
        "date": "5/7/2025",
        "time": "3:20 PM",
        "county": "Unknown",
        "subject": "",
        "body": "I would like more information on the class that you offer.. I've been in recovery for 3 years now and i wanna do more with my knowledge and leadership skills and help people who suffer with addiction get the help they need... I wanna become a certified recovery specialist..",
        "summary": "James Vaughn inquires about CRS training",
        "isInquiry": true,
        "isStaffResponse": false
    },
    {
        "name": "Jim Bollinger",
        "email": "Unknown",
        "date": "5/8/2025",
        "time": "9:11 AM",
        "county": "Philadelphia",
        "subject": "\"Our Stories Have Power\" Training Opportunity",
        "body": "Greetings!\n\nThe Recovery Hub is excited to offer three upcoming opportunities to attend Faces and Voices of Recovery's \"Our Stories Have Power\" training. This impactful two-day workshop is open to people in recovery, advocates, and family members. It is designed to empower participants to share their personal stories as a tool for advocacy, education, and connection. Continuing education hours will be available.\n\nTraining Dates:\n\n* Option 1 (Virtual): May 20 & 22, 2025\n* Link to register: Meeting Registration - Zoom\n\n* Option 2 (Virtual): May 21 & 23, 2025\n\n* Option 3 (In-Person): June 23 & 24, 2025\n Location: TBD\n\nTo celebrate, we're hosting a special in-person gathering for all training participants on June 27, 2025.\n\nPlease see the attached flyer for details, and feel free to share this invitation widely within your networks. We'd love to have you join us in lifting up the power of recovery stories.",
        "summary": "Jim Bollinger provides CRS training information in May",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Jim Bollinger",
        "email": "Unknown",
        "date": "5/8/2025",
        "time": "9:15 AM",
        "county": "Philadelphia",
        "subject": "Fw: Riverview Wellness Village Referral Change",
        "body": "Please see attached email.",
        "summary": "Jim Bollinger provides requested documents and information",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Sean Brinda",
        "email": "Unknown",
        "date": "5/7/2025",
        "time": "1:21 PM",
        "county": "Unknown",
        "subject": "FW: Riverview Wellness Village Referral Change",
        "body": "Greetings,\n\nA few days ago, Riverview Wellness Village expanded their referral criteria beyond individuals transitioning from 30+ days of inpatient treatment to include individuals who are receiving outpatient services for 30+ days. Please share with your networks and staff for any referrals.\n\nSee attached for an updated Recovery House Initiative referral form and the email below with more details.\n\nBest Regards,\n\nSean E. Brinda, MSW\nManager, Peer Culture & Community Inclusion\nDepartment of Behavioral Health and Intellectual disAbility Services\nDivision of Planning Innovation\nPronouns: He/Him/His\nP 215.685.4748",
        "summary": "Sean Brinda provides program update information",
        "isInquiry": true,
        "isStaffResponse": false
    },
    {
        "name": "Christopher Rodican",
        "email": "Unknown",
        "date": "5/8/2025",
        "time": "12:04 PM",
        "county": "Staff",
        "subject": "Re: CRS",
        "body": "Hi James,\n\nCongratulations on your recovery, I think it is awesome that you want to do more with your knowledge and leadership skills to help people in their own recovery journeys, and I would be happy to give you more information about our Recovery Specialist trainings.\n\nThe CRS (Certified Recovery Specialist) is a professional who utilizes their training and the personal lived recovery experience that they bring to the table to offer empathy, motivation, and support to individuals in recovery. They may find themselves working with a caseload of individuals in the office or out in the community, or working in a hospital, connecting with individuals in crisis and helping them find the treatment they need, and there are several other roles and jobs that a CRS might find themselves working in.\n\nTo become a Certified Recovery Specialist, someone must be a person with personal lived recovery experience (and have at least 18 months in a continuous manner), and must have a high school diploma or a GED. The training is 78 hours in total, 75 hours of class time and three hours' worth of homework. Our trainings are generally two weeks, Monday through Friday, or ten Saturdays.\n\nSo I can best assist you in locating a suitable training, can you tell me what counties you live in and work in?",
        "summary": "Christopher Rodican responds to program inquiry",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Fred Shue",
        "email": "Unknown",
        "date": "5/8/2025",
        "time": "4:32 PM",
        "county": "Staff",
        "subject": "RE: CRS",
        "body": "To be clear Chris, it is 66 hours of class time, and 12 hours of homework. Thanks. -Fred",
        "summary": "Fred Shue provides training details correction",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Christopher Rodican",
        "email": "Unknown",
        "date": "5/8/2025",
        "time": "5:32 PM",
        "county": "Staff",
        "subject": "RE: CRS",
        "body": "Much obliged, I'm sending a follow up to James now. 😊",
        "summary": "Christopher Rodican responds with contact information",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Christopher Rodican",
        "email": "Unknown",
        "date": "5/8/2025",
        "time": "5:33 PM",
        "county": "Staff",
        "subject": "RE: CRS",
        "body": "James,\n\nThat's actually 66 hours of class time and 12 hours of homework. Apologies",
        "summary": "Christopher Rodican provides training details correction",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Wyanda Holman",
        "email": "wyanda123@gmail.com",
        "date": "5/9/2025",
        "time": "7:26 AM",
        "county": "Unknown",
        "subject": "CRS Training",
        "body": "Good morning,\n\nI am looking to start CRS training and enroll into your next course. I currently have a CPS certification and I have been working as an Outreach specialist for Veteran's Multi-Service Center.\nCan you send me the next class schedule?\n\nThank you\nWyanda Holman",
        "summary": "Wyanda Holman inquires about training schedule",
        "isInquiry": true,
        "isStaffResponse": false
    },
    {
        "name": "Chanel Suber",
        "email": "chanels20231@gmail.com",
        "date": "5/9/2025",
        "time": "3:31 PM",
        "county": "Unknown",
        "subject": "Classes for CRS",
        "body": "Good Afternoon,\nMy name is Chanel Suber I'm inquiring about classes to become a CRS.\nAs someone in recovery I've had several various individuals help me along the way,I was able to open up to them and not feel judged because they understand everything that I'm going through. I have been clean since November 5th,2023 and I wouldn't have made it without help and support. I want to give back to those who are in the same position I used to be in. I would really like the opportunity to be able to enroll in trainings for both CRS/CPS.\nMy contact information is 445-238-8868\nAnd this is my personal email\n\nThank you for your time\nHope to hear from you soon",
        "summary": "Chanel Suber inquires about CRS training",
        "isInquiry": true,
        "isStaffResponse": false
    },
    {
        "name": "Christopher Rodican",
        "email": "Unknown",
        "date": "5/14/2025",
        "time": "9:25 AM",
        "county": "Staff",
        "subject": "RE: CRS Training",
        "body": "Wyanda,\n\nFirst let me say congratulations on your recovery, obtaining your CPS, and your outreach work! We facilitate several Recovery Specialist trainings in the city every year, and they are available to individuals who live or work in the city. They are provided at no cost to the student. As I see that you have filled out our interest survey form on 4/21, someone will be emailing you to give you the next steps when a training becomes available for you. I don't, however, have a schedule to be able to provide you with specifics beyond that.\n\nIf you would like, you can periodically check the Pennsylvania Certification Board website's statewide list of upcoming Recovery Specialist trainings that people can apply for. While there aren't any Philadelphia trainings currently listed, it is updated all the time so you could check back weekly or even daily.\n\nIn addition to those facilitated by PRO-ACT, which you have already filled out the Interest Survey for, you can apply to trainings from other organizations. As it says at the top of the chart listing the classes, you'll want to email the facilitator on that page directly, rather than clicking the \"enroll\" button.\n\nCongratulations again on your recovery and the amazing things you are doing, and good luck!",
        "summary": "Christopher Rodican responds to program inquiry",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Christopher Rodican",
        "email": "Unknown",
        "date": "5/14/2025",
        "time": "9:45 AM",
        "county": "Staff",
        "subject": "RE: Classes for CRS",
        "body": "Hi Chanel,\n\nThank you for reaching out, and congratulations on your recovery! While I am not able to assist you with information about CPS certification, I can help provide info about getting CRS certification.\n\nThe Certified Recovery Specialist certification offers a fantastic opportunity for individuals with at least 18 months in a continuous manner of personal, lived recovery experience to use that experience to assist individuals with their own recovery! In addition to the required minimum of 18 months, a high school diploma or GED is also required.\n\nSo we can best assist you, can you tell me what counties you live in and work in? Additionally, please use the following link to complete our short Recovery Specialist Interest Survey. As soon as a training becomes available for you, we'll contact you with the next steps:\n\nIf you would like, you can periodically check the Pennsylvania Certification Board website's statewide list of upcoming Recovery Specialist trainings that people can apply for. As of today, there are no Philadelphia trainings listed, but it is updated all the time so you should check back weekly or even daily.\n\nIn addition to those facilitated by PRO-ACT, which you have already filled out the Interest Survey for, you can apply to the trainings on that page that are from other organizations. As it says at the top of the chart listing the classes, you'll want to email the facilitator on that page directly, rather than clicking the \"enroll\" button.\n\nCongratulations again on your recovery, Chanel, and good luck!",
        "summary": "Christopher Rodican responds to program inquiry",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Ann Archer",
        "email": "archer.ann0819@icloud.com",
        "date": "5/18/2025",
        "time": "12:28 PM",
        "county": "Unknown",
        "subject": "How to get started",
        "body": "Hi, this is Ann Archer. I'm just reaching out to try and find out more information on the CRS certification and training if somebody could either give me an email back or give me a call at 304-702-9139 so I can get enrolled and get started as soon as possible thank you\n\nAnn Archer\nSent from my iPhone",
        "summary": "Ann Archer inquires about CRS program details",
        "isInquiry": true,
        "isStaffResponse": false
    },
    {
        "name": "Mathew Braciszewski",
        "email": "mathewbraciszewski@gmail.com",
        "date": "5/18/2025",
        "time": "9:03 PM",
        "county": "Philadelphia",
        "subject": "Requesting Info for CRS classes",
        "body": "Good evening.\n\nI was referred to this contact about looking into certified recovery specialist classes and training and was told this was a great resource to look into. I myself am a personal 29 months into alcohol recovery and find myself between a rock and a purposeless place. These classes are something I'd love to talk more about and get some further details on to potentially look into as a future career path.\n\nIf there is availability tomorrow to speak, I'd love to pick your brain and talk some more. My direct contact is 267-290-2585.\n\nLooking forward to speaking more.\n\nBest,\nMat Braciszewski\nSent from my iPhone",
        "summary": "Mathew Braciszewski inquires about CRS training",
        "isInquiry": true,
        "isStaffResponse": false
    },
    {
        "name": "Christopher Rodican",
        "email": "Unknown",
        "date": "5/19/2025",
        "time": "8:38 AM",
        "county": "Staff",
        "subject": "RE: How to get started",
        "body": "Hi Ann,\nThanks for reaching out! Congratulations on your interest, and to give you some more info, the Certified Recovery Specialist (CRS) is someone with personal experience in their own substance use disorder recovery. The CRS is not a therapist, a counselor, a sponsor, or a case manager. Instead, they are a professional who use their personal, lived recovery experience offer unique insights from their own journey, giving a kind of support that no one else can. The CRS's role is to be a role model, mentor, advocate, and motivator.\n\nSo I can best assist you, can you please tell me what counties you live in and work in? We offer several trainings a year across the southeast Pennsylvania region, and these trainings are available to individuals who live or work in the county where that training is conducted. These trainings are made available at no cost to the student. Please fill out this short survey form, and when a training becomes available for you, someone will contact you with the next steps to take:\n\nIn addition to the trainings facilitated by PRO-ACT, you may want to see trainings offered by other organizations. The Pennsylvania Certification Board website contains a list of all the upcoming Recovery Specialist trainings in the state. The list contains the location, cost, and instructor's email for each training course. The list is updated all the time so you can check back weekly or even daily. If you find a training on that list you would like to apply to, email the instructor directly instead of using the green enroll button.\n\nDon't forget to fill out the survey form and then email me back to let me know your counties.\n\nBest of luck, Ann!",
        "summary": "Christopher Rodican responds to program inquiry",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Christopher Rodican",
        "email": "Unknown",
        "date": "5/19/2025",
        "time": "11:29 AM",
        "county": "Staff",
        "subject": "RE: Requesting Info for CRS classes",
        "body": "Hi Mat,\n\nThank you so much for reaching out. It sounds like you're on an incredible journey with your recovery, and it's inspiring to hear about your interest in becoming a Certified Recovery Specialist. I can absolutely understand that feeling of being at a crossroads, and it's wonderful that you're exploring paths that could bring purpose and meaning.\n\nI'd be very happy to speak with you more about the CRS classes and training. I will plan to call you around 12:30 PM today. If you happen to miss my call, please feel free to call me back at your convenience.\n\nLooking forward to connecting with you.",
        "summary": "Christopher Rodican responds with contact information",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Christopher Rodican",
        "email": "Unknown",
        "date": "5/19/2025",
        "time": "2:30 PM",
        "county": "Staff",
        "subject": "RE: Requesting Info for CRS classes",
        "body": "Mat,\nIt was great having a chance to talk with you today. Here is some more information about Certified Recovery Specialist\n\nAs discussed, we offer several trainings in Philadelphia each year, for people who live and/or work in the city, and the trainings are offered at no cost to the student. Please fill out this short survey form, so we can contact you with next steps when we have a training for you\n\nAdditionally, to look into the CRS trainings offered by other organizations, the Pennsylvania Certification Board's website contains a list of all the upcoming Recovery Specialist trainings in the state. The list contains the location, cost, and instructor's email for each training course. The list is updated all the time so you can check back weekly or even daily. If you find a training on that list you would like to apply to, email the instructor directly instead of using the green enroll button.\n\nGood luck!",
        "summary": "Christopher Rodican responds to program inquiry",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Amber Moon",
        "email": "amberreneemoon41@gmail.com",
        "date": "5/19/2025",
        "time": "3:17 PM",
        "county": "Philadelphia",
        "subject": "Possibility of joining class for missed class on multiple pathways",
        "body": "Good afternoon,\n\nMy name is Amber Moon. I am currently enrolled in a CRS class and missed an hour and a half on day 2 for multiple pathways. Is it possible I could join in for that class? My graduation date is June 4th. My phone number is 267-808-2726.\n\nThank you for your time,\n\nAmber Moon",
        "summary": "Amber Moon requests make-up class for missed session",
        "isInquiry": true,
        "isStaffResponse": false
    },
    {
        "name": "Gina Tomaselli",
        "email": "gina@sparkwellness.com",
        "date": "5/21/2025",
        "time": "6:22 PM",
        "county": "Bucks",
        "subject": "information on classes",
        "body": "HI\n\nI have someone that is interested in becoming a CRS. Can you please send me info on your training and when the class opens up again.\n\nThank you\n\nGina Tomaselli ASW,CAAC\nFacility Director\nSpark Wellness LLC\n301 Oxford Valley Rd\nSuite 1302A\nYardley Pa 19067\noffice:267-399-3990\ncell:267-994-4248",
        "summary": "Gina Tomaselli inquires about CRS training",
        "isInquiry": true,
        "isStaffResponse": false
    },
    {
        "name": "Kristan Waters",
        "email": "kristanakai1@gmail.com",
        "date": "5/21/2025",
        "time": "7:09 PM",
        "county": "Delaware",
        "subject": "Certified Recovery Training",
        "body": "Hi,\nMy name is Kristan Waters and I'm very much interested in the Certified Recovery Support Specialist Program. I currently live in Delaware County and I'm 40 years old with lived experience of alcohol and mental health. I can be reached at kristanakai1@gmail.com or 610-220-1858\n\nThank you Kristan Waters\nSent from my iPhone",
        "summary": "Kristan Waters inquires about CRS training",
        "isInquiry": true,
        "isStaffResponse": false
    },
    {
        "name": "Christopher Rodican",
        "email": "Unknown",
        "date": "5/22/2025",
        "time": "3:46 PM",
        "county": "Staff",
        "subject": "RE: Certified Recovery Training",
        "body": "Kristan,\n\nThanks so much for reaching out and congratulations on your recovery! Becoming Certified Recovery Specialist is a fantastic opportunity to use your personal, lived recovery experience to assist individuals with their own recovery! We conduct several Recovery Specialist trainings across the region each year, available to individuals who live or work in the county where the training is being conducted. These trainings are offered at no cost to the students. I see that you've already filled out our Recovery Specialist Interest Survey form yesterday, which is great! We use the list generated from that form to contact people to fill the trainings, so as soon as a training becomes available for you, we will contact you with the next steps for enrolling.\n\nAdditionally, you can also check the Pennsylvania Certification Board website's statewide list of all upcoming Recovery Specialist trainings to see if another training is suitable for you in terms of cost and location. As the list is continually updated, you may want to check back regularly. If you see a course you want to apply for, it is best to contact the facilitator using the email provided in the list. It can be confusing, but the green \"Enroll\" button is actually for enrolling for the class portal.\n\nBest of luck!",
        "summary": "Christopher Rodican responds to program inquiry",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Kristan Waters",
        "email": "kristanakai1@gmail.com",
        "date": "5/22/2025",
        "time": "3:57 PM",
        "county": "Delaware",
        "subject": "Re: Certified Recovery Training",
        "body": "Thank you so much for the info! And please do keep me updated on the free courses. Thanks Again\n\nKristan Waters",
        "summary": "Kristan Waters inquires about CRS training",
        "isInquiry": true,
        "isStaffResponse": false
    },
    {
        "name": "Jack Lark",
        "email": "jacklark3422@icloud.com",
        "date": "4/9/2025",
        "time": "5:42 PM",
        "county": "Unknown",
        "subject": "CRS training inquiry",
        "body": "Hello my name is Jack Lark. I'm currently in recovery myself and am working in the field. A coworker of mine, recommend I reach out regarding CRS certification. I'm curious how I would be able to being the process of becoming a CRS.\n\nThank you kindly\nWith Unity,\nJL",
        "summary": "Jack Lark inquires about CRS training",
        "isInquiry": true,
        "isStaffResponse": false
    },
    {
        "name": "Christopher Rodican",
        "email": "Unknown",
        "date": "5/27/2025",
        "time": "10:03 AM",
        "county": "Staff",
        "subject": "RE: CRS training inquiry",
        "body": "Jack,\n\nCongratulations on your recovery and thank you for reaching out! I apologize for the delay in getting back to you, your email was lost in the shuffle for some reason. So I can best assist you, could you please let me know what counties you live and/or work in? We hold several Recovery Specialist trainings in Southeast Pennsylvania a year, at no cost to the students, open to people who either live or work in the county that the training is held in.\n\nPlease use the following link to complete our short Recovery Specialist Interest Survey form. As soon as a training becomes available for you, we'll contact you with the next steps:\n\nAdditionally, the Pennsylvania Certification Board keeps a list of all the Recovery Specialist trainings across the state which are available to apply for. It is continually updated, so you can check it weekly or even daily:\n\nGood luck!",
        "summary": "Christopher Rodican responds to program inquiry",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Lisa Baxter",
        "email": "baxtermlisa68@yahoo.com",
        "date": "5/26/2025",
        "time": "9:10 AM",
        "county": "Adams",
        "subject": "Lisa Baxter",
        "body": "Hello,\n\nMy name is Lisa Baxter and I graduated from Hood College located in Frederick, Maryland with a social work degree.\nI am interested in the field of addiction and I am interested in signing up for classes.\nI currently live in Gettysburg, Pennsylvania and I am interested in online classes and I came across your website and I saw that classes are starting soon!\nIf you could email or call me back regarding classes and certification guideline in PA I would appreciate it!\n\nThank You, Lisa Baxter",
        "summary": "Lisa Baxter inquires about CRS training",
        "isInquiry": true,
        "isStaffResponse": false
    },
    {
        "name": "Alison Dunn",
        "email": "Unknown",
        "date": "5/28/2025",
        "time": "10:32 AM",
        "county": "Adams",
        "subject": "RE: Lisa Baxter",
        "body": "Hi Lisa,\n\nIt is nice to meet you. We facilitate Recovery Specialist Trainings through the Pennsylvania Certification Board for individuals to receive the CRS, CFRS, or CRSS Credential. The counties we train in are Bucks, Berks, Chester, Delaware, Lancaster, Montgomery, Philadelphia, and Schuylkill Counties. Recovery Specialist Trainings are in person and have homework outside of class.\n\nWe use our Recovery Specialist Training Interest Survey:. This survey is for anyone interested in becoming a CRS or CFRS. When a training becomes available in their area, we send an email with details and provide support for enrollment. Additionally, we've created a dedicated email for questions and inquiries about Recovery Specialist Classes:.\n\nHere are some resources for you.\n\nYou have a Regional Recovery Hub for Adams County. They may be able to assist you with locating a Recovery Specialist Class in your area.\n\nPennsylvania Certification Board\n* To learn more about the certifications themselves, you can visit the PA Certification Board website\n* Upcoming trainings throughout the state.\n\nI hope this information is helpful and what you are looking for. If you have any other questions, feel free to email or to give me a call.",
        "summary": "Alison Dunn responds to program inquiry",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Carolyn Suhrcke",
        "email": "carolynmahn81718@gmail.com",
        "date": "5/29/2025",
        "time": "3:50 PM",
        "county": "Unknown",
        "subject": "Crs training Carolyn Suhrcke",
        "body": "Hello I was wondering how to apply or get started or find a course to become a crs if you could help with any info that would be great ! Thank you so much !! Carolyn rose suhrcke 570-202-2889\nSent from my iPhone",
        "summary": "Carolyn Suhrcke inquires about CRS program details",
        "isInquiry": true,
        "isStaffResponse": false
    },
    {
        "name": "Alison Dunn",
        "email": "Unknown",
        "date": "5/29/2025",
        "time": "4:54 PM",
        "county": "Montgomery",
        "subject": "Makeup Class Information & Upcoming Opportunities",
        "body": "Hi Theresa,\n\nHere's a quick summary of the classes you missed:\n* Day 3 – Learner Manual pages 32–45\n* Day 8 – Learner Manual pages 108–125\n* Day 10 – Learner Manual pages 140 to the end\n\nI'm glad you'll be able to attend Gina's class this Saturday, May 31, 2025. I hope you have a great experience! We also have an upcoming 10-day class starting next week in Schuylkill County, beginning Monday, June 2, 2025. Tentatively, Day 3 will fall on Wednesday, June 4, and Day 8 on Wednesday, June 11. Please note that the class flow may vary, so you'll need to check in with Fred to confirm which pages are being covered on each day. Please check with your employer regarding your availability and let us know if you're interested in attending. If this class doesn't work for you, we're planning another class in July in Montgomery County and can revisit your participation in that session depending on space.\n\nLocation:\nAlvernia University\n500 Progress Ave\nPottsville, PA 17901\n\nAdditionally, here's a link to the PCB website listing other upcoming classes:\n\nIf you see another class that fits your schedule, you can email the listed instructor directly to ask about availability. Be sure to mention which Learner Manual pages you need to make up.\n\nLet me know if you have any questions!",
        "summary": "Alison Dunn coordinates make-up class scheduling",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Teresa Fetzer",
        "email": "tfetzer35@gmail.com",
        "date": "5/29/2025",
        "time": "5:16 PM",
        "county": "Montgomery",
        "subject": "Re: Makeup Class Information & Upcoming Opportunities",
        "body": "Good evening, thank you Allison for your quick response and assistance.\nI will be there Saturday Gina, I look forward to attending.",
        "summary": "Teresa Fetzer inquires about training schedule",
        "isInquiry": true,
        "isStaffResponse": false
    }];