const emailData = [
    {
        "name": "Jim Bollinger",
        "email": "jbollinger@councilsepa.org",
        "date": "4/1/2025",
        "time": "3:01 PM",
        "county": "Staff",
        "subject": "Technical Tuesdays is Tonight - Register Now!!",
        "body": "Technical Tuesdays is tonight on Zoom. Tonight's topic: Learning Logistics 1st Tuesday of every month. Post Recovery Specialist Training Support: Have you completed the Recovery Specialist Training and are preparing for your exam? This week is for you! Topics include: exam readiness, test taking skills, support for outstanding assignments, and answers to questions you have about obtaining your credential...",
        "summary": "Jim Bollinger provides CRS training information",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Jim Bollinger",
        "email": "jbollinger@councilsepa.org",
        "date": "4/1/2025",
        "time": "3:17 PM",
        "county": "Staff",
        "subject": "DBHIDS Certified Peer Specialist Training",
        "body": "Please see attached flyer, post in your organization or share with your colleagues. Please direct any questions to the email address listed below. The next CPS application acceptance period will be April 1 through April 18 for the June 9-20, 2025 training. Applicants for this class must attend Storytelling training. Please go to www.healthymindsphilly.com to learn when the next opportunity for storytelling training...",
        "summary": "Jim Bollinger provides CPS training information in June",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Christopher Rodican",
        "email": "crodican@councilsepa.org",
        "date": "4/1/2025",
        "time": "3:50 PM",
        "county": "Staff",
        "subject": "Information regarging Recovery Specialist Training in Philadelphia",
        "body": "Keith, Thank you for calling, and congratulations on your decision to become a Certified Recovery Specialist! We hold several trainings in Philadelphia each year at no cost to the students, provided they live or work in Philadelphia. If you can fill out this short form, we can get you on our list to be contacted when we are filling the class...",
        "summary": "Christopher Rodican responds with contact information",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Christopher Rodican",
        "email": "crodican@councilsepa.org",
        "date": "4/1/2025",
        "time": "3:55 PM",
        "county": "Staff",
        "subject": "Info regarding Recovery Specialist Training in Philadelphia",
        "body": "Keith, Thank you for calling, and congratulations on your decision to become a Certified Recovery Specialist! We hold several trainings in Philadelphia each year at no cost to the students, provided they live or work in Philadelphia. If you can fill out this short form, we can get you on our list to be contacted when we are filling the class...",
        "summary": "Christopher Rodican responds with contact information",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Mariette Diaz",
        "email": "mariette.diaz1@gmail.com",
        "date": "4/1/2025",
        "time": "8:35 PM",
        "county": "Bucks",
        "subject": "Make up Class",
        "body": "Good evening, I need to make up an ethics class, specifically pages 56-63 in our books. I did reach out to a few people but haven t heard back. I currently am taking the CRS class in Philadelphia with Leilany Vargas on Tuesdays but live in Bucks county. You may reach me via email or phone at 2673701468. Thank you, Mariette Diaz",
        "summary": "Mariette Diaz requests make-up class information",
        "isInquiry": true,
        "isStaffResponse": false
    },
    {
        "name": "Christopher Rodican",
        "email": "crodican@councilsepa.org",
        "date": "4/2/2025",
        "time": "10:58 AM",
        "county": "Staff",
        "subject": "Make-Up Class for Mariette Diaz",
        "body": "Hi Ali, One of our Technical Tuesdays: Learning Logistics participants from yesterday evening, Mariette Diaz, is a student in Leilany Vargas s Recovery Specialist 332 training on Tuesdays. She missed the class with Ethics, pages 56 to 63. Provided you ll be doing it next week and not this week, and provided that it s not on Tuesday which is when she has Leilany s class, would she be allowed to attend that day at your Recovery Specialist 341 training at Government Service Center in West Chester?",
        "summary": "Christopher Rodican coordinates make-up class scheduling",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Alison Dunn",
        "email": "adunn@councilsepa.org",
        "date": "4/2/2025",
        "time": "11:11 AM",
        "county": "Staff",
        "subject": "RE: Make-Up Class for Mariette Diaz",
        "body": "Hey Chris, She can attend and I am adding Jon onto this. Ethics is a few days, and those page numbers would be this week. I am not sure where Jon will end today regarding page numbers, but this may be the second part of tomorrow s class and/or this Friday, 4/4/25. If I had to guess I d say it would be on Friday. Do you want to see what her availability is tomorrow and Friday and let her know we would have a better idea which day it is later today? Again, I believe Friday but I can check with Jon later today to see where he is at in the class.",
        "summary": "Alison Dunn coordinates make-up class scheduling",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Christopher Rodican",
        "email": "crodican@councilsepa.org",
        "date": "4/2/2025",
        "time": "11:14 AM",
        "county": "Staff",
        "subject": "RE: Make-Up Class for Mariette Diaz",
        "body": "Hey Ali, (hi Jon!) Ok I will let her know. Thanks!",
        "summary": "Christopher Rodican coordinates make-up class scheduling",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Christopher Rodican",
        "email": "crodican@councilsepa.org",
        "date": "4/2/2025",
        "time": "11:32 AM",
        "county": "Staff",
        "subject": "RE: Make up Class",
        "body": "Mariette, I spoke with the facilitators of the training in Chester, and you are more than welcome to make up the training there. They will be covering those pages in either the second part of tomorrow s class, and/or Friday. Most likely it will be Friday, but I can let you know for sure later this afternoon.",
        "summary": "Christopher Rodican coordinates make-up class scheduling",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "joeynich.",
        "email": "joeynich151@gmail.com",
        "date": "4/2/2025",
        "time": "12:06 PM",
        "county": "Chester",
        "subject": "Interest In CPS/CRS Training!",
        "body": "Dear CRS Training Team, My name is Joe Nicholson, and I m reaching out with strong interest in beginning the process to receive my Certification in Recovery and Peer Support. I am the Founder of The Pathfinder Initiative, an Advisor to the Chester County Reentry Coalition, and a Board Member of the PARC Health Subcommittee. Since coming home from a 14-year prison sentence, I ve committed my life to the work of Reentry, Recovery, and Reform...",
        "summary": "Joe Nicholson inquires about CRS training",
        "isInquiry": true,
        "isStaffResponse": false
    },
    {
        "name": "Alison Dunn",
        "email": "adunn@councilsepa.org",
        "date": "4/2/2025",
        "time": "1:08 PM",
        "county": "Staff",
        "subject": "RE: CRS refresher",
        "body": "Hi Trina, I m so glad you reached out and we are happy to help you! We have a virtual meeting Tuedays at 7pm called Technical Tuesdays. The first Tuesday of each month, is called Learning Logistics. They discuss the application process, has a test prep, can answer any questions you might have, and touches on incomplete homework assignments. It is dedicated to students who finished class but have not become credentialed yet. Unfortunately, it was last night, and the next one will be on 5/6/25...",
        "summary": "Alison Dunn provides CRS training information in May",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Christopher Rodican",
        "email": "crodican@councilsepa.org",
        "date": "4/2/2025",
        "time": "4:33 PM",
        "county": "Staff",
        "subject": "RE: Make up Class",
        "body": "Hi Mariette, I just spoke with the training facilitator; you can attend Friday to make up the class. Good luck!",
        "summary": "Christopher Rodican coordinates make-up class scheduling",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Peter Schiess",
        "email": "brooklyn32589@icloud.com",
        "date": "4/3/2025",
        "time": "3:55 AM",
        "county": "Unknown",
        "subject": "(Interest In Training)",
        "body": "Hello My Name Is Peter Schiess, A Recent Grad Of The CPS Training! I m Looking Further My Education & Experience. Please Can You Let Me Know About Any Upcoming Trainings I Can Attend In This Area.? Thank You Sent from my iPhone",
        "summary": "Peter Schiess inquires about training schedule",
        "isInquiry": true,
        "isStaffResponse": false
    },
    {
        "name": "Trina Adams",
        "email": "trinavadams9394@gmail.com",
        "date": "4/3/2025",
        "time": "8:46 AM",
        "county": "Unknown",
        "subject": "Re: CRS refresher",
        "body": "Hi Ali, Thank You for your prompt response. I'll work on all this and I'll reach out if I need more assistance. Have a great day! Trina",
        "summary": "Trina Adams asks about certification requirements",
        "isInquiry": true,
        "isStaffResponse": false
    },
    {
        "name": "Jim Bollinger",
        "email": "jbollinger@councilsepa.org",
        "date": "4/3/2025",
        "time": "8:48 AM",
        "county": "Staff",
        "subject": "Learn to Share the Value of Peer Support with Providers & Communities   May 7 (ZOOM)",
        "body": "Hello, We re excited to invite you to an upcoming Information Session on Peer-Based Professional Services, presented by PaPSC. Date: Wednesday, May 7, 2025 Time: 10:00 AM 11:30 AM This presentation provides an in-depth overview of peer-based professionals and their unique role in behavioral health and recovery settings. Designed specifically for providers and service teams, the session explores the distinction between natural peer support and certified peer roles...",
        "summary": "Jim Bollinger provides CRS training information in May",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Christopher Rodican",
        "email": "crodican@councilsepa.org",
        "date": "4/3/2025",
        "time": "9:18 AM",
        "county": "Staff",
        "subject": "RE: ",
        "body": "Keith, Thank you for calling, and congratulations on your decision to become a Certified Recovery Specialist! We hold several trainings in Philadelphia each year at no cost to the students, provided they live or work in Philadelphia. If you can fill out this short form, we can get you on our list to be contacted when we are filling the class...",
        "summary": "Christopher Rodican responds with contact information",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Christopher Rodican",
        "email": "crodican@councilsepa.org",
        "date": "4/3/2025",
        "time": "9:27 AM",
        "county": "Staff",
        "subject": "RE: CRS Training - Colleen Wurtz",
        "body": "Hello Colleen, Thank you so much for reaching out! The Certified Recovery Specialist certification is such an awesome way to use one s own lived experiences to help individuals on their recovery journey. It is for individuals with personal, lived experience in their own substance use disorder recovery. You can learn more about it on the Pennsylvania Certification Board s website...",
        "summary": "Christopher Rodican responds to program inquiry",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Christopher Rodican",
        "email": "crodican@councilsepa.org",
        "date": "4/3/2025",
        "time": "10:30 AM",
        "county": "Staff",
        "subject": "RE: Training Class",
        "body": "Hi Rosy, Thank you for reaching out and congrats on your decision to become a CRS! It is awesome the way being a Certified Recovery Specialist allows those in recovery to use their lived experiences to help individuals on their recovery journey. So that I may best help you, can you please let me know what counties you are currently living and/or working in?...",
        "summary": "Christopher Rodican responds to program inquiry",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Jim Bollinger",
        "email": "jbollinger@councilsepa.org",
        "date": "4/3/2025",
        "time": "12:26 PM",
        "county": "Staff",
        "subject": "Re: Learn to Share the Value of Peer Support with Providers & Communities   May 7 (ZOOM)",
        "body": "Here is the registration link:",
        "summary": "Jim Bollinger provides requested documents and information",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Alison Dunn",
        "email": "adunn@councilsepa.org",
        "date": "4/3/2025",
        "time": "8:43 PM",
        "county": "Staff",
        "subject": "Re: Make-Up Class for Mariette Diaz",
        "body": "Hey Fred, Sorry for the late email. Unfortunately, I got through the pages today that Mariette missed. I spoke to her last night letting her know it would probably be the Thursday/Friday with how the pages were going. I did speak to her today at lunch letting her know I started her pages today. She has been in touch with Gina and was told seats may be full. Could we please offer her your May class for make up if possible?...",
        "summary": "Alison Dunn coordinates make-up class scheduling",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Mathis, Latoya",
        "email": "lmathis@pa.gov",
        "date": "4/4/2025",
        "time": "9:53 AM",
        "county": "Erie",
        "subject": "CSR training",
        "body": "Hello, I have a customer interested in becoming a CSR and wanted to know information on the application and training process. Thank you Latoya Mathis, MS, BA | Vocational Rehabilitation Counselor Labor & Industry|Office of Vocational Rehabilitation Bureau of Blindness and Visual Services 4200 Lovell Place | Erie, PA 1650 Phone: 814.451.5413 | Cell: 814.323.5928| Fax: 814.871.4746...",
        "summary": "Latoya Mathis inquires about CRS program details",
        "isInquiry": true,
        "isStaffResponse": false
    },
    {
        "name": "Christopher Rodican",
        "email": "crodican@councilsepa.org",
        "date": "4/4/2025",
        "time": "3:57 PM",
        "county": "Staff",
        "subject": "RE: CSR training",
        "body": "Latoya, Hi and thank you for reaching out. A CRS (Certified Recovery Specialist) certification is a credential for individuals with personal, lived experience in their own substance use disorder recovery, enabling them to work in a career where they use that lived experience to support, motivate and guide others into and through their own recovery. To be eligible for a training, individuals must have a high school diploma or a GED, and at least eighteen months in a continuous manner of personal, lived, recovery experience...",
        "summary": "Christopher Rodican responds to program inquiry",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Jim Bollinger",
        "email": "jbollinger@councilsepa.org",
        "date": "4/7/2025",
        "time": "2:02 PM",
        "county": "Staff",
        "subject": "Philly CSP Meeting is Tomorrow",
        "body": "Hello, I hope this e-mail finds you well. I'm sharing an important resource the Community Support Program (CSP) monthly meeting flyer. These meetings are a key opportunity for Certified Peer Specialists (CPS) and Certified Recovery Specialists (CRS) to connect, collaborate, and advocate for our community. Philly Local Meetings: 2nd Tuesday of each month, 12:30 2:30 PM SE Regional Meetings: 1st Monday of each month, 3:00 5:00 PM...",
        "summary": "Jim Bollinger provides CRS training information",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Christopher Rodican",
        "email": "crodican@councilsepa.org",
        "date": "4/7/2025",
        "time": "3:00 PM",
        "county": "Staff",
        "subject": "RE: (Interest In Training)",
        "body": "Peter, Thank you for reaching out. Congratulations on obtaining your Certified Peer Specialist certification. What sort of training are you hoping to find? If you are interested in Recovery Specialist training, please let me know what county you are located in so I can best assist you. We offer several trainings a year in the southeast Pennsylvania region...",
        "summary": "Christopher Rodican responds to program inquiry",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Ashley Otoole",
        "email": "ashleyotoole3@gmail.com",
        "date": "4/8/2025",
        "time": "8:48 AM",
        "county": "Philadelphia",
        "subject": "Motoole812@gmail.com",
        "body": "",
        "summary": "Ashley Otoole inquires about CRS program details",
        "isInquiry": true,
        "isStaffResponse": false
    },
    {
        "name": "Ashley Otoole",
        "email": "ashleyotoole3@gmail.com",
        "date": "4/8/2025",
        "time": "8:53 AM",
        "county": "Philadelphia",
        "subject": "Sorry!",
        "body": "I apologize for the previous email! Good morning! My name is Ashley Toms ~OToole, and I m super interested in crs training! I wasn t sure how to apply or what I had to do in order to be on the list for the next available classes in Philadelphia?!? If you could let me know that would be greatly appreciated! Thank you",
        "summary": "Ashley Otoole inquires about CRS training",
        "isInquiry": true,
        "isStaffResponse": false
    },
    {
        "name": "Christopher Rodican",
        "email": "crodican@councilsepa.org",
        "date": "4/8/2025",
        "time": "11:37 AM",
        "county": "Staff",
        "subject": "RE: Interested in CRS Training ?",
        "body": "Hi Sarah, I remember you saying that you filled out the form to get on the list for upcoming trainings, but I did not see your name or email on there so I was reaching out to see if you may have not submitted the form when you were entering it. Additionally, can you tell me what county you live in and or work in? We hold several trainings per year across the region, available at no cost to people who live or work in the county where the training is being conducted, which is why I ask. Thank you!",
        "summary": "Christopher Rodican responds with contact information",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Sarah Love",
        "email": "sarahtglick@gmail.com",
        "date": "4/8/2025",
        "time": "1:02 PM",
        "county": "Bucks",
        "subject": "Re: Interested in CRS Training ?",
        "body": "Yes, I'm still interested in the course. I live in Lower Bucks County and work in this area as well. Please let me know what else is need from me!?",
        "summary": "Sarah Love inquires about CRS training",
        "isInquiry": true,
        "isStaffResponse": false
    },
    {
        "name": "Christopher Rodican",
        "email": "crodican@councilsepa.org",
        "date": "4/8/2025",
        "time": "1:05 PM",
        "county": "Staff",
        "subject": "RE: Interested in CRS Training ?",
        "body": "Sarah, You need to fill out the form at I just checked again and you re still not on there. Have you tried to fill it out but are having trouble?",
        "summary": "Christopher Rodican responds with contact information",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Christopher Rodican",
        "email": "crodican@councilsepa.org",
        "date": "4/8/2025",
        "time": "1:05 PM",
        "county": "Staff",
        "subject": "RE: Interested in CRS Training ?",
        "body": "Apologies, that s",
        "summary": "Christopher Rodican responds with contact information",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Christopher Rodican",
        "email": "crodican@councilsepa.org",
        "date": "4/8/2025",
        "time": "1:52 PM",
        "county": "Staff",
        "subject": "RE: Interested in CRS Training ?",
        "body": "Yes, it worked.. Someone will contact you when filling the next available training in your area. Additionally, While waiting to be contacted by someone for our next class in your area, you can check the Pennsylvania Certification Board website for other trainings besides the ones offered by us: It looks like currently there are a few in Reading, two of which cost $50 and the other costs $955. If you are interested in any trainings on the list that are not one of our trainings...",
        "summary": "Christopher Rodican responds with contact information",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Sarah Love",
        "email": "sarahtglick@gmail.com",
        "date": "4/8/2025",
        "time": "1:54 PM",
        "county": "Bucks",
        "subject": "Re: Interested in CRS Training ?",
        "body": "Thank you for getting back to me!",
        "summary": "Sarah Love asks about certification requirements",
        "isInquiry": true,
        "isStaffResponse": false
    },
    {
        "name": "Christopher Rodican",
        "email": "crodican@councilsepa.org",
        "date": "4/8/2025",
        "time": "2:09 PM",
        "county": "Staff",
        "subject": "RE: Sorry!",
        "body": "Ashley, Thank you for reaching out and congratulations on your decision to become a Certified Recovery Specialist. The CRS certification offers a fantastic opportunity to leverage personal experiences in assisting individuals with their recovery from substance use disorder. In Philadelphia, we run several trainings a year which areavailable at no cost to those who live and/or work in the city. I checked our form results and we have you on our list to be contacted when we are filling upcoming trainings...",
        "summary": "Christopher Rodican responds to program inquiry",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Christopher Rodican",
        "email": "crodican@councilsepa.org",
        "date": "4/8/2025",
        "time": "2:59 PM",
        "county": "Staff",
        "subject": "RE: Interest In CPS/CRS Training!",
        "body": "Joe, Thank you for reaching out. Congratulations on your recovery and all that you are doing. We hold several trainings per year in the Southeastern Pennsylvania area, at no cost to the students, available to those who live and/or work in the county in which the training is being conducted. In order to get on the list to be contacted when we hold a training in your county, please complete this short form...",
        "summary": "Christopher Rodican responds to program inquiry",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Christopher Rodican",
        "email": "crodican@councilsepa.org",
        "date": "4/8/2025",
        "time": "3:06 PM",
        "county": "Staff",
        "subject": "RE: Inquiry regarding Certified Recovery Specialist Training",
        "body": "Betsy, I am reaching out to check if you or your husband were able to fill out the form to get him on the list for upcoming Recovery Specialist trainings. I didn t see this email or your last name on the list, so I wanted to make sure you didn't have any issues with the form. Here is the form again if you need it...",
        "summary": "Christopher Rodican responds with contact information",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Keith Robinson",
        "email": "keithrobinsonsr62@gmail.com",
        "date": "4/8/2025",
        "time": "3:13 PM",
        "county": "Philadelphia",
        "subject": "Re:",
        "body": "Can you please send me the application for the Recovery Specialist Course please? Thank you!!",
        "summary": "Keith Robinson asks about certification requirements",
        "isInquiry": true,
        "isStaffResponse": false
    },
    {
        "name": "Christopher Rodican",
        "email": "crodican@councilsepa.org",
        "date": "4/8/2025",
        "time": "3:41 PM",
        "county": "Staff",
        "subject": "RE: Re:",
        "body": "Hi Keith, I see that you filled out the form to be added to the list to be contacted when we are filling the next training in Philadelphia. Someone will contact you when we are filling the class. After you have taken the training, you can apply to take the exam. Additionally, you can look at the Pennsylvania Certification Board website s statewide list of Recovery Specialist trainings, in case another organization is having a training in your area as well...",
        "summary": "Christopher Rodican responds with contact information",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Christopher Rodican",
        "email": "crodican@councilsepa.org",
        "date": "4/8/2025",
        "time": "3:54 PM",
        "county": "Staff",
        "subject": "RE: RE: Crs training date",
        "body": "Hey Aaron, I m reaching out because I noticed that you hadn t completed the form to be contacted for Recovery Specialist trainings. Did you have trouble filling it out? In case you need it again, here is the link: Reach out if you have any questions.",
        "summary": "Christopher Rodican responds with contact information",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Jim Bollinger",
        "email": "jbollinger@councilsepa.org",
        "date": "4/8/2025",
        "time": "4:25 PM",
        "county": "Staff",
        "subject": "Technical Tuesdays is Tonight - Job Junction",
        "body": "Hello, Technical Tuesdays is tonight on Zoom. Tonight's topic: Job Junction 2nd Tuesday of every month Job Placement & Networking Support: Are you ready to work in the field? We will discuss resume building, interview tips, open positions within the region and invite providers to discuss career opportunities. Register at the link below: Hope to see you there!",
        "summary": "Jim Bollinger provides CRS training information",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Joe Nicholson",
        "email": "joeynich151@gmail.com",
        "date": "4/9/2025",
        "time": "7:32 AM",
        "county": "Chester",
        "subject": "Re: Interest In CPS/CRS Training!",
        "body": "Christopher, Thank you so much for this valuable information that is going to change the path of my life! I am available on Monday 4/14 at 10 AM for sure! If anything arises from now until then, do not hesitate to reach out and let me know! Thank you once again! Respectfully, Joe",
        "summary": "Joe Nicholson confirms meeting availability for CRS training discussion",
        "isInquiry": true,
        "isStaffResponse": false
    },
    {
        "name": "Joe Nicholson",
        "email": "joeynich151@gmail.com",
        "date": "4/9/2025",
        "time": "9:32 AM",
        "county": "Chester",
        "subject": "Re: Interest In CPS/CRS Training!",
        "body": "Christopher, Ugh! Something just came up for MONDAY, so would Tuesday be a good time? Let me know! Regards, Joe",
        "summary": "Joe Nicholson requests meeting schedule change to Tuesday",
        "isInquiry": true,
        "isStaffResponse": false
    },
    {
        "name": "Katrina Stopfer",
        "email": "Katrina.Stopfer@USE.SalvationArmy.Org",
        "date": "4/9/2025",
        "time": "10:34 AM",
        "county": "Philadelphia",
        "subject": "CRS training course dates",
        "body": "Good morning, Is there a CRS training course coming up for either the summer or fall? Thank you, Katrina Stopfer, LCSW Assistant Clinical Director, New Day to Stop Trafficking Program The Salvation Army Greater Philadelphia 3150 N. Mascher Street, Philadelphia, PA 19133 Cell: (215) 452-2246",
        "summary": "Katrina Stopfer inquires about CRS training schedule for summer or fall",
        "isInquiry": true,
        "isStaffResponse": false
    },
    {
        "name": "Christopher Rodican",
        "email": "crodican@councilsepa.org",
        "date": "4/9/2025",
        "time": "11:19 AM",
        "county": "Staff",
        "subject": "RE: Interest In CPS/CRS Training!",
        "body": "Okay, we look forward to meeting with you!",
        "summary": "Christopher Rodican confirms meeting arrangements",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Christopher Rodican",
        "email": "crodican@councilsepa.org",
        "date": "4/9/2025",
        "time": "11:40 AM",
        "county": "Staff",
        "subject": "RE: Interest In CPS/CRS Training!",
        "body": "Joe, Sure, we ll see you Tuesday at 10am. Sent you an invite, and here s the link. Meeting ID: 895 1173 7414",
        "summary": "Christopher Rodican provides meeting details and Zoom link for Tuesday",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Joe Nicholson",
        "email": "joeynich151@gmail.com",
        "date": "4/9/2025",
        "time": "11:41 AM",
        "county": "Chester",
        "subject": "Re: Interest In CPS/CRS Training!",
        "body": "Thank you! I will be there!",
        "summary": "Joe Nicholson confirms attendance for Tuesday meeting",
        "isInquiry": true,
        "isStaffResponse": false
    },
    {
        "name": "Christopher Rodican",
        "email": "crodican@councilsepa.org",
        "date": "4/9/2025",
        "time": "12:12 PM",
        "county": "Staff",
        "subject": "RE: CRS training course dates",
        "body": "Katrina, Thank you for reaching out! We do offer several trainings in Philadelphia and the surrounding counties, available to people who live and/or work in the county where that training is conducted. at no cost to the students who live and/or work in that county. There are going to be upcoming Recovery Specialist trainings in Philadelphia this summer and fall, both conducted by us and by other organizations. For our organization, we have a short form to fill out, and then we use the resulting list to fill our classes. Please complete the short form in the following list, and we will contact you for an interview when we are filling a class in your county: Additionally, you can view all upcoming Recovery Specialist trainings across the state at the following link to the Pennsylvania Certification Board s website. The list is continually updated, so checking back regularly is recommended. Filling out the above form will take care of those from our organization, but you may refer to the list in case a Recovery Specialist training from another organization better fits your needs for scheduling, etc Good luck and if you have any more questions, don t hesitate to reach back out to us at CRSTrainingInfo@councilsepa.org .",
        "summary": "Christopher Rodican provides CRS training information for Philadelphia in summer and fall",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Megan Levan",
        "email": "megan@provivewellness.com",
        "date": "4/9/2025",
        "time": "12:55 PM",
        "county": "Montgomery",
        "subject": "CRS Training",
        "body": "Hello, Can you advise when and where is your next CRS training? How could we sign up? Thank You, Megan Levan MA, CAADC, LPC Director Of Operations C: (610) 614-5108 P: (610) 947-0800 ext 101 F: 615.456.2050 E: megan@provivewellness.com Provive Wellness of Wayne 489 Devon Park Dr, Ste 306 Wayne, PA 19087 provivepa.com",
        "summary": "Megan Levan inquires about next CRS training schedule and registration",
        "isInquiry": true,
        "isStaffResponse": false
    },
    {
        "name": "Jack Lark",
        "email": "jacklark3422@icloud.com",
        "date": "4/9/2025",
        "time": "5:42 PM",
        "county": "Unknown",
        "subject": "CRS training inquiry",
        "body": "Hello my name is Jack Lark. I m currently in recovery myself and am working in the field. A coworker of mine, recommend I reach out regarding CRS certification. I m curious how I would be able to being the process of becoming a CRS. Thank you kindly With Unity, JL",
        "summary": "Jack Lark inquires about CRS certification process",
        "isInquiry": true,
        "isStaffResponse": false
    },
    {
        "name": "Christopher Rodican",
        "email": "crodican@councilsepa.org",
        "date": "4/10/2025",
        "time": "9:23 AM",
        "county": "Staff",
        "subject": "RE: CRS Training",
        "body": "Hi Megan! We offer several trainings a year in the southeast Pennsylvania region, available to those who live or work in the county where the training is being held, at no cost to the students. To be added to the list to be contacted when we fill a training in their county, individuals will need to complete a short form: In addition to filling out that form, individuals should also routinely check the Pennsylvania Certification Board website s continually updated list of all Recovery Specialist trainings across Pennsylvania. For the trainings being conducted by The Council of Southeast Pennsylvania, PRO-ACT, Regional Recovery Hub 1, or Regional Recovery Hub 4, they will have already filled out the above form, and for the trainings held by other organizations, there should be contact information for the organizations or instructors. Good luck and give Timber a Milk Bone please!",
        "summary": "Christopher Rodican provides CRS training information and registration details",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Christopher Rodican",
        "email": "crodican@councilsepa.org",
        "date": "4/11/2025",
        "time": "3:22 PM",
        "county": "Staff",
        "subject": "Information about Certified Recovery Specialist training and certification",
        "body": "Ken, Thanks for calling today, it was nice getting to talk with you. Congratulations on your recovery and deciding to become a CRS. It is a really amazing way to use our lived experiences to help guide others on their own recovery journey. As I was saying over the phone, the requirements to enroll in the training are a high school diploma or GED, and 18 months in a continuous manner of personal, lived recovery experience. You already have both of those so we are on the right track! We hold several trainings each year, in and around Southeastern Pennsylvania. The trainings are available to individuals who live or work in the county where the training is being conducted, and they are offered at no cost to the students. Your next step will be to fill out this short form, so that we can contact you for an interview when we are filling a class in Delaware county. In addition to filling out the form, you may also want to regularly check the Pennsylvania Certification Board website s continually updated list of Recovery Specialist trainings across Pennsylvania: Best of luck, Ken, and if you need anything at all, don t hesitate to reach out us again.",
        "summary": "Christopher Rodican provides CRS training information for Delaware county resident Ken",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Colleen Wurtz",
        "email": "collster14@gmail.com",
        "date": "4/14/2025",
        "time": "8:06 AM",
        "county": "Bucks",
        "subject": "Re: CRS Training - Colleen Wurtz",
        "body": "Hi Christopher! I filled out the form/survey! Also I live and work in Bucks County. Looking forward to starting classes! Thank you!",
        "summary": "Colleen Wurtz confirms survey completion and location in Bucks County",
        "isInquiry": true,
        "isStaffResponse": false
    },
    {
        "name": "Christopher Rodican",
        "email": "crodican@councilsepa.org",
        "date": "4/14/2025",
        "time": "10:40 AM",
        "county": "Staff",
        "subject": "RE: CRS Training - Colleen Wurtz",
        "body": "Colleen, That s amazing! Thanks again for reaching out, good luck! If you need anything else don t hesitate to reach back out to us at CRSTrainingInfo@councilsepa.org !",
        "summary": "Christopher Rodican acknowledges Colleen's survey completion",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Lorraine Beckett",
        "email": "lorrainebeckett26@gmail.com",
        "date": "4/14/2025",
        "time": "8:42 PM",
        "county": "Philadelphia",
        "subject": "Technical Tuesday",
        "body": "Hello, I am a CRS here in Philadelphia. I am interested in attending your technical Tuesday s. Please send me the registration link. Thank you for your support. Sent from my iPhone",
        "summary": "Lorraine Beckett requests Technical Tuesday registration link",
        "isInquiry": true,
        "isStaffResponse": false
    },
    {
        "name": "Jim Bollinger",
        "email": "jbollinger@councilsepa.org",
        "date": "4/15/2025",
        "time": "10:01 AM",
        "county": "Staff",
        "subject": "CPS/CRS Professional Development Networking Meeting",
        "body": "Hello everybody! Just a friendly reminder of our monthly Professional Development Networking Meeting for Certified Peer Specialists and Certified Recovery Specialists. Come and be a part of a network of CPS and CRS in Pennsylvania! Reconnect with old classmates and co-workers! Find out what is happening in the peer communities! Date: Thursday, April 17, 2025 Time: 3:00PM to 5:00PM In-Person Location: Pro Act, 1701 W. Lehigh Avenue Online Location: Zoom Information below. Join Zoom Meeting Meeting ID: 987 6321 5961 Passcode: 825205",
        "summary": "Jim Bollinger announces CPS/CRS Professional Development Networking Meeting on April 17",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Jim Bollinger",
        "email": "jbollinger@councilsepa.org",
        "date": "4/15/2025",
        "time": "10:13 AM",
        "county": "Staff",
        "subject": "Local Organization Seeking Partners for Community Day Free Tabling Opportunity!",
        "body": "Hello, I wanted to share an opportunity to support a local community event! A local organization, Katie s Cupboard @ Tabor Lutheran Church, is hosting a Community Day on Saturday, April 19, 2025, from 2:30 PM to 5:00 PM at 4843 N Mascher St, Philadelphia, PA 19120 and they re looking for organizations to table and share resources with families in the community. There is no cost to participate, and tables will be provided. It s a great way to get involved, connect with neighbors, and support a positive community initiative. If you or someone you know is interested, please reach out to Myisha at KatiesCupboardTabor@Outlook.com to get more info or sign up. Feel free to share this with others who might want to be involved!",
        "summary": "Jim Bollinger shares Community Day tabling opportunity on April 19",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Christopher Rodican",
        "email": "crodican@councilsepa.org",
        "date": "4/15/2025",
        "time": "10:58 AM",
        "county": "Staff",
        "subject": "RE: Interest In CPS/CRS Training!",
        "body": "Hey Joe, It was great connecting with you today. I am including Ali and Jon on this email. Talk to you soon!",
        "summary": "Christopher Rodican follows up after meeting with Joe and includes team members",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Joe Nicholson",
        "email": "joeynich151@gmail.com",
        "date": "4/15/2025",
        "time": "11:09 AM",
        "county": "Chester",
        "subject": "Re: Interest In CPS/CRS Training!",
        "body": "Hello All!! Thank you guys for the support, the confidence and the hope that you provided me this morning! I am really excited to be able to assist in any way that I possibly can. I have enclosed The Mirror Workshop and The LIFE Manual (which is constantly being reshaped and reformatted). I will send my Re-Program Policy as soon as possible! Once again, thank you so much. Regards, Joe",
        "summary": "Joe Nicholson shares workshop materials and expresses gratitude for meeting support",
        "isInquiry": true,
        "isStaffResponse": false
    },
    {
        "name": "Jim Bollinger",
        "email": "jbollinger@councilsepa.org",
        "date": "4/15/2025",
        "time": "11:54 AM",
        "county": "Staff",
        "subject": "Technical Tuesdays is Tonight - Register Now!!",
        "body": "Greetings! Looking forward to seeing you at Technical Tuesdays! Tuesday s session Future Focus! Attached is the flyer and registration link. Tuesday, 4/15 Mini-training on Self-Disclosure 1 hour CEU for attending When: Every Tuesday | 7:00 PM 8:30 PM Where: Online (Register in advance link/QR code in the flyer) Each week offers a unique focus to support your journey: Learning Logistics (1st Tuesday): Prep for your Recovery Specialist certification/ exam. Job Junction (2nd Tuesday): Resume tips, interview prep, and job networking. Future Focus (3rd Tuesday): Mini-trainings and recertification support. Courageous Conversations (4th Tuesday): Share and listen to lived experiences to reduce stigma.",
        "summary": "Jim Bollinger promotes Technical Tuesdays session on Self-Disclosure",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Christopher Rodican",
        "email": "crodican@councilsepa.org",
        "date": "4/17/2025",
        "time": "10:41 AM",
        "county": "Staff",
        "subject": "RE: Previous Student",
        "body": "Kavia, Thank you so much for reaching out. Even though you have been unable to take the test and become certified yet, congratulations still on your continued recovery! As the Supporting Youth Recovery Certified Enhanced Certified Recovery Specialist Training Cohort 4 took place prior to 2021, you will unfortunately need to retake the training before you can take the exam. The Recovery Specialist curriculum was updated and standardized across the state in 2021. Your situation is common, and I promise it s not the end of the world. Maybe life got in the way and suddenly you didn t have the time or resources to focus on your career goals at the time. If you are ready now, we are here for you. As you likely remember, the course is made up of ten eight-hour days. It can either be taken over two weeks, Monday to Friday, or taken on Saturdays over ten weeks. We hold several Recovery Specialist trainings in Southeast Pennsylvania a year, at no cost to the students, open to people who either live or work in the county that the training is held in. So that I can best assist you, can you tell me what counties you live in and work in? Also, please use the following link to complete a very short form. It will add you to the list we use when filling our classes.",
        "summary": "Christopher Rodican explains retaking requirements for previous CRS student Kavia",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Jim Bollinger",
        "email": "jbollinger@councilsepa.org",
        "date": "4/17/2025",
        "time": "11:14 AM",
        "county": "Staff",
        "subject": "CRSS Training Series Now Underway Still Time to Join!",
        "body": "Hello, We re excited to share that the Certified Recovery Specialist Supervisor (CRSS) Training Series began on Tuesday, April 15 but it s not too late to join! The training runs Tuesdays and Thursdays from 1:00 PM to 4:00 PM through May 15, 2025, and is held virtually via Zoom. This 10-session series is designed to fulfill the educational requirements for CRSS certification through the Pennsylvania Certification Board (PCB). It covers the core domains of: Recovery Specialist Development Advocacy & System Navigation Organizational Practices Ethical Responsibility & Professionalism If you missed the first few sessions, don t worry you re still welcome to attend the remaining sessions. Plus, the full training series will be offered again in the next cohort, likely beginning in July or August, so any sessions you miss now can be completed then. Please note: Completion of this training alone does not fulfill all CRSS certification criteria. Additional requirements such as work experience and on-the-job supervision must also be met. We encourage you to review the full certification requirements on the PCB website: Training Dates: April 15 May 14, 2025 Time: Tuesdays & Thursdays, 1:00 PM 4:00 PM Location: Online via Zoom Cost: Free (funded by DBHIDS)",
        "summary": "Jim Bollinger announces ongoing CRSS Training Series with late enrollment opportunity",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Jim Bollinger",
        "email": "jbollinger@councilsepa.org",
        "date": "4/17/2025",
        "time": "11:28 AM",
        "county": "Staff",
        "subject": "Fw: Registration is Open: Faith & Spiritual Affairs Conference - April 24",
        "body": "Please see attached email. The City of Philadelphia Department of Behavioral Health and Intellectual disAbility Services (DBHIDS) is proud to host the 18th annual Faith and Spiritual Affairs Conference on April 24 from 9 a.m. to 4 p.m. at Temple University Student Center, Student Center South, second floor, 1755 N. 13th St., Philadelphia 19122. This year s theme is Healing Together: Faith, Compassion, and the Journey to Suicide Prevention. The conference will focus on suicide prevention for youth and young adults with an emphasis on how faith communities can offer essential support. Join us for: Multi-perspective panel discussions. Dynamic workshops. Helpful resources. Live entertainment from Beyond the Bars. There will be a continental breakfast provided from 8 to 9 a.m.",
        "summary": "Jim Bollinger forwards Faith & Spiritual Affairs Conference information for April 24",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Barbara Winterstein",
        "email": "barbw77@icloud.com",
        "date": "4/17/2025",
        "time": "7:59 PM",
        "county": "Unknown",
        "subject": "Training courses",
        "body": "My name is Barbara winterstein I m interested in the training for recovery specialist. I have 23 months in recovery. I m very interested in helping other addicts. Please get back to me when the next training courses will be.. thanks in advance",
        "summary": "Barbara Winterstein inquires about CRS training with 23 months recovery",
        "isInquiry": true,
        "isStaffResponse": false
    },
    {
        "name": "Jim Bollinger",
        "email": "jbollinger@councilsepa.org",
        "date": "4/18/2025",
        "time": "11:01 AM",
        "county": "Staff",
        "subject": "Mental Health Advocacy Day May 6th - 2025",
        "body": "Mental Health Advocacy Day May 6th, 2025 There are still seats available to take a bus with us to the state capital! Event Details: Networking & Resource Sharing, Legislative Visits, and Lunch (on your own): 10:00 AM 1:00 PM Press Conference: 1:00 PM 2:00 PM agenda and additional information to come. Again, the attached document will help guide this effort, but we encourage you to schedule visits with your legislators in advance. If an in-person visit is not possible, consider a written comment card/letter that can be delivered to your legislators. We will bring some blank cards on the day for anyone who wishes to complete and drop off on the day. You can also visit your legislators at their local offices, send an email, or reach out by phone. There is great power in sharing our voices both collectively and individually!",
        "summary": "Jim Bollinger promotes Mental Health Advocacy Day bus trip on May 6",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Christopher Rodican",
        "email": "crodican@councilsepa.org",
        "date": "4/21/2025",
        "time": "9:23 AM",
        "county": "Staff",
        "subject": "RE: Training courses",
        "body": "Hi Megan! So that we may best assist you, can you please tell me the counties that you live and work in? We offer several trainings a year in the southeast Pennsylvania region, available to those who live or work in the county where the training is being held, at no cost to the students. Additionally, please complete this short form to be added to our list to be contacted when we fill a training in your county: In addition to filling out that form, individuals should also routinely check the Pennsylvania Certification Board website s continually updated list of all Recovery Specialist trainings across Pennsylvania.",
        "summary": "Christopher Rodican responds to Barbara Winterstein with training information",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Alison Dunn",
        "email": "adunn@councilsepa.org",
        "date": "4/21/2025",
        "time": "9:23 AM",
        "county": "Staff",
        "subject": "Recovery Specialist Interest Survey, Line Dancing, MCRCC Contact",
        "body": "Hey Stefan! Please complete our Recovery Specialist Interest Survey. Once we know more of the Montgomery County Training, we will follow up also. Recovery Specialist Training Interest Survey: (This survey is for anyone interested in becoming a CRS or CFRS. When a training becomes available in their area, we send an email with details and provide support for enrollment.) I attached the MCRCC calendar and Line Dancing event. If you have any questions or are interested in volunteering at the center, you will want to contact Liz Wendt at LWendt@councilsepa.org",
        "summary": "Alison Dunn provides Stefan with Recovery Specialist survey and MCRCC information",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Christopher Rodican",
        "email": "crodican@councilsepa.org",
        "date": "4/21/2025",
        "time": "9:33 AM",
        "county": "Staff",
        "subject": "RE: Technical Tuesday",
        "body": "Lorraine, Thank you for reaching out! Here is the registration link you requested. Additionally, here is a copy of our flyer. Thanks and see you soon!",
        "summary": "Christopher Rodican provides Technical Tuesday registration link to Lorraine",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Christopher Rodican",
        "email": "crodican@councilsepa.org",
        "date": "4/21/2025",
        "time": "9:44 AM",
        "county": "Staff",
        "subject": "RE: Training courses",
        "body": "Barbara, Thank you for reaching out and congratulations on your recovery! The Certified Recovery Specialist certification offers a fantastic opportunity to leverage personal experiences in assisting individuals with their recovery from substance use disorder. For more info about the certification, please see: So we can best assist you, can you tell me what counties you live in and work in? We hold several Recovery Specialist trainings in Southeast Pennsylvania a year, at no cost to the students, open to people who either live or work in the county where the training is being conducted. Please get back to me after you have filled out this short form, which will add you to the list that we use to fill our classes in each county Additionally, I would like to share with you the Pennsylvania Certification Board website's continually updated list of Recovery Specialist trainings across the state. We look forward to hearing back from you after you fill out the form! Good luck!",
        "summary": "Christopher Rodican provides Barbara with detailed CRS training information and requirements",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Jim Bollinger",
        "email": "jbollinger@councilsepa.org",
        "date": "4/22/2025",
        "time": "10:51 AM",
        "county": "Staff",
        "subject": "CRSS Training Series Now Underway Still Time to Join!",
        "body": "Hello, We re excited to share that the Certified Recovery Specialist Supervisor (CRSS) Training Series began on Tuesday, April 15 but it s not too late to join! The training runs Tuesdays and Thursdays from 1:00 PM to 4:00 PM through May 15, 2025, and is held virtually via Zoom. This 10-session series is designed to fulfill the educational requirements for CRSS certification through the Pennsylvania Certification Board (PCB). Training Dates: April 15 May 14, 2025 Time: Tuesdays & Thursdays, 1:00 PM 4:00 PM Location: Online via Zoom Cost: Free (funded by DBHIDS)",
        "summary": "Jim Bollinger repeats CRSS Training Series announcement with late enrollment opportunity",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Jim Bollinger",
        "email": "jbollinger@councilsepa.org",
        "date": "4/23/2025",
        "time": "9:48 AM",
        "county": "Staff",
        "subject": "The 'Art of Reporting' Workshop",
        "body": "Hi all! Please share with your networks and providers. We encourage everyone to attend and listen about how to report work earnings to different social service entities, how reporting is crucial to maintaining benefits and more! Please reach out to Taylor.samuels@phila.gov for more info The 'Art of Reporting' Workshop 9:30 a.m. to noon May 9 DBHIDS, 1601 Market St., Sixth Floor, Conference Center We are excited to invite you to \"The Art of Reporting,\" an informative and informal session covering how to report earnings to social service agencies such as the Social Security Administration, Department of Public Welfare, and others. This session is designed for individuals entering the workforce and receiving benefits as well as their support teams, such as case managers, Mobile Psych Rehabilitation Services, Certified Peer Specialists, Certified Recovery Specialists, community health workers, or anyone else involved in a care team.",
        "summary": "Jim Bollinger promotes 'Art of Reporting' Workshop on May 9 about benefit reporting",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Amber Johnson",
        "email": "amberikeema2535@icloud.com",
        "date": "4/23/2025",
        "time": "1:14 PM",
        "county": "Unknown",
        "subject": "",
        "body": "Good afternoon my name is Amber Johnson I am interested in the CRS training my phone number is 2159898777 my email is amberikeema2535@icloud.com Sent from my iPhone",
        "summary": "Amber Johnson inquires about CRS training",
        "isInquiry": true,
        "isStaffResponse": false
    },
    {
        "name": "Shannon Kirby",
        "email": "stkirby@buckscounty.org",
        "date": "4/25/2025",
        "time": "3:08 PM",
        "county": "Bucks",
        "subject": "Training Inquiry",
        "body": "Good Afternoon, I wanted to check to see if there are set dates for when the CRS trainings take place. If there are, can you please confirm the scheduled trainings for 2025? Thank you, Shannon Kirby Opioid Settlement Program Manager Bucks County Human Services 55 East Court Street Doylestown, PA 18901 Phone: 215.348.6302",
        "summary": "Shannon Kirby requests 2025 CRS training schedule information",
        "isInquiry": true,
        "isStaffResponse": false
    },
    {
        "name": "Christopher Rodican",
        "email": "crodican@councilsepa.org",
        "date": "4/25/2025",
        "time": "3:29 PM",
        "county": "Staff",
        "subject": "RE:",
        "body": "Amber, Thanks for reaching out and congratulations on your decision to become a Certified Recovery Specialist! So that we can best assist you, can you tell me what counties you live in and work in? We hold several Recovery Specialist trainings in Southeast Pennsylvania a year, at no cost to the students, open to people who either live or work in the county that the training is held in. Please use the following link to complete our short Recovery Specialist Interest Survey so that you may be added to our list which is used to fill classes. When a class is available for you we will contact you with the next steps: Additionally, the Pennsylvania Certification Board keeps an updated list of all currently scheduled Recovery Specialist trainings across the state which you can periodically check here:",
        "summary": "Christopher Rodican responds to Amber Johnson with CRS training information",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Kristy Jameson",
        "email": "kccj33@gmail.com",
        "date": "4/26/2025",
        "time": "2:48 PM",
        "county": "Montgomery",
        "subject": "Training",
        "body": "Hello, I would like to apply for the training program. I live in montgomery county and have a bachelor degree as well as lived experience I believe I would be a great asset to the community. Thanks for your time, Kristy Jameson",
        "summary": "Kristy Jameson applies for CRS training program in Montgomery County",
        "isInquiry": true,
        "isStaffResponse": false
    },
    {
        "name": "Jim Bollinger",
        "email": "jbollinger@councilsepa.org",
        "date": "4/28/2025",
        "time": "9:23 AM",
        "county": "Staff",
        "subject": "Learn to Share the Value of Peer Support with Providers & Communities May 7 (ZOOM)",
        "body": "Hello, We re excited to invite you to an upcoming Information Session on Peer-Based Professional Services, presented by PaPSC. Date: Wednesday, May 7, 2025 Time: 10:00 AM 11:30 AM This presentation provides an in-depth overview of peer-based professionals and their unique role in behavioral health and recovery settings. Designed specifically for providers and service teams, the session explores the distinction between natural peer support and certified peer roles, outlines the credentialing process for Certified Peer Specialists (CPS) and Certified Recovery Specialists (CRS), and highlights the benefits of peer services within clinical and community environments. Important Note: Please be aware that this is not a CEU training. We are unable to offer Continuing Education (CE) hours for this session, and attendees should not expect to receive them.",
        "summary": "Jim Bollinger announces PaPSC Information Session on peer support for May 7",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Jim Bollinger",
        "email": "jbollinger@councilsepa.org",
        "date": "4/28/2025",
        "time": "9:31 AM",
        "county": "Staff",
        "subject": "Upcoming Certified Peer Specialist (CPS) Training Opportunity Montgomery County",
        "body": "NOTE: This is not a Pro-Act training. I am passing the information along for those who may be interested. Hello, For those who live or work in Montgomery County, there is an upcoming Certified Peer Specialist (CPS) Training, scheduled for late Spring to early Summer 2025! This free training opportunity is open to individuals who live or work in Montgomery County. The CPS training provides the skills and knowledge necessary to take the Pennsylvania Certification Board CPS Exam, paving the way for professional opportunities in peer support roles. Eligibility Requirements: Must be 18 years of age or older Must have a mental health diagnosis and be in a stable place in your recovery, able to offer positive support to others Please note: Lived experience with substance use alone does not meet the qualification standard",
        "summary": "Jim Bollinger shares CPS training opportunity for Montgomery County residents",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Christopher Rodican",
        "email": "crodican@councilsepa.org",
        "date": "4/28/2025",
        "time": "2:57 PM",
        "county": "Staff",
        "subject": "RE: Training Inquiry",
        "body": "Good afternoon, Shannon, To my knowledge, the SCA hosts 2 Recovery Specialist Trainings each year. The last few trainings were held in May 2024, September 2024, and March 2025. I do not have confirmed dates for their next Recovery Specialist Training. When we receive the training flyers, we promote them and check regularly on the PCB website for upcoming trainings. The Recovery Hub does not have training scheduled currently. We did have discussions with a provider, but nothing was finalized. Please let me know if you would like to schedule a Zoom meeting to discuss any potential training opportunities.",
        "summary": "Christopher Rodican responds to Shannon about 2025 CRS training schedule",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Melissa Groden",
        "email": "mgroden@councilsepa.org",
        "date": "4/29/2025",
        "time": "9:35 AM",
        "county": "Staff",
        "subject": "Fw: New Voice Message from RAJKOWSKI,JOAN (215) 869-6101 on 04/29/2025 9:28 AM",
        "body": "Good morning please see message! Thanks, Melissa voicemail from Joan Rakowski: \"Hi, and my name is Joan Rakowski and I applied to get a seat with the C R s program. I am I am almost certain that I got in and I have a seat but something happened with my email. It is all like, was all weird and I had to reset it and I lost a lot of emails So I I do not see that 1 anywhere. I am just trying to reach out to someone to find out if or if I do not have a seat. And for the class, which starts on Monday, I have tried emailing and going through a contact, but I have not heard anything back from anybody. Can somebody please call me At 205 8696101. Even if it is a no, it is fine. Just I just need to know because I have to get a job. If not. All right, thank you very much for your time. Bye bye and.\"",
        "summary": "Melissa Groden forwards voicemail from Joan Rakowski about CRS program seat confirmation",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Fred Shue",
        "email": "fshue@councilsepa.org",
        "date": "4/29/2025",
        "time": "9:41 AM",
        "county": "Staff",
        "subject": "RE: New Voice Message from RAJKOWSKI,JOAN (215) 869-6101 on 04/29/2025 9:28 AM",
        "body": "Thanks Melissa!",
        "summary": "Fred Shue acknowledges Melissa's voicemail forwarding",
        "isInquiry": false,
        "isStaffResponse": true
    },
    {
        "name": "Christopher Rodican",
        "email": "crodican@councilsepa.org",
        "date": "4/29/2025",
        "time": "10:22 AM",
        "county": "Staff",
        "subject": "RE: Training",
        "body": "Hi Kristy, Congratulations on your decision to become a Certified Recovery Specialist, an awesome way to use your lived experiences to help individuals on their recovery journey. It is for individuals with personal, lived experience in their own substance use disorder recovery. The Recovery Specialist trainings which we offer are held across the region several times a year, and are available to those who live or work in the county where the training is being conducted. They are provided at no cost to the student. I see that you have already filled out our Recovery Specialist Interest Survey, which is a great step since we use this to fill our classes. When we hold a training in Montgomery County, someone will contact you with next steps. In the meantime, though, you can also look at the Pennsylvania Certification Board website s regularly updated statewide list of Recovery Specialist trainings, in case another organization has a training on the schedule which is suitable. I included the list below. Depending on your budget and location requirements, you may be able to locate a suitable training. If you see one you are interested in, check the included flyer in the Class column for that training s instructions, and if there is no flyer, email the instructor from the Contact column. It appears that there are two upcoming trainings in Reading that only cost $50, so that could be a fit. Also, the page is updated whenever a new training is scheduled, so if there isn t a suitable training at this time, you can check back regularly. Congratulations again on your recovery! Best of Luck!",
        "summary": "Christopher Rodican provides Kristy with comprehensive CRS training options and state listing",
        "isInquiry": false,
        "isStaffResponse": true
    }
];