emailData =
    [
        {
            "name": "Alex Smith",
            "email": "alex.smith@example.org",
            "date": "7/1/2025",
            "time": "10:00 AM",
            "county": "Philadelphia",
            "subject": "CRS Training Info",
            "body": "Hi, I am interested in your Certified Recovery Specialist (CRS) training. I live in Philadelphia. Could you please send me some information about the upcoming classes and any scholarship opportunities? Thank you, Alex Smith",
            "summary": "Individual expresses interest in CRS certification training",
            "isInquiry": true,
            "isStaffResponse": false
        },
        {
            "name": "Christopher Rodican",
            "email": "christopher.rodican@councilsepa.org",
            "date": "7/1/2025",
            "time": "10:15 AM",
            "county": "Unknown",
            "subject": "RE: CRS Training Info",
            "body": "Hi Alex, I've attached our course catalog and a scholarship application form. There is a CRS class starting in Philadelphia at the end of July. Let me know if you have any other questions. Chris",
            "summary": "Staff provides CRS training information and support",
            "isInquiry": false,
            "isStaffResponse": true
        },
        {
            "name": "Maria Garcia",
            "email": "maria.garcia@example.net",
            "date": "7/2/2025",
            "time": "2:30 PM",
            "county": "Montgomery",
            "subject": "CFRS Class",
            "body": "Hello, I am a family recovery specialist and I am looking for a CFRS class in the Norristown area. Do you have any upcoming classes? Thank you.",
            "summary": "Individual inquires about CFRS (family recovery specialist) training",
            "isInquiry": true,
            "isStaffResponse": false
        },
        {
            "name": "jim bollinger",
            "email": "jim.bollinger@councilsepa.org",
            "date": "7/2/2025",
            "time": "3:00 PM",
            "county": "Unknown",
            "subject": "RE: CFRS Class",
            "body": "Hi Maria, We have a CFRS class starting in Norristown in August. I have attached the full schedule and registration link. Please let me know if you have any questions. Jim",
            "summary": "Staff provides CRS training information and support",
            "isInquiry": false,
            "isStaffResponse": true
        },
        {
            "name": "Thomas Brown",
            "email": "thomas.brown@example.org",
            "date": "7/3/2025",
            "time": "11:00 AM",
            "county": "Bucks",
            "subject": " CRS Training",
            "body": "I am interested in becoming a Certified Recovery Specialist. I live in Bucks County. Do you have any training programs available?",
            "summary": "Individual expresses interest in CRS certification training",
            "isInquiry": true,
            "isStaffResponse": false
        },
        {
            "name": "alison dunn",
            "email": "alison.dunn@councilsepa.org",
            "date": "7/3/2025",
            "time": "11:30 AM",
            "county": "Unknown",
            "subject": "RE: CRS Training",
            "body": "Hi Thomas, We have a CRS class starting in Levittown in September. I have attached the full schedule and registration link. Let me know if you have any questions. Allison",
            "summary": "Staff provides CRS training information and support",
            "isInquiry": false,
            "isStaffResponse": true
        },
        {
            "name": "Jessica Lee",
            "email": "jessica.lee@example.com",
            "date": "7/5/2025",
            "time": "9:00 AM",
            "county": "Philadelphia",
            "subject": "My Recovery Journey",
            "body": "I have been in recovery for 10 years and I am looking for a way to help others. I heard about your CRS program and was wondering if it would be a good fit for me. I live in Philly. Any information would be helpful. Thanks, Jessica",
            "summary": "Individual shares recovery story and training interest",
            "isInquiry": true,
            "isStaffResponse": false
        },
        {
            "name": "Christopher Rodican",
            "email": "christopher.rodican@councilsepa.org",
            "date": "7/5/2025",
            "time": "9:15 AM",
            "county": "Unknown",
            "subject": "RE: My Recovery Journey",
            "body": "Hi Jessica, That's wonderful! We would be honored to have you as part of our program. I have attached a brochure with details about the CRS training. Please let me know if you have any questions. Chris",
            "summary": "Staff provides CRS training information and support",
            "isInquiry": false,
            "isStaffResponse": true
        },
        {
            "name": "David Wilson",
            "email": "david.wilson@example.org",
            "date": "7/7/2025",
            "time": "1:00 PM",
            "county": "Chester",
            "subject": "Scholarship Question",
            "body": "To whom it may concern, I am writing on behalf of a client who is interested in the CRS training. We are looking for information on scholarship or funding options that may be available to them. Our client is in Chester County. Please let us know if you can assist. Best, David Wilson Chester County Alliance",
            "summary": "Organization requests scholarship information for client",
            "isInquiry": true,
            "isStaffResponse": false
        },
        {
            "name": "jim bollinger",
            "email": "jim.bollinger@councilsepa.org",
            "date": "7/7/2025",
            "time": "1:30 PM",
            "county": "Unknown",
            "subject": "RE: Scholarship Question",
            "body": "Hi David, Thank you for your inquiry. We have several scholarship options available. I'll connect you with our scholarship coordinator who can provide the details and assist your client with the application process. Jim",
            "summary": "Staff responds to scholarship funding inquiry",
            "isInquiry": false,
            "isStaffResponse": true
        },
        {
            "name": "Melissa Groden",
            "email": "melissa.groden@councilsepa.org",
            "date": "7/8/2025",
            "time": "9:15 AM",
            "county": "Unknown",
            "subject": "Technical Tuesday: July 15th",
            "body": "Hi everyone, This is a reminder about our next Technical Tuesday session on July 15th. This month's topic is 'Ethical Considerations in Peer Support'. Please RSVP by Friday so we can get a headcount. See you there! Melissa Groden",
            "summary": "Staff sends Technical Tuesday training announcement",
            "isInquiry": false,
            "isStaffResponse": true
        },
        {
            "name": "Robert Clark",
            "email": "robert.clark@example.com",
            "date": "7/10/2025",
            "time": "11:40 AM",
            "county": "Montgomery",
            "subject": "CRS Practice Test",
            "body": "Hi, I'm a student in the current CRS class. Do you have any practice tests or exam prep materials available? I have my certification exam coming up in two weeks and want to be fully prepared. Thanks, Robert",
            "summary": "Individual expresses interest in CRS certification training",
            "isInquiry": true,
            "isStaffResponse": false
        },
        {
            "name": "Christopher Rodican",
            "email": "christopher.rodican@councilsepa.org",
            "date": "7/10/2025",
            "time": "12:00 PM",
            "county": "Unknown",
            "subject": "RE: CRS Practice Test",
            "body": "Hi Robert, Yes, we have a comprehensive practice exam available online. I've also attached a study guide with key concepts for the upcoming exam. Best of luck! Chris",
            "summary": "Staff provides exam practice materials to student",
            "isInquiry": false,
            "isStaffResponse": true
        },
        {
            "name": "Sarah Thompson",
            "email": "sarah.thompson@example.org",
            "date": "7/11/2025",
            "time": "3:00 PM",
            "county": "Bucks",
            "subject": "Advanced Training",
            "body": "I'm a Certified Recovery Specialist (CRS) and I am looking for advanced training. I live in Bristol. Do you offer any workshops for experienced professionals? Please let me know. Sarah Thompson",
            "summary": "Individual requests training class information",
            "isInquiry": true,
            "isStaffResponse": false
        },
        {
            "name": "alison dunn",
            "email": "alison.dunn@councilsepa.org",
            "date": "7/11/2025",
            "time": "3:30 PM",
            "county": "Unknown",
            "subject": "RE: Advanced Training",
            "body": "Hi Sarah, We have several advanced workshops scheduled this fall. I will send you a separate email with the full list and descriptions. Thanks for your interest! Allison",
            "summary": "Staff provides CRS training information and support",
            "isInquiry": false,
            "isStaffResponse": true
        },
        {
            "name": "Mark Evans",
            "email": "mark.evans@example.com",
            "date": "7/14/2025",
            "time": "9:45 AM",
            "county": "Montgomery",
            "subject": "Re: Technical Tuesday: July 15th",
            "body": "Hi Melissa, I'm excited about the upcoming Technical Tuesday session. Will this be a Zoom meeting, or is it in person? Please let me know the details. Thanks, Mark",
            "summary": "Individual expresses interest in CRS certification training",
            "isInquiry": true,
            "isStaffResponse": false
        },
        {
            "name": "Melissa Groden",
            "email": "melissa.groden@councilsepa.org",
            "date": "7/14/2025",
            "time": "10:00 AM",
            "county": "Unknown",
            "subject": "RE: Technical Tuesday: July 15th",
            "body": "Hi Mark, This will be a virtual meeting via Zoom. I've included the meeting link and password in this email. See you there! Melissa",
            "summary": "Staff coordinates virtual meeting or training",
            "isInquiry": false,
            "isStaffResponse": true
        },
        {
            "name": "test",
            "email": "test@councilsepa.org",
            "date": "7/15/2025",
            "time": "11:00 AM",
            "county": "Unknown",
            "subject": "Test Email 2",
            "body": "This is a test email sent from our automated system. Please disregard. Thank you.",
            "summary": "Staff testing automated systems",
            "isInquiry": false,
            "isStaffResponse": true
        },
        {
            "name": "Laura Adams",
            "email": "laura.adams@example.org",
            "date": "7/16/2025",
            "time": "2:10 PM",
            "county": "Philadelphia",
            "subject": "CFRS Supervisor Training",
            "body": "Hello, I am a CFRS in Philadelphia and am interested in becoming a supervisor. Do you offer any training or certification for this? Thank you.",
            "summary": "Individual inquires about recovery specialist training",
            "isInquiry": true,
            "isStaffResponse": false
        },
        {
            "name": "jim bollinger",
            "email": "jim.bollinger@councilsepa.org",
            "date": "7/17/2025",
            "time": "9:00 AM",
            "county": "Unknown",
            "subject": "RE: CFRS Supervisor Training",
            "body": "Hi Laura, We will be starting our new CFRS Supervisor training program in the fall. I've attached the full program description and a link to register. Please let me know if you have any questions. Jim",
            "summary": "Staff announces supervisor training program",
            "isInquiry": false,
            "isStaffResponse": true
        },
        {
            "name": "Ryan Johnson",
            "email": "ryan.johnson@example.com",
            "date": "7/18/2025",
            "time": "1:00 PM",
            "county": "Montgomery",
            "subject": "General Training Question",
            "body": "Hello, I'm new to the field and would like to find out more about the training classes you offer. I live in Narberth, so Montgomery County classes would be best for me. Thank you for your time.",
            "summary": "Individual requests training class information",
            "isInquiry": true,
            "isStaffResponse": false
        },
        {
            "name": "alison dunn",
            "email": "alison.dunn@councilsepa.org",
            "date": "7/18/2025",
            "time": "2:15 PM",
            "county": "Unknown",
            "subject": "RE: General Training Question",
            "body": "Hi Ryan, Thanks for reaching out. We have a variety of training classes. I've attached our full course catalog. We have several sessions coming up in your area. Let me know if I can help further. Allison",
            "summary": "Staff provides CRS training information and support",
            "isInquiry": false,
            "isStaffResponse": true
        },
        {
            "name": "Michelle Davis",
            "email": "michelle.davis@example.net",
            "date": "7/19/2025",
            "time": "10:30 AM",
            "county": "Bucks",
            "subject": "CRS Application Question",
            "body": "I am working on my CRS application and had a question about the reference requirements. Can I use a family member? I live in Levittown. Please advise. Thanks, Michelle",
            "summary": "Individual expresses interest in CRS certification training",
            "isInquiry": true,
            "isStaffResponse": false
        },
        {
            "name": "alison dunn",
            "email": "alison.dunn@councilsepa.org",
            "date": "7/19/2025",
            "time": "10:45 AM",
            "county": "Unknown",
            "subject": "RE: CRS Application Question",
            "body": "Hi Michelle, Please refer to the application requirements document I've attached. It has a section on references and who is eligible to be a reference. If you have any further questions, please contact the main office number. Allison",
            "summary": "Staff provides CRS training information and support",
            "isInquiry": false,
            "isStaffResponse": true
        },
        {
            "name": "Daniel Wilson",
            "email": "daniel.wilson@example.org",
            "date": "7/21/2025",
            "time": "1:50 PM",
            "county": "Delaware",
            "subject": "CFRS Training Availability",
            "body": "Hi, Are there any upcoming CFRS training classes available in Delaware County? I am interested in signing up. Thanks, Daniel",
            "summary": "Individual inquires about CFRS (family recovery specialist) training",
            "isInquiry": true,
            "isStaffResponse": false
        },
        {
            "name": "Christopher Rodican",
            "email": "christopher.rodican@councilsepa.org",
            "date": "7/21/2025",
            "time": "2:05 PM",
            "county": "Unknown",
            "subject": "RE: CFRS Training Availability",
            "body": "Hi Daniel, We don't currently have a CFRS class scheduled in Delaware County, but we have a virtual option coming up. Would you like me to send you the details for the virtual class? Chris",
            "summary": "Staff provides CRS training information and support",
            "isInquiry": false,
            "isStaffResponse": true
        },
        {
            "name": "Kevin White",
            "email": "kevin.white@example.com",
            "date": "7/22/2025",
            "time": "11:20 AM",
            "county": "Montgomery",
            "subject": "Workshop Inquiry",
            "body": "Hello, I am a professional working in the mental health field and I was hoping to find out about any upcoming workshops you may be hosting. I am particularly interested in workshops for professionals. I work in Narberth. Thanks, Kevin",
            "summary": "Individual requests training class information",
            "isInquiry": true,
            "isStaffResponse": false
        },
        {
            "name": "alison dunn",
            "email": "alison.dunn@councilsepa.org",
            "date": "7/22/2025",
            "time": "11:45 AM",
            "county": "Unknown",
            "subject": "RE: Workshop Inquiry",
            "body": "Hi Kevin, Thanks for reaching out. We have a full slate of professional workshops coming up in the fall, including a new series on peer support in mental health settings. I've attached our fall workshop schedule for your review. Let me know if you have any questions. Allison",
            "summary": "Staff provides CRS training information and support",
            "isInquiry": false,
            "isStaffResponse": true
        },
        {
            "name": "Jennifer Hall",
            "email": "jennifer.hall@example.org",
            "date": "7/23/2025",
            "time": "9:30 AM",
            "county": "Philadelphia",
            "subject": "General Question",
            "body": "Hello, I received a flyer about your services and wanted to ask a general question about what you do. I live in Philly. I am particularly interested in the family services you offer.",
            "summary": "Individual inquires about recovery specialist training",
            "isInquiry": true,
            "isStaffResponse": false
        },
        {
            "name": "Christopher Rodican",
            "email": "christopher.rodican@councilsepa.org",
            "date": "7/23/2025",
            "time": "10:00 AM",
            "county": "Unknown",
            "subject": "RE: General Question",
            "body": "Hi Jennifer, Thanks for your interest! I've attached our general brochure that outlines all of our services, including our family programs. Please feel free to call us at your convenience to discuss this further. Chris",
            "summary": "Staff provides CRS training information and support",
            "isInquiry": false,
            "isStaffResponse": true
        },
        {
            "name": "unknown",
            "email": "unknown",
            "date": "7/24/2025",
            "time": "2:00 PM",
            "county": "Philadelphia",
            "subject": " CRS class availability",
            "body": "Do you have any CRS classes starting in the next couple of months in the Philadelphia area? I am hoping to get certified as soon as possible.",
            "summary": "Individual expresses interest in CRS certification training",
            "isInquiry": true,
            "isStaffResponse": false
        },
        {
            "name": "Melissa Groden",
            "email": "melissa.groden@councilsepa.org",
            "date": "7/25/2025",
            "time": "8:30 AM",
            "county": "Unknown",
            "subject": "RE: CRS class availability",
            "body": "We have a CRS class starting in August in Philadelphia. I have attached the full schedule and registration link. Let me know if you have any questions. Melissa",
            "summary": "Staff provides CRS training information and support",
            "isInquiry": false,
            "isStaffResponse": true
        },
        {
            "name": "John Smith",
            "email": "john.smith@example.org",
            "date": "7/25/2025",
            "time": "10:00 AM",
            "county": "Montgomery",
            "subject": "CRS Training Info",
            "body": "Hi, I am interested in your Certified Recovery Specialist (CRS) training. I live in Exton. Could you please send me some information about the upcoming classes and any scholarship opportunities? Thank you, John Smith",
            "summary": "Individual expresses interest in CRS certification training",
            "isInquiry": true,
            "isStaffResponse": false
        },
        {
            "name": "Christopher Rodican",
            "email": "christopher.rodican@councilsepa.org",
            "date": "7/25/2025",
            "time": "10:15 AM",
            "county": "Unknown",
            "subject": "RE: CRS Training Info",
            "body": "Hi John, I've attached our course catalog and a scholarship application form. There is a CRS class starting in Exton at the end of July. Let me know if you have any other questions. Chris",
            "summary": "Staff provides CRS training information and support",
            "isInquiry": false,
            "isStaffResponse": true
        },
        {
            "name": "Susan Jones",
            "email": "susan.jones@example.net",
            "date": "7/26/2025",
            "time": "2:30 PM",
            "county": "Lehigh",
            "subject": "CFRS Class",
            "body": "Hello, I am a family recovery specialist and I am looking for a CFRS class in the Allentown area. Do you have any upcoming classes? Thank you.",
            "summary": "Individual inquires about CFRS (family recovery specialist) training",
            "isInquiry": true,
            "isStaffResponse": false
        },
        {
            "name": "jim bollinger",
            "email": "jim.bollinger@councilsepa.org",
            "date": "7/26/2025",
            "time": "3:00 PM",
            "county": "Unknown",
            "subject": "RE: CFRS Class",
            "body": "Hi Susan, We have a CFRS class starting in Allentown in August. I have attached the full schedule and registration link. Please let me know if you have any questions. Jim",
            "summary": "Staff provides CRS training information and support",
            "isInquiry": false,
            "isStaffResponse": true
        },
        {
            "name": "Peter Thomas",
            "email": "peter.thomas@example.org",
            "date": "7/27/2025",
            "time": "11:00 AM",
            "county": "Berks",
            "subject": " CRS Training",
            "body": "I am interested in becoming a Certified Recovery Specialist. I live in Reading. Do you have any training programs available?",
            "summary": "Individual expresses interest in CRS certification training",
            "isInquiry": true,
            "isStaffResponse": false
        },
        {
            "name": "alison dunn",
            "email": "alison.dunn@councilsepa.org",
            "date": "7/27/2025",
            "time": "11:30 AM",
            "county": "Unknown",
            "subject": "RE: CRS Training",
            "body": "Hi Peter, We have a CRS class starting in Reading in September. I have attached the full schedule and registration link. Let me know if you have any questions. Allison",
            "summary": "Staff provides CRS training information and support",
            "isInquiry": false,
            "isStaffResponse": true
        },
        {
            "name": "Nancy Wilson",
            "email": "nancy.wilson@example.com",
            "date": "7/28/2025",
            "time": "9:00 AM",
            "county": "Philadelphia",
            "subject": "My Recovery Journey",
            "body": "I have been in recovery for 5 years and I am looking for a way to help others. I heard about your CRS program and was wondering if it would be a good fit for me. I live in Philly. Any information would be helpful. Thanks, Nancy",
            "summary": "Individual shares recovery story and training interest",
            "isInquiry": true,
            "isStaffResponse": false
        },
        {
            "name": "Christopher Rodican",
            "email": "christopher.rodican@councilsepa.org",
            "date": "7/28/2025",
            "time": "9:15 AM",
            "county": "Unknown",
            "subject": "RE: My Recovery Journey",
            "body": "Hi Nancy, That's wonderful! We would be honored to have you as part of our program. I have attached a brochure with details about the CRS training. Please let me know if you have any questions. Chris",
            "summary": "Staff provides CRS training information and support",
            "isInquiry": false,
            "isStaffResponse": true
        },
        {
            "name": "Michael Taylor",
            "email": "michael.taylor@example.org",
            "date": "7/29/2025",
            "time": "1:00 PM",
            "county": "Chester",
            "subject": "Scholarship Question",
            "body": "To whom it may concern, I am writing on behalf of a client who is interested in the CRS training. We are looking for information on scholarship or funding options that may be available to them. Our client is in Exton. Please let us know if you can assist. Best, Michael Taylor Chester County Alliance",
            "summary": "Organization requests scholarship information for client",
            "isInquiry": true,
            "isStaffResponse": false
        },
        {
            "name": "jim bollinger",
            "email": "jim.bollinger@councilsepa.org",
            "date": "7/29/2025",
            "time": "1:30 PM",
            "county": "Unknown",
            "subject": "RE: Scholarship Question",
            "body": "Hi Michael, Thank you for your inquiry. We have several scholarship options available. I'll connect you with our scholarship coordinator who can provide the details and assist your client with the application process. Jim",
            "summary": "Staff responds to scholarship funding inquiry",
            "isInquiry": false,
            "isStaffResponse": true
        }
    ];