        const emailData = [
            {
                "name": "joshua shorts",
                "email": "joshuashorts232@yahoo.com",
                "date": "6/3/2025",
                "time": "2:49 PM",
                "subject": "Next available class",
                "body": "Hi my name is Joshua shorts and I m interested in the next class you have available to become a certified peer specialist please contact me via email or phone at 267 453 6181 thank you",
                "county": "Unknown",
                "summary": "Joshua Shorts expresses interest in becoming a certified peer specialist and requests contact via email or phone.",
                "isInquiry": true,
                "isStaffResponse": false
            },
            {
                "name": "Amy Legath",
                "email": "amylegath@gmail.com",
                "date": "6/3/2025",
                "time": "9:33 PM",
                "subject": "Recovery Specialist Training",
                "body": "Good Evening,  I am interested in enrolling in the Certified Recovery Specialist course. I am just shy of 19 months sober (AA) and have been interested in close to a year to complete this training program. What is the next step?  Warmest Regards,   Amy Legath",
                "county": "Unknown",
                "summary": "Amy inquires about enrolling in CRS course, mentions being shy of 19 months sober and interested for close to a year.",
                "isInquiry": true,
                "isStaffResponse": false
            },
            {
                "name": "Alison Dunn",
                "email": "adunn@councilsepa.org",
                "date": "6/10/2025",
                "time": "11:23 AM",
                "subject": "RE: CRS Training",
                "body": "Good morning Alyssa, Currently, we are taking applications to identify the class size. Could you follow back up with me around the beginning of July and I will have a better idea on if we can accommodate your make up days. Please let me know the exact Learner Manual pages you need to cover as each class can flow differently. Additionally, what class were you in and what county are you travelling from? Thank you, Ali Dunn, CRS/CFRS/CRSS",
                "county": "Montgomery",
                "summary": "Response to Alyssa Murriell about make-up days for Montgomery County training, requesting specific details and follow-up in July.",
                "isInquiry": false,
                "isStaffResponse": true
            },
            {
                "name": "Christopher Rodican",
                "email": "crodican@councilsepa.org",
                "date": "6/10/2025",
                "time": "2:21 PM",
                "subject": "RE: Crs training Carolyn Suhrcke",
                "body": "Carolyn, Thank you for reaching out, congratulations on your recovery, and on your interest in Recovery Specialist certification.  The CRS is for individuals with personal, lived recovery experience, and it's a wonderful way to your personal, lived recovery experience to assist other individuals in recovery from substance use disorder as a role model, mentor, advocate, and motivator.     To better assist you, could you please let us know the counties where you live and work?     We offer several Recovery Specialist trainings in Southeast Pennsylvania each year at no cost to the participants.  These trainings are available to individuals who live or work in the county where the training is conducted.  Please fill out this short Recovery Specialist Interest Survey form, and someone will contact you with the next steps when a suitable training is available for you.",
                "county": "Unknown",
                "summary": "Response to Carolyn Mahn providing comprehensive CRS training information, survey link, and PCB training list.",
                "isInquiry": false,
                "isStaffResponse": true
            },
            {
                "name": "Anita James",
                "email": "anitajames1306@icloud.com",
                "date": "6/12/2025",
                "time": "11:36 AM",
                "subject": "CRS Course Inquiry",
                "body": "Hello my name is Anita.  I am interested in taking the CRS course. I have 2 years and 7 months clean, I also have been working one treatment as a BHT for 18 months. You can contact me at 445-224-8978 or my email. Thank you so much for your time. Have a wonderful day.",
                "county": "Unknown",
                "summary": "Anita expresses interest in CRS course, mentions 2 years 7 months clean and 18 months working in treatment as BHT.",
                "isInquiry": true,
                "isStaffResponse": false
            },
            {
                "name": "Christopher Rodican",
                "email": "crodican@councilsepa.org",
                "date": "6/12/2025",
                "time": "2:46 PM",
                "subject": "RE: CRS Course Inquiry",
                "body": "Hi Anita,  Thanks for reaching out!  To better assist you, could you please let us know the counties where you live and work?  We offer several Recovery Specialist trainings in Southeast Pennsylvania each year at no cost to the participants.  These trainings are available to individuals who live or work in the county where the training is conducted.  Please fill out this short Recovery Specialist Interest Survey form, and someone will contact you with the next steps when a suitable training is available for you.  [link]  In the meantime, the Pennsylvania Certification Board keeps an up to date list of every upcoming Recovery Specialist training across the state.  You can always check it regularly in case there is another organization with a suitable Recovery Specialist training for you.  The prices for the trainings, the locations, the dates, and instructor's contact info are included.  If interested in a class, rather than click the green enroll button, you will want to email the instructor.  [link] Best of luck to you!",
                "county": "Unknown",
                "summary": "Response to Anita James asking for county information and providing Recovery Specialist Interest Survey and PCB training list.",
                "isInquiry": false,
                "isStaffResponse": true
            },
            {
                "name": "Christopher Rodican",
                "email": "crodican@councilsepa.org",
                "date": "6/12/2025",
                "time": "2:51 PM",
                "subject": "RE: Recovery Specialist Training",
                "body": "Joshua,  A Certified Recovery Specialist is an individual who has lived experience with substance use disorder recovery and is certified to provide peer support to others on their recovery journey.  A CPS (Certified Peer Specialist), on the other hand, is an individual who has lived experience with mental health challenges and recovery and is certified to provide peer support to others facing similar struggles.  Both CRS and CPS are types of 'peer specialists'. They are trained and certified by the Pennsylvania Certification Board (PCB).  Which certification were you inquiring about?",
                "county": "Chester",
                "summary": "Response to Amy Legath congratulating her recovery, requesting county info, and providing survey link and training resources.",
                "isInquiry": false,
                "isStaffResponse": true
            },
            {
                "name": "Amy Legath",
                "email": "amylegath@gmail.com",
                "date": "6/12/2025",
                "time": "2:57 PM",
                "subject": "Re: Recovery Specialist Training",
                "body": "                                                                                                                                                                                                                                                                       ",
                "county": "Chester",
                "summary": "Amy specifies Chester County location, requests low-cost Saturday training due to full-time work and caring for autistic son.",
                "isInquiry": true,
                "isStaffResponse": false
            },
            {
                "name": "Christopher Rodican",
                "email": "crodican@councilsepa.org",
                "date": "6/12/2025",
                "time": "2:58 PM",
                "subject": "RE: Next available class",
                "body": "",
                "county": "Unknown",
                "summary": "Response to Joshua Shorts explaining difference between CRS and CPS certifications and asking which he was interested in.",
                "isInquiry": false,
                "isStaffResponse": true
            },
            {
                "name": "Christopher Rodican",
                "email": "crodican@councilsepa.org",
                "date": "6/12/2025",
                "time": "3:27 PM",
                "subject": "RE: Recovery Specialist Training",
                "body": "",
                "county": "Montgomery",
                "summary": "Follow-up to Amy providing Pottstown training link and PCB statewide list, noting weekday schedule and limited slots.",
                "isInquiry": false,
                "isStaffResponse": true
            },
            {
                "name": "Amy Legath",
                "email": "amylegath@gmail.com",
                "date": "6/12/2025",
                "time": "3:43 PM",
                "subject": "Re: Recovery Specialist Training",
                "body": "",
                "county": "Chester",
                "summary": "Amy mentions Pottstown is too far from Coatesville, asks about Reading/Lancaster options and password issues.",
                "isInquiry": true,
                "isStaffResponse": false
            },
            {
                "name": "Alyssa Brennan",
                "email": "abrennan1991@icloud.com",
                "date": "6/12/2025",
                "time": "6:17 PM",
                "subject": "CRS",
                "body": "",
                "county": "Bucks",
                "summary": "Alyssa requests information about getting CRS certification and guidance on the process.",
                "isInquiry": true,
                "isStaffResponse": false
            },
            {
                "name": "Christopher Rodican",
                "email": "crodican@councilsepa.org",
                "date": "6/13/2025",
                "time": "6:29 PM",
                "subject": "Re: Recovery Specialist Training",
                "body": "",
                "county": "Unknown",
                "summary": "Clarification to Amy about enrollment process - explaining to email instructor rather than use green enrollment button.",
                "isInquiry": false,
                "isStaffResponse": true
            },
            {
                "name": "Alison Dunn",
                "email": "adunn@councilsepa.org",
                "date": "6/16/2025",
                "time": "9:44 AM",
                "subject": "RE: Trying to register for the crs course",
                "body": "",
                "county": "Montgomery",
                "summary": "Response to Ange about Montgomery County training registration, providing flyer and application link with June 30th deadline.",
                "isInquiry": false,
                "isStaffResponse": true
            },
            {
                "name": "Alison Dunn",
                "email": "adunn@councilsepa.org",
                "date": "6/16/2025",
                "time": "9:51 AM",
                "subject": "RE: CFRS training July",
                "body": "",
                "county": "Montgomery",
                "summary": "Response to Diane from Exton Parents about July CFRS training, mentions blended CRS/CFRS class with high interest.",
                "isInquiry": false,
                "isStaffResponse": true
            },
            {
                "name": "Christopher Rodican",
                "email": "crodican@councilsepa.org",
                "date": "6/16/2025",
                "time": "10:14 AM",
                "subject": "Re: CRS",
                "body": "",
                "county": "Bucks",
                "summary": "Response to Alyssa Brennan providing CRS info, noting she's from Bucks County, and offering Pottstown training option.",
                "isInquiry": false,
                "isStaffResponse": true
            },
            {
                "name": "Alison Dunn",
                "email": "adunn@councilsepa.org",
                "date": "6/16/2025",
                "time": "10:36 AM",
                "subject": "Recovery Specialist interest Survey",
                "body": "",
                "county": "Unknown",
                "summary": "Providing Recovery Specialist Training Interest Survey link to Serephine for future training notifications.",
                "isInquiry": false,
                "isStaffResponse": true
            },
            {
                "name": "Alison Dunn",
                "email": "adunn@councilsepa.org",
                "date": "6/16/2025",
                "time": "2:34 PM",
                "subject": "RE: Recovery Specialist Cert Program",
                "body": "",
                "county": "Montgomery",
                "summary": "Response to Joanna Roth about Montgomery County training enrollment, providing application process details.",
                "isInquiry": false,
                "isStaffResponse": true
            },
            {
                "name": "Joanna Roth",
                "email": "joannaroth84@gmail.com",
                "date": "6/16/2025",
                "time": "2:54 PM",
                "subject": "Re: Recovery Specialist Cert Program",
                "body": "",
                "county": "Montgomery",
                "summary": "Joanna confirms she found the application link in flyer and submitted her application, thanks Alison for quick response.",
                "isInquiry": true,
                "isStaffResponse": false
            },
            {
                "name": "Christopher Rodican",
                "email": "crodican@councilsepa.org",
                "date": "6/16/2025",
                "time": "3:01 PM",
                "subject": "RE: Next available class",
                "body": "",
                "county": "Unknown",
                "summary": "Follow-up to Joshua after phone conversation, providing Recovery Specialist Interest Survey and PCB training list guidance.",
                "isInquiry": false,
                "isStaffResponse": true
            },
            {
                "name": "Alison Dunn",
                "email": "adunn@councilsepa.org",
                "date": "6/17/2025",
                "time": "2:19 PM",
                "subject": "RE: CRS program information: Jasmine Baez",
                "body": "",
                "county": "Montgomery",
                "summary": "Response to Jasmine providing Montgomery County training application process and deadline information.",
                "isInquiry": false,
                "isStaffResponse": true
            },
            {
                "name": "Joan Rajkowski",
                "email": "djraj1128@gmail.com",
                "date": "6/21/2025",
                "time": "9:26 PM",
                "subject": "CRS Training program",
                "body": "Hi, My name is Joanie Rajkowski.  I have applied to the program in the past and I thought I got a seat but never heard back from anyone that I left messages to. I would like to apply again and hope to get in for the 2 Weeks or the Saturday program preferably because I m looking actively for employment to work during the week.  Please get back to me and I will redo The application.  Thank you for your time and consideration.  Sincerely,  Joan Rajkowski  215-869-6101",
                "county": "Unknown",
                "summary": "Joan mentions previous application issues, seeks 2-week or Saturday program due to active job searching during weekdays.",
                "isInquiry": true,
                "isStaffResponse": false
            },
            {
                "name": "Alison Dunn",
                "email": "adunn@councilsepa.org",
                "date": "6/23/2025",
                "time": "4:25 PM",
                "subject": "RE: Recovery Specialist Training",
                "body": "",
                "county": "Montgomery",
                "summary": "Response to Debbie Soto-Vega noting Montgomery County class may be full, providing application info and interest survey.",
                "isInquiry": false,
                "isStaffResponse": true
            },
            {
                "name": "Alison Dunn",
                "email": "adunn@councilsepa.org",
                "date": "6/23/2025",
                "time": "4:30 PM",
                "subject": "RE: Recovery Specialist Training",
                "body": "",
                "county": "Berks",
                "summary": "Response to Andrea Rose about Kelly Schaeffer's memorial service conflict, noting class appears full.",
                "isInquiry": false,
                "isStaffResponse": true
            },
            {
                "name": "Alison Dunn",
                "email": "adunn@councilsepa.org",
                "date": "6/23/2025",
                "time": "4:32 PM",
                "subject": "Recovery Specialist Interest Survey",
                "body": "",
                "county": "Unknown",
                "summary": "Providing Jackie with Montgomery County training info noting class may be full, plus Philadelphia training options.",
                "isInquiry": false,
                "isStaffResponse": true
            },
            {
                "name": "Alison Dunn",
                "email": "adunn@councilsepa.org",
                "date": "6/25/2025",
                "time": "12:11 PM",
                "subject": "RE: CRS CLASSES",
                "body": "",
                "county": "Montgomery",
                "summary": "Response to Brendan Bungay explaining Montgomery County class appears full, providing application process details.",
                "isInquiry": false,
                "isStaffResponse": true
            },
            {
                "name": "Andrea Rose",
                "email": "arose@recoverycoachingservices.com",
                "date": "6/26/2025",
                "time": "11:55 AM",
                "subject": "Re: Recovery Specialist Training",
                "body": "",
                "county": "Berks",
                "summary": "Andrea confirms Montgomery class is full and Kelly can't attend, asks about future training availability.",
                "isInquiry": true,
                "isStaffResponse": false
            },
            {
                "name": "R Wills",
                "email": "rafiya127@gmail.com",
                "date": "7/22/2025",
                "time": "4:48 PM",
                "subject": "CRS",
                "body": "",
                "county": "Unknown",
                "summary": "Rafiya Williams requests to join CRS training and provides phone number 2679007117.",
                "isInquiry": true,
                "isStaffResponse": false
            },
            {
                "name": "R Wills",
                "email": "rafiya127@gmail.com",
                "date": "7/22/2025",
                "time": "4:51 PM",
                "subject": "CRS TRAINING",
                "body": "",
                "county": "Unknown",
                "summary": "Follow-up email from Rafiya Williams expressing interest in CRS training.",
                "isInquiry": true,
                "isStaffResponse": false
            },
            {
                "name": "Alison Dunn",
                "email": "adunn@councilsepa.org",
                "date": "7/23/2025",
                "time": "12:35 PM",
                "subject": "Recovery Specialist Interest Survey",
                "body": "",
                "county": "Unknown",
                "summary": "Response to artis1214@gmail.com providing Recovery Specialist Interest Survey link and upcoming class information.",
                "isInquiry": false,
                "isStaffResponse": true
            },
            {
                "name": "Jennifer Carroll",
                "email": "jacrroll@councilsepa.org",
                "date": "7/23/2025",
                "time": "1:35 PM",
                "subject": "Recovery Specialist Training Interest Survey",
                "body": "",
                "county": "Unknown",
                "summary": "Response to Lisa (lisamensch094@gmail.com) with interest survey link and information about enrollment process.",
                "isInquiry": false,
                "isStaffResponse": true
            },
            {
                "name": "Jennifer Carroll",
                "email": "jacrroll@councilsepa.org",
                "date": "7/23/2025",
                "time": "1:48 PM",
                "subject": "Recovery Specialist Interest Survey",
                "body": "",
                "county": "Unknown",
                "summary": "Standard response template providing Recovery Specialist Interest Survey link for enrollment.",
                "isInquiry": false,
                "isStaffResponse": true
            },
            {
                "name": "quarantine@messaging.microsoft.com",
                "email": "",
                "date": "7/23/2025",
                "time": "6:09 PM",
                "subject": "Microsoft 365 security: You have messages in quarantine",
                "body": "",
                "county": "Unknown",
                "summary": "Microsoft security notification about quarantined message from malcolmb2595@gmail.com flagged as phishing.",
                "isInquiry": false,
                "isStaffResponse": false
            },
            {
                "name": "Christopher Rodican",
                "email": "crodican@councilsepa.org",
                "date": "7/25/2025",
                "time": "8:46 AM",
                "subject": "RE: CRS TRAINING",
                "body": "",
                "county": "Unknown",
                "summary": "Response to Rafiya Williams explaining CRS certification requirements, asking for location details, and providing survey link and training information.",
                "isInquiry": false,
                "isStaffResponse": true
            },
            {
                "name": "Christopher Rodican",
                "email": "crodican@councilsepa.org",
                "date": "7/27/2025",
                "time": "6:30 PM",
                "subject": "test",
                "body": "",
                "county": "Unknown",
                "summary": "Internal test email with no content.",
                "isInquiry": false,
                "isStaffResponse": false
            },
            {
                "name": "Christopher Rodican",
                "email": "christopher.rodican@gmail.com",
                "date": "7/27/2025",
                "time": "6:37 PM",
                "subject": "test email",
                "body": "",
                "county": "Unknown",
                "summary": "External test email from Christopher Rodican's personal Gmail account.",
                "isInquiry": false,
                "isStaffResponse": false
            },
            {
                "name": "Christina Pooler",
                "email": "christina.pooler@gmail.com",
                "date": "7/28/2025",
                "time": "9:41 AM",
                "subject": "CRS Training",
                "body": "",
                "county": "Delaware",
                "summary": "Inquiry from Delaware County resident about CRS training availability, format, location, prerequisites, and costs. Mentions 3 years sobriety.",
                "isInquiry": true,
                "isStaffResponse": false
            },
            {
                "name": "Christopher Rodican",
                "email": "crodican@councilsepa.org",
                "date": "7/29/2025",
                "time": "10:00 AM",
                "subject": "RE: Recovery Specialist Training",
                "body": "",
                "county": "Delaware",
                "summary": "Response to Shawn confirming he's on waiting list for Delaware County training and providing alternative training options.",
                "isInquiry": false,
                "isStaffResponse": true
            },
            {
                "name": "Christopher Rodican",
                "email": "crodican@councilsepa.org",
                "date": "7/29/2025",
                "time": "1:25 PM",
                "subject": "RE: Recovery Specialist Training",
                "body": "",
                "county": "Berks",
                "summary": "Instructions for Shawn on how to contact facilitator for Reading training enrollment.",
                "isInquiry": false,
                "isStaffResponse": true
            },
            {
                "name": "Alison Dunn",
                "email": "adunn@councilsepa.org",
                "date": "7/29/2025",
                "time": "2:07 PM",
                "subject": "Bucks County Recovery Specialist Training - October 2025",
                "body": "",
                "county": "Bucks",
                "summary": "Mass email to Bucks County residents about October 2025 Recovery Specialist Training with registration link.",
                "isInquiry": false,
                "isStaffResponse": true
            },
            {
                "name": "Sean Ripley",
                "email": "smripley@gmail.com",
                "date": "7/29/2025",
                "time": "2:09 PM",
                "subject": "Re: Bucks County Recovery Specialist Training - October 2025",
                "body": "",
                "county": "Bucks",
                "summary": "Positive response from Sean Ripley confirming he will register for the October Bucks County training.",
                "isInquiry": true,
                "isStaffResponse": false
            },
            {
                "name": "Alison Dunn",
                "email": "adunn@councilsepa.org",
                "date": "7/29/2025",
                "time": "2:10 PM",
                "subject": "RE: Bucks County Recovery Specialist Training - October 2025",
                "body": "",
                "county": "Bucks",
                "summary": "Brief acknowledgment response to Sean Ripley wishing him a great day.",
                "isInquiry": false,
                "isStaffResponse": true
            },
            {
                "name": "Casilyn Papiro",
                "email": "casipapirio@gmail.com",
                "date": "7/29/2025",
                "time": "2:30 PM",
                "subject": "Re: Bucks County Recovery Specialist Training - October 2025",
                "body": "",
                "county": "Bucks",
                "summary": "Casilyn Papirio explains she already completed training but certification lapsed during breast cancer recovery; she's been in remission for 3 years and ready to return to work.",
                "isInquiry": true,
                "isStaffResponse": false
            },
            {
                "name": "tania_oneill25",
                "email": "tania_oneill25@yahoo.com",
                "date": "7/29/2025",
                "time": "3:31 PM",
                "subject": "RE: Bucks County Recovery Specialist Training - October 2025",
                "body": "",
                "county": "Bucks",
                "summary": "Tania O'Neill expresses interest in October training but needs information about funding or financial assistance.",
                "isInquiry": true,
                "isStaffResponse": false
            },
            {
                "name": "Alison Dunn",
                "email": "adunn@councilsepa.org",
                "date": "7/30/2025",
                "time": "9:14 AM",
                "subject": "RE: Bucks County Recovery Specialist Training - October 2025",
                "body": "",
                "county": "Bucks",
                "summary": "Response to Tania directing her to complete registration form for information about funding, as this training is not facilitated by their organization.",
                "isInquiry": false,
                "isStaffResponse": true
            },
            {
                "name": "Alison Dunn",
                "email": "adunn@councilsepa.org",
                "date": "7/30/2025",
                "time": "9:21 AM",
                "subject": "RE: Bucks County Recovery Specialist Training - October 2025",
                "body": "",
                "county": "Bucks",
                "summary": "Response to Trevor Hahn about TMS account requirement and Keystone Login setup instructions for registration.",
                "isInquiry": false,
                "isStaffResponse": true
            },
            {
                "name": "Christopher Rodican",
                "email": "crodican@councilsepa.org",
                "date": "7/31/2025",
                "time": "2:05 PM",
                "subject": "RE: [blank]",
                "body": "",
                "county": "Berks",
                "summary": "Clarification to Shawn about contacting the correct facilitator for Reading training, includes training list link.",
                "isInquiry": false,
                "isStaffResponse": true
            },
            {
                "name": "Alison Dunn",
                "email": "adunn@councilsepa.org",
                "date": "8/1/2025",
                "time": "10:12 AM",
                "subject": "Recovery Specialist Interest Survey and Upcoming Bucks County Recovery Specialist Training - October 2025",
                "body": "",
                "county": "Bucks",
                "summary": "Outreach to Elvin Colon at Pocono MRC sharing interest survey and October Bucks County training information.",
                "isInquiry": false,
                "isStaffResponse": true
            },
            {
                "name": "Christopher Rodican",
                "email": "crodican@councilsepa.org",
                "date": "8/1/2025",
                "time": "1:42 PM",
                "subject": "RE: Re:",
                "body": "",
                "county": "Unknown",
                "summary": "Follow-up with Shawn confirming phone number (267-817-4972) and offering continued assistance.",
                "isInquiry": false,
                "isStaffResponse": true
            },
            {
                "name": "Jacquelyn Hagen",
                "email": "hagenjacquelyn7@gmail.com",
                "date": "8/4/2025",
                "time": "1:21 PM",
                "subject": "Re: Bucks County Recovery Specialist Training - October 2025",
                "body": "",
                "county": "Bucks",
                "summary": "Jacquelyn mentions being on waitlist for Saturday Philadelphia class through Jennifer Carroll, asks about Saturday options in Bucks County.",
                "isInquiry": true,
                "isStaffResponse": false
            },
            {
                "name": "Ashley Crozier",
                "email": "croziera@live.bucks.edu",
                "date": "8/8/2025",
                "time": "6:48 AM",
                "subject": "Re: Bucks County Recovery Specialist Training - October 2025",
                "body": "",
                "county": "Bucks",
                "summary": "Ashley asks about weekend-only availability due to current employment schedule preventing weekday attendance.",
                "isInquiry": true,
                "isStaffResponse": false
            },
            {
                "name": "Alison Dunn",
                "email": "adunn@councilsepa.org",
                "date": "8/8/2025",
                "time": "10:02 AM",
                "subject": "RE: CFRS Trainings?",
                "body": "",
                "county": "Chester",
                "summary": "Response to Kim Porter about CFRS training availability, mentions no current CFRS-specific training scheduled but one planned for later in year. Provides interest survey and Chester County PSEI option.",
                "isInquiry": false,
                "isStaffResponse": true
            },
            {
                "name": "Kim Porter",
                "email": "kim@conversation.zone",
                "date": "8/8/2025",
                "time": "11:42 AM",
                "subject": "Re: CFRS Trainings?",
                "body": "",
                "county": "Unknown",
                "summary": "Kim Porter thanks Alison for helpful information and confirms she'll pass along info to Synergy House.",
                "isInquiry": false,
                "isStaffResponse": false
            }
        ];