const jsonData = 
[
    {
        "Location Name": "Unity Recovery- Philadelphia",
        "Organization": "Unity Recovery",
        "County": "Philadelphia",
        "Domain": "Recovery Support",
        "Category": "Recovery Community Organization",
        "Populations Served": "Men; Women",
        "More Info": "",
        "Phone": "267-748-2454",
        "Address": "106 Gay Street, Floor 2",
        "City": "Philadelphia",
        "State": "PA",
        "Zip Code": "19127",
        "Website": "https://unityrecovery.org/rss-interest-philadelphia",
        "Image": "https://unityrecovery.org/wp-content/uploads/2019/03/Main_Logo_Large-1.jpg",
        "Latitude": "",
        "Longitude": "",
        "Slug": "8"
    },
    {
        "Location Name": "Philadelphia Recovery Community Center",
        "Organization": "The Council of Southeast Pennsylvania",
        "County": "Philadelphia",
        "Domain": "Recovery Support",
        "Category": "Recovery Community Organization",
        "Populations Served": "Men; Women",
        "More Info": "PRO-ACT Philadelphia County Recovery Support Services",
        "Phone": "215-223-7700",
        "Address": "1701 W. Lehigh Avenue, #6",
        "City": "Philadelphia",
        "State": "PA",
        "Zip Code": "19132",
        "Website": "https://www.councilsepa.org/pro-act-recovery-support-services/",
        "Image": "https://lh3.googleusercontent.com/d/17HjRJ68MnAoRokMSl5cWd0ezsN2sbB9I",
        "Latitude": "39.994841",
        "Longitude": "-75.160134",
        "Slug": "13"
    },
    {
        "Location Name": "Philadelphia Recovery Training Center",
        "Organization": "The Council of Southeast Pennsylvania",
        "County": "Philadelphia",
        "Domain": "Recovery Support",
        "Category": "Recovery Community Organization",
        "Populations Served": "Men; Women",
        "More Info": "FLYY – Fostering Leadership in Youth and Young Adults Early Intervention Program, Philadelphia Recovery Training Program, Philadelphia Peer Leadership Academy, Supporting Youth Recovery",
        "Phone": "267-817-7661",
        "Address": "520 North Columbus Blvd., Suite 203",
        "City": "Philadelphia",
        "State": "PA",
        "Zip Code": "19123",
        "Website": "https://www.councilsepa.org/prevention-training-and-education/",
        "Image": "https://lh3.googleusercontent.com/d/1aEt7QZJNtfXQyKqfP0V0v2l9uSZ7QHoQ",
        "Latitude": "39.959861",
        "Longitude": "-75.137905",
        "Slug": "14"
    },
    {
        "Location Name": "Regional Recovery Hub 1",
        "Organization": "The Council of Southeast Pennsylvania",
        "County": "Philadelphia",
        "Domain": "Recovery Support",
        "Category": "Regional Recovery Hub",
        "Populations Served": "Men; Women",
        "More Info": "Jennifer Carol; Regional Recovery Hub Project Coordinator\n267.817.4898 – jcarroll@councilsepa.org\nAnthony Bynum; Regional Recovery Hub Project Coordinator\n267.817.8036 – abynum@councilsepa.org\nFrederick K. Shue; Regional Recovery Hub Administrative Coordinator\n267.817.7016 - fshue@councilsepa.org",
        "Phone": "215-223-7700",
        "Address": "1701 West Lehigh Ave",
        "City": "Philadelphia",
        "State": "PA",
        "Zip Code": "19132",
        "Website": "https://www.councilsepa.org/recovery-hubs/",
        "Image": "https://councilsepa.org/wp-content/uploads/2024/03/logo.svg",
        "Latitude": "39.99507238",
        "Longitude": "-75.16011318",
        "Slug": "73"
    },
    {
        "Location Name": "Mental Health Partnerships",
        "Organization": "Mental Health Partnerships",
        "County": "Philadelphia",
        "Domain": "Recovery Support",
        "Category": "Recovery Community Organization",
        "Populations Served": "Men; Women",
        "More Info": "CPS Services, Mental Health and SUD Peer Support",
        "Phone": "800-688-4226",
        "Address": "833 Chestnut St # 1100",
        "City": "Philadelphia",
        "State": "PA",
        "Zip Code": "19107",
        "Website": "https://www.mentalhealthpartnerships.org/",
        "Image": "https://images.squarespace-cdn.com/content/v1/64356437c0ce5179e88b5ffe/281d5bdc-1f6e-43a0-95f2-dc8ea5ec3b14/MHP-17-Logo-Tagline.png",
        "Latitude": "39.95007182",
        "Longitude": "-75.15510753",
        "Slug": "88.49236995"
    },
    {
        "Location Name": "Targeted Case Management, Mental Health Partnerships",
        "Organization": "Mental Health Partnerships",
        "County": "Philadelphia",
        "Domain": "Recovery Support",
        "Category": "Recovery Community Organization",
        "Populations Served": "Men; Women",
        "More Info": "CPS Services, Mental Health and SUD Peer Support",
        "Phone": "267-507-3950",
        "Address": "4950 Parkside Avenue, Suite 200",
        "City": "Philadelphia",
        "State": "PA",
        "Zip Code": "19131",
        "Website": "https://www.mentalhealthpartnerships.org/",
        "Image": "https://images.squarespace-cdn.com/content/v1/64356437c0ce5179e88b5ffe/281d5bdc-1f6e-43a0-95f2-dc8ea5ec3b14/MHP-17-Logo-Tagline.png",
        "Latitude": "39.97952906",
        "Longitude": "-75.218546",
        "Slug": "89.52415125"
    },
    {
        "Location Name": "The Well Recovery Learning Center",
        "Organization": "Mental Health Partnerships",
        "County": "Philadelphia",
        "Domain": "Recovery Support",
        "Category": "Recovery Community Organization",
        "Populations Served": "Men; Women",
        "More Info": "CPS Services, Mental Health and SUD Peer Support",
        "Phone": "267-507-3466",
        "Address": "2709 North Broad Street",
        "City": "Philadelphia",
        "State": "PA",
        "Zip Code": "19132",
        "Website": "https://www.mentalhealthpartnerships.org/",
        "Image": "https://images.squarespace-cdn.com/content/v1/64356437c0ce5179e88b5ffe/281d5bdc-1f6e-43a0-95f2-dc8ea5ec3b14/MHP-17-Logo-Tagline.png",
        "Latitude": "39.99463688",
        "Longitude": "-75.15407396",
        "Slug": "90.55593255"
    },
    {
        "Location Name": "A new Life Recovery Learning Center",
        "Organization": "Mental Health Partnerships",
        "County": "Philadelphia",
        "Domain": "Recovery Support",
        "Category": "Recovery Community Organization",
        "Populations Served": "Men; Women",
        "More Info": "CPS Services, Mental Health and SUD Peer Support",
        "Phone": "267-507-3530",
        "Address": "3119 Spring Garden Street",
        "City": "Philadelphia",
        "State": "PA",
        "Zip Code": "19104",
        "Website": "https://www.mentalhealthpartnerships.org/",
        "Image": "https://images.squarespace-cdn.com/content/v1/64356437c0ce5179e88b5ffe/281d5bdc-1f6e-43a0-95f2-dc8ea5ec3b14/MHP-17-Logo-Tagline.png",
        "Latitude": "39.96370023",
        "Longitude": "-75.18847145",
        "Slug": "91.58771384"
    },
    {
        "Location Name": "MyModivcare",
        "Organization": "",
        "County": "Philadelphia",
        "Domain": "Transportation",
        "Category": "Medical Assistance Transportation",
        "Populations Served": "Men; Women",
        "More Info": "",
        "Phone": "877-835-7412",
        "Address": "n/a",
        "City": "Philadelphia",
        "State": "PA",
        "Zip Code": "19104",
        "Website": "https://www.mymodivcare.com/book-now",
        "Image": "",
        "Latitude": "",
        "Longitude": "",
        "Slug": "253.5773775"
    },
    {
        "Location Name": "Substance Use Philly- Counseling",
        "Organization": "Philadelphia Department of Public Health",
        "County": "Philadelphia",
        "Domain": "Family Support",
        "Category": "",
        "Populations Served": "",
        "More Info": "Counseling for children age 4 to 21, and people in need of post-partum support.",
        "Phone": "",
        "Address": "",
        "City": "",
        "State": "",
        "Zip Code": "",
        "Website": "",
        "Image": "",
        "Latitude": "",
        "Longitude": "",
        "Slug": "271"
    },
    {
        "Location Name": "Interim House",
        "Organization": "PMHC",
        "County": "Philadelphia",
        "Domain": "Recovery Support",
        "Category": "Recovery House",
        "Populations Served": "Women; Children",
        "More Info": "Recovery house for women in recovery and their children.",
        "Phone": "215-849-0606",
        "Address": "333 West Upsal Street",
        "City": "Philadelphia",
        "State": "PA",
        "Zip Code": "19119",
        "Website": "https://interimhouse.phmc.org/",
        "Image": "https://interimhouse.phmc.org/templates/interimhouse/images/ihi-logo.gif",
        "Latitude": "40.04326487",
        "Longitude": "-75.18909891",
        "Slug": ""
    },
    {
        "Location Name": "Interim House West",
        "Organization": "PMHC",
        "County": "Philadelphia",
        "Domain": "Recovery Support",
        "Category": "Recovery House",
        "Populations Served": "Women; Children",
        "More Info": "Recovery house for women in recovery and their children.",
        "Phone": "215-871-0300",
        "Address": "4108 Parkside Avenue",
        "City": "Philadelphia",
        "State": "PA",
        "Zip Code": "19104",
        "Website": "https://interimhouse.phmc.org/",
        "Image": "https://interimhouse.phmc.org/templates/interimhouse/images/ihi-logo.gif",
        "Latitude": "",
        "Longitude": "",
        "Slug": ""
    },
    {
        "Location Name": "Substance Use Prevention and Harm Reduction (SUPHR) ",
        "Organization": "Philadelphia Department of Public Health",
        "County": "Philadelphia",
        "Domain": "Recovery Support",
        "Category": "",
        "Populations Served": "",
        "More Info": "",
        "Phone": "",
        "Address": "",
        "City": "",
        "State": "",
        "Zip Code": "",
        "Website": "",
        "Image": "",
        "Latitude": "",
        "Longitude": "",
        "Slug": ""
    },
    {
        "Location Name": "Philly HEALs",
        "Organization": "Philadelphia Department of Public Health",
        "County": "Philadelphia",
        "Domain": "Family Support",
        "Category": "Family Support Services",
        "Populations Served": "",
        "More Info": "",
        "Phone": "",
        "Address": "",
        "City": "",
        "State": "",
        "Zip Code": "",
        "Website": "",
        "Image": "",
        "Latitude": "",
        "Longitude": "",
        "Slug": ""
    }
]